### ISSUE TITLE
Module not installing on Prestashop Version 1.6.0.14

### ISSUE THREAD

**Issue by motion2082** [nenes25/eicaptcha#1]
Just letting you know this is not working on PS V1.6.0.14

**Comment by nenes25** [comment]
Hello,

Could you please be more specific ?
What kind of problem do you have ?

I've just tested on a fresh Prestashop Version 1.6.0.14 without any problems.

Regards,

**Comment by nenes25** [comment]
No return since one week.
The ticket is now closed, and will be reopened if necessary.

**Comment by motion2082** [comment]
Sorry please see thread
https://www.prestashop.com/forums/topic/442633-add-recaptcha-to-prestashop-version-16014-for-free/

Mail sending without checking reCAPTCHA

**Comment by motion2082** [comment]
Sorry please see thread https://www.prestashop.com/forums/topic/442633-add-recaptcha-to-prestashop-version-16014-for-free/

Mail sending without checking reCAPTCHA

**Comment by nenes25** [comment]
OK thanks, i have replied on this topic.
Waiting for more information on this subject.

**Comment by motion2082** [comment]
No worries, thank you for your hard work!
