### ISSUE TITLE
Uncaught Error: ReCAPTCHA placeholder element must be an element or id

### ISSUE THREAD

**Issue by nodirashidov** [nenes25/eicaptcha#10]
Hello, thank you for the capthca module

I was trying to implement it into my prestashop website (ver. 1.6.0.9), I keep getting the following error:

> Uncaught Error: ReCAPTCHA placeholder element must be an element or id

After googling this error, I found out that it is usually caused by the recapthca API being called more than once.

**How I installed the module:**
I cloned your repo, unzipped it into the modules folder, installed and enabled the module from the prestashop dashboard, pasted my public and secret codes and that is it. I did not edit the contact-form.tpl file (do I need to input the html manually? from what i could tell, i dont have to)

Could you please help me resolve this issue?

Thanks a lot

**Comment by nenes25** [comment]
Hello,

Did you run the command "composer install" or get the release file  as told in the README file ?
I've installed the module on a default prestashop 1.6.0.9 without any issues.

Regards,
Hervé

**Comment by nodirashidov** [comment]
I just cloned the repo as zip and installed it like that without running any commands.

I just downloaded the 0.4.9 release file and tried to install that in prestashop instead, but I get the same error as in my original post. I did not change any of my source codes.

> Uncaught Error: ReCAPTCHA placeholder element must be an element or id
>     at Object.nq [as render] (www.gstatic.com/recaptcha/api2/r20170717162708/recaptcha__en.js:410)
>     at onloadCallback (contact-us:133)
>     at aq (www.gstatic.com/recaptcha/api2/r20170717162708/recaptcha__en.js:405)
>     at www.gstatic.com/recaptcha/api2/r20170717162708/recaptcha__en.js:414
>     at www.gstatic.com/recaptcha/api2/r20170717162708/recaptcha__en.js:426

contact-us: lines 132-134

```
//Recaptcha CallBack Function
var onloadCallback = function() {grecaptcha.render("captcha-box", {"theme" : "light", "sitekey" : "**mypersonalgooglesitekey**"});};
</script><script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit&hl=" async defer></script>
```

**Comment by nenes25** [comment]
Do you use the standard prestashop theme or a custom one ?
The div captcha-box , is added automaticaly to the DOM by js as you can see  https://github.com/nenes25/eicaptcha/blob/master/eicaptcha.php#L340
If this line is not working, the google script will not work.
If you use a custom theme can you try to add the folowing code before the submit button ?
<div id="captcha-box"></div>

Regards,
Hervé

**Comment by nodirashidov** [comment]
Oh wow thanks! That worked! Thanks a lot!
