### ISSUE TITLE
 Ei Captcha not appearing in registration account! #66 Closed Nimstery opened this Issue on 22 May 2018 - I have the same problem but with prestashop 1.6

### ISSUE THREAD

**Issue by nath40360** [nenes25/eicaptcha#102]
### biocosmetic

###Everything is ok in the contact form, but when I go to the register screen there is no captcha box only the label "captcha" and i can not register, i have an message " captcha incorrect". 
When i test the installation of module the result is :

Success

    the module is compatible with your version
    the module is well registered in hook header
    the module is well registered in hook displayCustomerAccountForm
    the module is well registered in hook contactFormAccess
    the module is well registered in hook actionBeforeSubmitAccount
    Overrides are enabled on your website
    ContactController.php override exists
    ContactController.php override is present in class_index.php

Aditionnal informations

    Prestashop version 1.6.1.20
    Theme name biocosmetic
    Php version 7.1.26

Sometimes in the debug i have this error :

SecurityError: Permission denied to access property "a-vq2r0xdc4awh" on cross-origin object

Thanks for help.

**Comment by nenes25** [comment]
Hi,

Do you face this problem when using Quick Order checkout or the standard 5 steps ?
For the security error it may be linked with your host configuration ( see : https://stackoverflow.com/questions/42354076/recaptcha-permission-denied-to-access-property )

Regards,

**Comment by nath40360** [comment]
Hi,

with the standart 5 steps.

**Comment by nenes25** [comment]
Weird
So the issue is not recurrent ?
By the way you're the first i see who runs a prestashop 1.6 version on php 7.1 :D

**Comment by nath40360** [comment]
Hello,
I have installed another module and i have no more the problem.
Thank you for spending time on this trouble.

i knew this week end that prestashop 1.6 should not run on php 7 !

again thanks a lot for your help.

**Comment by nenes25** [comment]
Thanks for your feedback ;)
