### ISSUE TITLE
Error translation

### ISSUE THREAD

**Issue by osaya** [nenes25/eicaptcha#105]
### Your prestashop version
1.6.1.1
### Eicaptcha Version
0.4.16
### Do you use a specific theme
no
### Issue description

Is there a way - other than modifying eicaptcha.php - to translate sentence below?

> incorrect response to CAPTCHA challenge. Please try again.

**Comment by nenes25** [comment]
Hi,
There is a small issue on this translation on the contact-form.
It will be fixed in next realease, but for now you can translate it in the errors message section.
