### ISSUE TITLE
error: module is not registered in hook header

### ISSUE THREAD

**Issue by Lichtwanderer** [nenes25/eicaptcha#106]
### Issue description: 
Hello,
after installing the latest version (0.4.16) the following problem occurs: 
- in the advanced parameters of the module I get the error message: "the module is not registered in hook header" (check screenshot in the attachments)
in the front office the reCaptcha occurs with the error message: "error for site owner: Invalid site key” (in german it's: "Fehlerhinweis für Inhaber der Website: Schlüsseltyp ungültig")
I have correctly registered domain in google reCaptcha site and entered the correct keys in the module.
Do you know a solution?
Thank you very much
![error - module is not registered in hook header](https://user-images.githubusercontent.com/50104178/56893307-83bcec00-6a82-11e9-8b7c-f04007291930.JPG)
![error for site owner - Invalid site key](https://user-images.githubusercontent.com/50104178/56893308-83bcec00-6a82-11e9-9e4d-0147b0d16645.JPG)

**Comment by nenes25** [comment]
Hi,
Try to reset the module in order to fix the display header error.
If it's still not working you can add it manually through the back office.

For the site key, this error can appear when you use the wrong fields ( for site key and the secret key )
Or when the data are wrong ( beware of the begining and/or trailing spaces )

Regards,

**Comment by Lichtwanderer** [comment]
Hi,
thank you for the quick reply. 
I have just deinstalled and reinstalled the module, and entered the site key and secret key again, but the errors still remain. 
There is really not much to do wrong entering the keys. There are only 2 and they are labelled; the codes are correct (no trailing spaces, etc.)
What do you mean by adding the module manually through the back office? Via FTP? 
Thanks

**Comment by nenes25** [comment]
Hi,
Not really you can add module to hook through the admin.
Click on Modules & services / Positions / , then on the button "Transplant a module"
![image](https://user-images.githubusercontent.com/7163132/56920267-14b3b780-6ac3-11e9-882a-c3fc88ea6112.png)

Regards,

**Comment by Lichtwanderer** [comment]
Hi,
thanks for your answer. 
I have tried to add it manually:
![Unbenannt](https://user-images.githubusercontent.com/50104178/56921109-331ab280-6ac5-11e9-96bc-b64b9dcb01ca.JPG)

but it tells me that it's already hooked in:
![Unbenannt](https://user-images.githubusercontent.com/50104178/56921168-59d8e900-6ac5-11e9-82c0-94db1cd435a7.JPG)

Both errors still remain.

**Comment by Lichtwanderer** [comment]
Hi again,
I found the error for the invalid site key: It only occurs, when I choose Google reCaptcha Version 3. When I choose Version 2, the error disappears and the reCaptcha is displayed correctly in the front office (and works correctly, too). 
So apparently the module only works with reCaptcha Version 2!?

**Comment by nenes25** [comment]
Yes it only works with v2.
Ok so for the hook it may be a false positive, so everything is working now ?

**Comment by Lichtwanderer** [comment]
it seems to work now, except for the problem with the customer registration page. You deactivated this function in the new release (0.4.17). But actually now there is no protection against robots in the registration formular anymore. However that is where I am having a lot of spams lately. Is there a chance that you get the issue fixed, so that the reCaptcha will be activated and well functioning on the registration form, as well?
Thank you anyway for offering this module for free!

**Comment by nenes25** [comment]
Yes the account verification is disabled on customer account but only in OPC checkout.
With the last returns i've had it seems this one is less spamed than the standard one.

For now i've no clean solution to make it works without overriding the opc javascript file which might cause a lot of problem related to the theme of the store.
Or to override the ordercontroller to manage it.

You can find a suggestion to implement it here : https://github.com/nenes25/eicaptcha/issues/103#issuecomment-486986207

**Comment by Lichtwanderer** [comment]
OK, thanks. Actually I have received quite a bit of Spam registrations on the OPC checkout, so it would be nice, if there was a reCaptcha here, too. But if you cannot find a solution for that, that's OK. It is fair enough, that you offer a free solution anyway, thank you again for that.

**Comment by DrupaListo-com** [comment]
my 2 cents:
+1 on "the header warning seems to be a false positive" - I think the self test code has a bug. While the hook is hooked ok.

as for the recaptcha V2 vs V3 - I'd suggest to add that notice to the README/module config page - at least for now. That will save countless hours to module users.

**Comment by nenes25** [comment]
The readme file has been updated,
I'll add the information in the module too
