### ISSUE TITLE
Javascript in footer rather than header

### ISSUE THREAD

**Issue by jacobmasters** [nenes25/eicaptcha#107]
Prestashop 1.7.1.1

 0.4.17

Custom Theme

On my theme jquery is loaded in the footer, so the plugin throws 
 Uncaught ReferenceError: $ is not defined
is there a way to load it on the footer rather than header to fix this issue?

**Comment by nenes25** [comment]
Hi,
Please use v 2.0.4 for prestashop 1.7 ;-)
https://github.com/nenes25/eicaptcha/releases/tag/2.0.4

Regards,
