### ISSUE TITLE
captcha appears on instant checkout page

### ISSUE THREAD

**Issue by ross235** [nenes25/eicaptcha#108]
** Prestashop Version **
1.6.1.1
** Eicaptcha version **
0.4.17
** Do you use a specific theme **
No
**Describe the bug**
After updating to version 0.4.17 the captcha still appears on instant checkout page. This means the customer can proceed to next stage without completing the captcha. Is it possible to remove the captcha from the instant checkout page as I fear this causes confusion as it does not need to be completed anyway it seems? Many thanks.

**Comment by JaykubCZ** [comment]
yes, this would help me too, but i have the same problem on 1.7.6.7 version and THE CHECKOUT checkout

**Comment by JaykubCZ** [comment]
is this project dead?

**Comment by eramirezprotec** [comment]
Solution [here](https://github.com/nenes25/eicaptcha/issues/124#issuecomment-710041812).
