### ISSUE TITLE
Captcha appears on instant checkout page

### ISSUE THREAD

**Issue by goncalosribeiro** [nenes25/eicaptcha#109]
** Prestashop Version **
1.7.5.0

** Eicaptcha version **
2.0.4

** Do you use a specific theme **
Alysum

**Describe the bug**
The captcha appears on instant checkout page and is possible to movo forward on the check out process without checking the captcha box.

**Comment by nenes25** [comment]
Hi @gonalo123 ,
Could you please provide screenshots ?
Regards,

**Comment by gonalo123** [comment]
Attached.
![screencapture](https://user-images.githubusercontent.com/32962095/57783507-24b7d200-7726-11e9-95d1-5566ed7f20f7.png)

**Comment by silviots** [comment]
I have the same problem

**Comment by JaykubCZ** [comment]
I have the same problem. Can you solve that please?

**Comment by JaykubCZ** [comment]
is this project dead?

**Comment by nenes25** [comment]
Hi,

Nope the project is not dead, but i'm the only one working on it during my free time.
Since a couple of months i have no time to check unfortunately, and this project is not in my top priorities.
But as it's an open source project every one is welcome to contribute.

Regards,

**Comment by JaykubCZ** [comment]
I could try. Would it help to move it to another hook? Or tell me how to solve that, i will try and let youbknow.

**Comment by eramirezprotec** [comment]
Solution [here](https://github.com/nenes25/eicaptcha/issues/124#issuecomment-710041812).

**Comment by nenes25** [comment]
Hi all,

Sorry for the delay but this is finally fixed in new release 2.0.6
Thanks @eramirezprotec for remaining me about that recently.

Regards,
