### ISSUE TITLE
bug in shopping cart

### ISSUE THREAD

**Issue by Roman-kra** [nenes25/eicaptcha#110]
** Prestashop Version **
1.6.1.4

** Eicaptcha version **
Eicaptcha version 0.4.17

**Describe the bug**
in the shopping cart, Captcha is turned off and is not showing, but if an order is sent, an "incorrect response to CAPTCHA challenge."

How to fix?

**Comment by Rissinko** [comment]
Hello i have same issue with one page checkout. Captcha is not showing but it looks like it is still sending the request to confirm that iam not robot. like sending request without checked checkbox.
