### ISSUE TITLE
Error installation on Prestashop 1.7.5.1

### ISSUE THREAD

**Issue by Tiranodonte** [nenes25/eicaptcha#115]
** Prestashop Version **
1.7.5.1

** Eicaptcha version **
0.4.17

** Do you use a specific theme **
Classic theme

**Describe the bug**
The installation doesn´t end, and appears an alert with the follow message: "Upps!.. The upload has failed! What happened? An error occurred while installing the eicaptcha module. The module version is not compatible with your version of Prestashop. Try again"

**Screenshots**
![Screenshot_2019-07-15 Gestor de módulos • Menuda Percha](https://user-images.githubusercontent.com/52918495/61214290-d0ba7100-a707-11e9-9dd4-4b90503ec6a6.png)

Javier Suárez
Regards.

**Comment by nenes25** [comment]
Hi,
It's not a bug you try to install the version for ps < 1.7
Please use this release instead : https://github.com/nenes25/eicaptcha/releases/tag/2.0.4
Regards,

**Comment by Tiranodonte** [comment]
Hi,
The version 2.0.4 has been installed sucesfully, but it returns the follow message in the contact form after check and submit:
"Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /usr/home/menudapercha.com/web/modules/eicaptcha/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php on line 68 Warning: file_get_contents(https://www.google.com/recaptcha/api/siteverify): failed to open stream: no suitable wrapper could be found in /usr/home/menudapercha.com/web/modules/eicaptcha/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php on line 68.
![Screenshot_2019-07-15 Contacte con nosotros](https://user-images.githubusercontent.com/52918495/61225790-94940a00-a721-11e9-9788-7955332d0290.png)

Thank you very much for your answer.
Regards

**Comment by nenes25** [comment]
Hi,
Unfortunately as the error claims, your issue is related to your server configuration.
You have to change your php configuration "allow_url_fopen" to 1.
If you don't know how to do it,you'll have to check with your hosting provider.

Regards,
