### ISSUE TITLE
Problème avec le module eicaptcha v 2.0.5

### ISSUE THREAD

**Issue by cycyrielle** [nenes25/eicaptcha#118]
** Prestashop Version **
Your prestashop version 1.7.6

** Eicaptcha version **
Eicaptcha version 2.0.5

** Do you use a specific theme **
Are you using a specific theme, if yes please tell which
ZoneTheme
**Describe the bug**
L'installation du module se passe très bien puis quand je vérifie si le module est bien installé, j'ai toujours cette erreur:
contactform.php override does not exist
j'ai déjà essayé des issues mises sur le site comme de retirer le class_index.php ou le fichier contactform.php dans override/modules/contactform/contactform.php mais sans résultats
**Screenshots**
![image](https://user-images.githubusercontent.com/53265589/62854348-61787280-bcef-11e9-94db-4b607ebe26db.png)

**Additional context**

**Comment by nenes25** [comment]
Bonjour,
Est-ce que le module fonctionne correctement ?
Cette erreur est un faux positif.
Cordialement,

**Comment by cycyrielle** [comment]
Bonjour, en fait, j'ai tout désinstallé, vidé le cache manuellement mais l'entièreté des fichiers (par précaution je ne vidais que le fichier smarty) et ça a fonctionné pour moi. 
Merci pour ce super module, 
Cordialement,
