### ISSUE TITLE
Captcha not showing on contact form

### ISSUE THREAD

**Issue by HMD-CR** [nenes25/eicaptcha#119]
** Prestashop Version **
Your prestashop version 1.6.1.11

** Eicaptcha version **
Eicaptcha version 0.4.17

** Do you use a specific theme **
Are you using a specific theme, if yes please tell which  Theme 1293

**Describe the bug**

All works on account creation but if I enable on the contact form we get no captcha box displayed...... and then no forms send as captch not completed..... I have also tried on Presta Version 1.6.1.23 with the. same theme with same results but changing theme all works fine so it does seem a conflict with somethingin the theme.

Any suggestions appreciated

**Screenshots**
![Screenshot 2019-08-16 at 17 35 22](https://user-images.githubusercontent.com/50070361/63183177-48075b80-c04c-11e9-944a-7d664e77a8d5.png)
![Screenshot 2019-08-16 at 17 36 19](https://user-images.githubusercontent.com/50070361/63183211-640afd00-c04c-11e9-99bf-42dd9d2efff9.png)

**Additional context**

**Comment by nenes25** [comment]
Hi,

Could you please give me an url to check ?

Regards,

**Comment by HMD-CR** [comment]
Hi 

Www.rapideyewear.co.uk/contact-us

**Comment by Juslesiasru** [comment]
Hi,

Same problem but with this error in console : reCAPTCHA couldn't find user-provided function: onloadCallback.

<div> appears but nothing to show.

Ideas ?
Regards.

**Comment by HMD-CR** [comment]
Hi Herve 

Any updates on this?  We have had to turn the capture off on the contact page now they are getting around 3-400 spam mails per day!!


Many thanks

Clive Riches







HYPERMEDIA DESIGN
Direct: +44 7870 156769    

Main Office: +44 1256 398188   Skype: cliveriches
http://www.hypermediadesign.co.uk <http://www.hypermediadesign.co.uk/>

Please be advised, the information contained herein is confidential and intended only for use by the individual stated above. 
If you are not the named recipient, you are hereby notified that any disclosure, distribution, dissemination or copying of this content is prohibited and should be deleted.
Hypermedia Design accepts no responsibility in the event that the onward transmission, opening or use of this message and/or any
included attachments adversely affects the recipient's systems or data. It is the recipient's responsibility 
to carry out any virus checks that the recipient considers appropriate.

**Comment by Juslesiasru** [comment]
Hello @HMD-CR ,

I solved it by replacing 

```
//Recaptcha CallBack Function
function onloadCallback() {grecaptcha.render("captcha-box", {"theme" : "'.$this->themes[Configuration::get('CAPTCHA_THEME')].'", "sitekey" : "'.Configuration::get('CAPTCHA_PUBLIC_KEY').'"});};
```

Instead of 
```
//Recaptcha CallBack Function
var onloadCallback = function() {grecaptcha.render("captcha-box", {"theme" : "'.$this->themes[Configuration::get('CAPTCHA_THEME')].'", "sitekey" : "'.Configuration::get('CAPTCHA_PUBLIC_KEY').'"});};`
```

Tell me.

**Comment by nenes25** [comment]
Hi all,

Thanks for the feedback, please let me know if it also solve your issue ;)
I've not a lot of time to check sorry for it

Regards,

**Comment by luciabriano** [comment]
Hola, yo tengo el mismo problema, en la pagina de creación de cuenta se puede visualizar, pero en la pagina de contacto no.

**Comment by Rikplays** [comment]
@HMD-CR
Hello. How did you manage it? I see it already works on your site. I have the same problem.

https://www.loredan.sk/sk/kontaktujte-nas

**Comment by HMD-CR** [comment]
Hi

We ended up hardcoding the captcha to the pages that we needed it on (contactform.tpl & authentication.tpl) 

Here is what we added

<script src='https://www.google.com/recaptcha/api.js'></script>
<div class="g-recaptcha" data-sitekey=“xxxx-your api key-xxx-xxxxx-xxxxx-xxxxxxx"></div>


Many thanks

Clive Riches







HYPERMEDIA DESIGN
Direct: +44 7870 156769    

Main Office: +44 1256 398188   Skype: cliveriches
http://www.hypermediadesign.co.uk <http://www.hypermediadesign.co.uk/>

Please be advised, the information contained herein is confidential and intended only for use by the individual stated above. 
If you are not the named recipient, you are hereby notified that any disclosure, distribution, dissemination or copying of this content is prohibited and should be deleted.
Hypermedia Design accepts no responsibility in the event that the onward transmission, opening or use of this message and/or any
included attachments adversely affects the recipient's systems or data. It is the recipient's responsibility 
to carry out any virus checks that the recipient considers appropriate.

**Comment by Rikplays** [comment]
@HMD-CR  so you put it there firmly and not using eicaptcha?

**Comment by HMD-CR** [comment]
Yes hard coded in the template file and stopped eicatcha

**Comment by Rikplays** [comment]
@HMD-CR  Hello. and just put there just hentak the script ?? no need to put both codes there? i privat i public ?? why then are both required in eicaptcha and other applications, if that's enough?

**Comment by Rikplays** [comment]
@HMD-CR  I would like to ask you for help with this, in which files (paths / files) to put it and where in the code? to which line or between which lines ???

**Comment by HMD-CR** [comment]
Which version of prestashop  are you using?

**Comment by Rikplays** [comment]
** Prestashop Version **
Verzia PrestaShopu: 1.7.2.5

** Eicaptcha version **
0.4.17

https://www.loredan.sk/sk/kontaktujte-nas
https://www.loredan.sk/sk/prihlasit-sa?create_account=1

Screenshots
http://prntscr.com/oxm4oe
http://prntscr.com/oxm4td
http://prntscr.com/oxm589
http://prntscr.com/oxm5h0

**Comment by Juslesiasru** [comment]
If you don't want to be in truble, just buy :

https://addons.prestashop.com/fr/securite-access/40268-invisible-google-re-captcha-v3-block-spam-customer.html

**Comment by Rikplays** [comment]
@Juslesiasru no thanks.. 30€ is more...

**Comment by HMD-CR** [comment]
Hi

The site we patched was Prestashop V1.6.1.24, I think it may be different in V1.7.x.  I hope this helps.

In contact-form.tpl 

We added at line 131 after 
129        <input type="text" name="url" value="" class="hidden" />
130        <input type="hidden" name="contactKey" value="{$contactKey}" /> 
131        <script src='https://www.google.com/recaptcha/api.js'></script>
132       <div class="g-recaptcha" data-sitekey=“xxxx-xxxx YOUR API KEY -xxxxx-xxxxxx"></div>   


In authentication.tpl

We added at line 649 after 

639             			<div class="account_creation dni">
640				<h3 class="page-subheading">{l s='Tax identification'}</h3>
641				<p class="required form-group">
642					<label for="dni">{l s='Identification number'} <sup>*</sup></label>
643					<input type="text" class="form-control" name="dni" id="dni" value="{if isset($smarty.post.dni)}{$smarty.post.dni}{/if}" />
644					<span class="form_info">{l s='DNI / NIF / NIE'}</span>
645				</p>
646			</div>
647		{/if}
648		
649         <script src='https://www.google.com/recaptcha/api.js'></script>
650        <div class="g-recaptcha" data-sitekey=“xxxx-xxxx YOUR API KEY -xxxxx-xxxxxx"></div>   
Many thanks

Clive Riches







HYPERMEDIA DESIGN
Direct: +44 7870 156769    

Main Office: +44 1256 398188   Skype: cliveriches
http://www.hypermediadesign.co.uk <http://www.hypermediadesign.co.uk/>

Please be advised, the information contained herein is confidential and intended only for use by the individual stated above. 
If you are not the named recipient, you are hereby notified that any disclosure, distribution, dissemination or copying of this content is prohibited and should be deleted.
Hypermedia Design accepts no responsibility in the event that the onward transmission, opening or use of this message and/or any
included attachments adversely affects the recipient's systems or data. It is the recipient's responsibility 
to carry out any virus checks that the recipient considers appropriate.

**Comment by Rikplays** [comment]
@HMD-CR   
Hello. Thank you, but I have trouble finding the right file contact-form.tpl. my FTP listing at / web / modules / contactform: http://prntscr.com/p0l3hn

none of your listed lines so I can not find. I have less there (107 only)
https://pastebin.com/yYQ2JRWS

**Comment by Rikplays** [comment]
I found only here: but apparently that is not it. because nothing I write there is showing up

http://prntscr.com/p0l4fh

**Comment by Rikplays** [comment]
I tried contact form to turn it off or it will be unavailable .. but no change .. I don't understand ..
http://prntscr.com/p0l5hi

**Comment by HMD-CR** [comment]
I have not used V1.7.x very much but from memory the contactform.tpl file you need should be found at 

/themes/yourthemename/modules/contactform/views/templates/widget/contactform.tpl. 

I do not know where to find the authentication.tpl or equivalent sorry


Many thanks

Clive Riches







HYPERMEDIA DESIGN
Direct: +44 7870 156769    

Main Office: +44 1256 398188   Skype: cliveriches
http://www.hypermediadesign.co.uk <http://www.hypermediadesign.co.uk/>

Please be advised, the information contained herein is confidential and intended only for use by the individual stated above. 
If you are not the named recipient, you are hereby notified that any disclosure, distribution, dissemination or copying of this content is prohibited and should be deleted.
Hypermedia Design accepts no responsibility in the event that the onward transmission, opening or use of this message and/or any
included attachments adversely affects the recipient's systems or data. It is the recipient's responsibility 
to carry out any virus checks that the recipient considers appropriate.

**Comment by Rikplays** [comment]
@HMD-CR Ok.. its ok.. i find contactform in  me theme.. i write there: http://prntscr.com/p0mdtl   but not show captcha... WTF.. I don't understand this...  any idea?

**Comment by Rikplays** [comment]
oh.. i bad... not clear cache :D :D http://prntscr.com/p0mg9b   but error is there...

**Comment by HMD-CR** [comment]
Hi

I guess this is saying that your site api key is incorrect…. You need to enable the site URL in google recaptcha for this api key to work

Many thanks

Clive Riches







HYPERMEDIA DESIGN
Direct: +44 7870 156769    

Main Office: +44 1256 398188   Skype: cliveriches
http://www.hypermediadesign.co.uk <http://www.hypermediadesign.co.uk/>

Please be advised, the information contained herein is confidential and intended only for use by the individual stated above. 
If you are not the named recipient, you are hereby notified that any disclosure, distribution, dissemination or copying of this content is prohibited and should be deleted.
Hypermedia Design accepts no responsibility in the event that the onward transmission, opening or use of this message and/or any
included attachments adversely affects the recipient's systems or data. It is the recipient's responsibility 
to carry out any virus checks that the recipient considers appropriate.

**Comment by Rikplays** [comment]
@HMD-CR Hi my support :) I am very grateful for your support and advice. I have both keys generated:
Captcha public key (Site key): 6Ldd4LQUAAAAAMGbgMJmHAUDJXXXXXXXXXXXXXX
and
Captcha private key (Secret key): 6Ldd4LQUAAAAAArGOPZFOKcV_JR95XXXXXXXXXXXXXX
and in the script I entered the first / Captcha public key
as can be seen on the screens I sent above where the source code of the website and thus contactform.tpl

**Comment by HMD-CR** [comment]
Hi

Do you still have the eicaptcha installed?

In our site this module is still installed and configured with both keys but it is not enabled… I have no idea if this will make any difference


Many thanks

Clive Riches







HYPERMEDIA DESIGN
Direct: +44 7870 156769    

Main Office: +44 1256 398188   Skype: cliveriches
http://www.hypermediadesign.co.uk <http://www.hypermediadesign.co.uk/>

Please be advised, the information contained herein is confidential and intended only for use by the individual stated above. 
If you are not the named recipient, you are hereby notified that any disclosure, distribution, dissemination or copying of this content is prohibited and should be deleted.
Hypermedia Design accepts no responsibility in the event that the onward transmission, opening or use of this message and/or any
included attachments adversely affects the recipient's systems or data. It is the recipient's responsibility 
to carry out any virus checks that the recipient considers appropriate.

**Comment by Rikplays** [comment]
Yes. I still have installed it is disabled. http://prntscr.com/p0mxpr     is there anything else to be added? insert?

**Comment by HMD-CR** [comment]
We have done nothing else….. try regenerating a new site key at google and update the code accordingly the issue now is the communication to google recaptcha as the box is now showing

 
Many thanks

Clive Riches







HYPERMEDIA DESIGN
Direct: +44 7870 156769    

Main Office: +44 1256 398188   Skype: cliveriches
http://www.hypermediadesign.co.uk <http://www.hypermediadesign.co.uk/>

Please be advised, the information contained herein is confidential and intended only for use by the individual stated above. 
If you are not the named recipient, you are hereby notified that any disclosure, distribution, dissemination or copying of this content is prohibited and should be deleted.
Hypermedia Design accepts no responsibility in the event that the onward transmission, opening or use of this message and/or any
included attachments adversely affects the recipient's systems or data. It is the recipient's responsibility 
to carry out any virus checks that the recipient considers appropriate.
