### ISSUE TITLE
stf_secure_key is not defined

### ISSUE THREAD

**Issue by 7starsone** [nenes25/eicaptcha#12]
Hello,
0.4.10 version

problem with js with the sendtoafriend module

**stf_secure_key is not defined** on console
when you click the send button, so it doesn't send the message

thank you

**Comment by nenes25** [comment]
Hello,

Have you tried with a previous version ?
Which version of prestashop are you using ?

This functionnality is droped on prestashop 1.7 version.

Regards,
Hervé

**Comment by 7starsone** [comment]
1.6.9 and 1.6.14 both... it does the same

**Uncaught ReferenceError: stf_secure_key is not defined**

**Comment by 7starsone** [comment]
you forgot this into sendtoafriend-extra.tpl at the end of **.../themes/yourtheme/modules/sendtoafriend**

`{addJsDef stf_secure_key=$stf_secure_key}
{addJsDefL name=stf_msg_success}{l s='Your e-mail has been sent successfully' mod='sendtoafriend' js=1}{/addJsDefL}
{addJsDefL name=stf_msg_error}{l s='Your e-mail could not be sent. Please check the e-mail address and try again.' mod='sendtoafriend' js=1}{/addJsDefL}
{addJsDefL name=stf_msg_title}{l s='Send to a friend' mod='sendtoafriend' js=1}{/addJsDefL}
{addJsDefL name=stf_msg_required}{l s='You did not fill required fields' mod='sendtoafriend' js=1}{/addJsDefL}
`

**Comment by nenes25** [comment]
Hello,

Great thanks for your feeback , could you please do a pull request ?

**Comment by yosoychicho** [comment]
helo ¿is this fixed?, i am with the same problem.
