### ISSUE TITLE
Chinese bots and Russian bots pass the captcha

### ISSUE THREAD

**Issue by GaetanBrunin** [nenes25/eicaptcha#125]
I installed the captcha module in my client's store because it receives 400 spam messages a day.
But they continue to pass the captcha and send a message through the contact form.

![image](https://user-images.githubusercontent.com/43266465/65018180-c21b5080-d928-11e9-9aa3-d3540a453d71.png)
![image](https://user-images.githubusercontent.com/43266465/65018202-d4958a00-d928-11e9-96c6-62003c3c8bf8.png)

How can i fix it ?

Regards

**Comment by nenes25** [comment]
Hi,

Your issue description is incomplete : 
Please answer the requested information when submitting a bug : 

**Prestashop Version**
Your prestashop version

**Eicaptcha version**
Eicaptcha version

**Do you use a specific theme**
Are you using a specific theme, if yes please tell which

Regards,

**Comment by GaetanBrunin** [comment]
Prestashop Version
1.6.0.8
Eicaptcha version
v.0.4.15
Do you use a specific theme
default-bootstrap version 1.0

**Comment by guidobuldrighini** [comment]
Hi, same for me.
Prestashop Version:
1.6.1.24
Eicaptcha version:
v.0.4.17
Do you use a specific theme?
default-bootstrap

**Comment by f1sz** [comment]
Same issue for me. China spam pass through Eicaptcha.

Prestashop version: 1.6.1.19
EiCaptcha ver: v0.4.17
default-bootstrap theme

**Comment by GaetanBrunin** [comment]
Just modify your contact page link, and they stop spamming.
