### ISSUE TITLE
Prestashop 1.7.6.1

### ISSUE THREAD

**Issue by chakiboss** [nenes25/eicaptcha#126]
Thankyou for your Work
i wanna just to tell you that doesn't work with 1.7.6.1 don't know why i will make tests & give you back

thanks

**Comment by nenes25** [comment]
Hi,

Thanks for the feedback.

I've already had such feedbacks, but on my demo website everything seems to works well.
cf. https://web.h-hennes.fr/dev/prestashop/prestashop_1-7-6-1/en/contact-us

Regards,

**Comment by chakiboss** [comment]
I think because you use the default template i use another template

**Comment by nenes25** [comment]
It may effectively be related what's the error ?

**Comment by chakiboss** [comment]
can't install it it's not for your prestashop version
and i tried the  (AM) eicaptcha v1.0 it's installed well but don't work with Recaptcha 3 but ony with v2
but it's bypassed in signup 
PS: My Prestashop is only in french version i deleted all english mods

**Comment by nenes25** [comment]
For ps 1.7 please try the release 2.x ;)
https://github.com/nenes25/eicaptcha/releases/tag/2.0.4

**Comment by chakiboss** [comment]
That Work!!!!!!!!!!! thankyou! Arigato Gosaimasu!!!! :)

**Comment by nenes25** [comment]
Nice if everything works :D
