### ISSUE TITLE
I could not install on ps 1.7.6.1

### ISSUE THREAD

**Issue by Patricio1HT** [nenes25/eicaptcha#130]
**Prestashop Version**  
1.7.6.1

**Eicaptcha version**  
V 0.4.17

**Do you use a specific theme**  
Default theme

**Describe the bug**  
I could not install the module in version 1.7.6.1
I receive the error:
"An error occurred installing the eicaptcha module. The module version is not compatible with your version of PrestaShop."

**Comment by nenes25** [comment]
Hi,
Duplicate of #126 
Please install the good version

Regards,
