### ISSUE TITLE
Contactform is NOT working

### ISSUE THREAD

**Issue by tbores** [nenes25/eicaptcha#131]
**Prestashop Version**  
1.7.6.1

**Eicaptcha version**  
![image](https://user-images.githubusercontent.com/4364483/69797715-77437200-11d0-11ea-9d00-f9be3844785c.png)

**Do you use a specific theme**  
No the default one

**Describe the bug**  
The AddIn is working for the AccountCreation form
The AddIn is NOT working for the Contact form. The send button cannot be clicked.

**Screenshots**  
![image](https://user-images.githubusercontent.com/4364483/69797568-377c8a80-11d0-11ea-8fb8-e9a611bb2417.png)

**Additional context**  
![image](https://user-images.githubusercontent.com/4364483/69797643-5418c280-11d0-11ea-9a8e-55597bc4c6f1.png)

**Comment by tbores** [comment]
Hi, you can close this issue, this is actually a problem with the RGPD module that is not shown correctly in Firefox.

**Comment by tbores** [comment]
Link for follow-up: https://github.com/PrestaShop/psgdpr/issues/70

**Comment by nenes25** [comment]
Thanks for the information :)
Regards,
