### ISSUE TITLE
Does not work on account creation page

### ISSUE THREAD

**Issue by sardin3s** [nenes25/eicaptcha#132]
**Prestashop Version**  
1.7.6.1

**Eicaptcha version**  
2.0.4

**Do you use a specific theme**  
Yes, sp_autostore Version 1.6.0

**Describe the bug**  
Captcha works fine on the contact page but does not appear on the registration page. However if selecting the default theme works fine.

**Comment by nenes25** [comment]
Hi,

The module is hooked on displayCustomerAccountForm hook to display the captcha on register form.
This hook is well present on default theme as you can see here https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/customer/_partials/customer-form.tpl#L38
Please check if it is also the case in your theme.

Regards,

**Comment by sardin3s** [comment]
Thanks for the help, solved my problem :)

I added the code `{$ hook_create_account_form nofilter}` to my theme file `customer-form.tpl`
