### ISSUE TITLE
Cannot install ZIP

### ISSUE THREAD

**Issue by franciscogimeno2000** [nenes25/eicaptcha#133]
**Prestashop Version**  
1.7.6.0

**Eicaptcha version**  
0.4.17

**Do you use a specific theme**  
classic Versión 1.0.0

**Describe the bug**  
Cannot install ZIP

ERROR:
An error occurred installing the eicaptcha module. The module version is not compatible with your version of PrestaShop.

**Comment by nenes25** [comment]
Hi,
Please check older issue before open new one
Duplicate of #126 / Duplicate of #130

Regards,

**Comment by franciscogimeno2000** [comment]
Thank you and sorry I had not seen it.
