### ISSUE TITLE
User register JS error

### ISSUE THREAD

**Issue by soulraven** [nenes25/eicaptcha#135]
**Prestashop Version**  
1.7.5.2

**Eicaptcha version**  
v2.0.4

**Do you use a specific theme**  
Techone

**Describe the bug**  
On user register page i get this error:
```
Uncaught Error: reCAPTCHA has already been rendered in this element
    at Object.rm [as render] (VM23625 recaptcha__ro.js:501)
    at onloadCallback (autentificare?create_account=1:167)
    at $7 (VM23625 recaptcha__ro.js:499)
    at VM23625 recaptcha__ro.js:506
    at Jo (VM23625 recaptcha__ro.js:510)
    at zW (VM23625 recaptcha__ro.js:506)
    at VM23625 recaptcha__ro.js:512
    at VM23625 recaptcha__ro.js:532
```

**Screenshots**  

**Additional context**

**Comment by soulraven** [comment]
check also # is a different error, on different view

**Comment by aln-1** [comment]
I vote for this!! Same JS error on the registration form.

**Comment by aln-1** [comment]
fixed in :
https://github.com/nenes25/eicaptcha/pull/153
