### ISSUE TITLE
PHPunit

### ISSUE THREAD

**Issue by HartLarsson** [nenes25/eicaptcha#137]
**Is your feature request related to a problem? Please describe.**
PHPunit create avulnerabilty as explained here: https://build.prestashop.com/news/critical-security-vulnerability-in-prestashop-modules/

**Describe the solution you'd like**
i found a phpunit.xml.dist inside the downloadable version 4.x.
Is necessary the presence of phpunit file?

thanks

**Comment by nenes25** [comment]
Hi @HartLarsson ,
Thanks for your feedback, can you point me out which branch or release is impacted by this phpunit.xml.dist.file ?
I have a quick look on the release files and i was not able to find this file.

Regards,

**Comment by HartLarsson** [comment]
the latest version contains a folder "/Vendor" that i think is not needed in the distribution version and contains the phpunit xml file:

![image](https://user-images.githubusercontent.com/16102074/72084366-a2f36500-3303-11ea-8ac8-7a51132042ae.png)

**Comment by nenes25** [comment]
Thanks for your analyze.
In fact the vendor directory is needed by the module, as it uses the official google php recaptcha library to deal with captcha validation.
The file you shows is packaged with the google library and fortunately does not provide any risk as it is a simple xml file :)
So we can safely close this issue.
Thanks again for the feedback,
Regards,
