### ISSUE TITLE
Error "Overrides are disabled on your website"

### ISSUE THREAD

**Issue by BillyWilly08** [nenes25/eicaptcha#138]
**Prestashop Version**  
1.7.5.1

**Eicaptcha version**  
2.0.4

**Do you use a specific theme**  
Theme name AngarTheme

**Describe the bug**  
"Overrides are disabled on your website"

**Screenshots**  
![image](https://user-images.githubusercontent.com/59875913/72352196-75832e80-36ea-11ea-881d-1da9cfc905f3.png)
![Overrides are disabled on your website](https://user-images.githubusercontent.com/59875913/72352488-035f1980-36eb-11ea-9c2a-b5d677e18a64.png)

**Additional context**

**Comment by BillyWilly08** [comment]
Hi

May you please advice

**Comment by nenes25** [comment]
Hi,

Your error is not related with the module but with your shop configuration.
I don't know why you have disabled the override functionality but it is required for this module to works.
You can enabled it again in page "advanced parameters / performances"
![image](https://user-images.githubusercontent.com/7163132/72433519-c6059500-3799-11ea-8a00-9463a10a61e6.png)
Regards,

**Comment by BillyWilly08** [comment]
> Hi,
> 
> Your error is not related with the module but with your shop configuration.
> I don't know why you have disabled the override functionality but it is required for this module to works.
> You can enabled it again in page "advanced parameters / performances"
> ![image](https://user-images.githubusercontent.com/7163132/72433519-c6059500-3799-11ea-8a00-9463a10a61e6.png)
> Regards,

Thank you very. It worked.

I am now only having a problem on the Front Office it's showing the attached screenshot:

"ERROR for site owner: Invalid key type"

![image](https://user-images.githubusercontent.com/59875913/72434714-fb63b000-37a4-11ea-9bd5-9c2401ea291e.png)

**Comment by nenes25** [comment]
Hi,

As the image shows,the key is not valid.
So i guess you use a recaptcha V3 api Key, and the module need a V2 one ;)

Regards,

**Comment by nenes25** [comment]
No feedbacks, issue closed

**Comment by badchy** [comment]
thanks. V2 api :)

Excelent work
