### ISSUE TITLE
Error "500" in Modules and Services after install module

### ISSUE THREAD

**Issue by samsonlife** [nenes25/eicaptcha#139]
**Prestashop Version**  
_1.6.1.23_

**Eicaptcha version**  
_0.4.17_

**Do you use a specific theme**  
_default-bootstrap version 1.0_

**Describe the bug**  
_"Error 500 server error" on Modules and services_ 

**Screenshots**  
http://www.sklepsaturn.pl/uploads/error_captcha_modul.jpg

**Additional context**  
_After installing the module, it is not possible to enter the tab in PrestaShop "Modules and Services" in the administration panel (see screenshot). Other tabs works without any problem_ 

**_500 Server Error
Oops, something went wrong.
Try to refresh this page or feel free to contact us if the problem persists._**

**Comment by nenes25** [comment]
Hi,
Could you please enable the debug mode in order to give me a detailed error.
Unfortunately with this description i can't understand what's going wrong
Regards,

**Comment by nenes25** [comment]
No feebacks, issue closed
