### ISSUE TITLE
Code works only with php >=5.5, lower versions produce error

### ISSUE THREAD

**Issue by Marghis** [nenes25/eicaptcha#14]
Hello,
Since introduction of function langSettings in eicaptcha.php this module can not be installed on PrestaShop running on PHP versions lower than 5.5.
This is because of the line
`254        if (empty(Configuration::get('CAPTCHA_FORCE_LANG'))) {`.
It passes a function as a parameter to `empty`, but prior to PHP v5.5 `empty` can only accept variables as parameter. This causes error `Can't Use Function Return Value In Write Context` when trying to open modules list from PS BO (PS 1.6).

I believe changing the line to 
`254        if (!Configuration::get('CAPTCHA_FORCE_LANG')) {`
makes the module compatible with versions lower than 5.5 (tested with 5.4).

https://github.com/nenes25/eicaptcha/blob/c4d022bf1dca9a2e82721b430c034cf1d51d9887/eicaptcha.php#L254

**Comment by nenes25** [comment]
Hello,

Thanks for your feedback, i have updated the code.
I'll make a new release asap.

Regards,

**Comment by nenes25** [comment]
Fixed in release 0.4.13
