### ISSUE TITLE
Error upload module

### ISSUE THREAD

**Issue by ManuelFPrado** [nenes25/eicaptcha#140]
I am trying to install the module in Prestashop and I can't get it to give the error I attached. My version of Prestashop is 1.7.6.3. Thanks!
![imagen](https://user-images.githubusercontent.com/42935406/73444858-c2f1d380-4359-11ea-91a8-20eea9494520.png)

**Comment by pipoe2h** [comment]
I'm having this exact issue too.

**Comment by pipoe2h** [comment]
Found the problem, for Prestashop 1.7 you must upload version 2.0.4 of the module.
https://github.com/nenes25/eicaptcha/releases/tag/2.0.4
