### ISSUE TITLE
Recaptcha n'apparaît pas sur le widget de contact intégré à d'autres pages

### ISSUE THREAD

**Issue by Maxtab** [nenes25/eicaptcha#141]
Bonjour et merci pour ce module bien conçu, et efficace, et surtout ce don à la communauté. ;)

**Prestashop Version**  
1.7.6.3

**Eicaptcha version**  
2.0.4

**Do you use a specific theme**  
breeze Version 2.0.3
Conçu par Anvanto Team

**Describe the bug**  
Le captcha fonctionne correctement et apparaît bien sur la page de contact, mais lorsque l'on affiche le widget de contact sur une page de contenu par exemple, le captcha lui ne s'affiche pas.

**Screenshots**  
Le captcha apparaît bien sur la page de contact classique: https://spaservice.fr/nous-contacter
Mais pas lorsque j'insère le widget de contact (qui fait appel au formulaire de contact classique, et qui donc devrait être appelé de la même façon) par exemple ici : https://spaservice.fr/content/10-service-apres-vente-garantie-de-votre-spa-gonflable-ospazia (en cliquant en bas sur "PROBLEME TECHNIQUE] FUITE SUR LA STRUCTURE GONFLABLE" puis "LA FUITE SE SITUE SUR UNE SOUDURE, UNE JOINTURE".

**Comment by Maxtab** [comment]
EN version for other readers
Prestashop Version
1.7.6.3

Eicaptcha version
2.0.4

Do you use a specific theme
breeze Version 2.0.3
Designed by Anvanto Team

Describe the bug
The captcha works properly and appears well on the contact page, but when you display the contact widget on a content page for example, the captcha does not appear.

screenshots
The captcha appears well on the classic contact page: https://spaservice.fr/nous-contacter
But not when I insert the contact widget (which uses the classic contact form, and which therefore should be called the same way) for example here (by clicking below on "TECHNICAL PROBLEM] LEAK ON THE INFLATABLE STRUCTURE" then "THE LEAK IS ON A WELDING, A JOINT".

**Comment by gringo1er** [comment]
Bonjour!
Même constat sur la toute version 2.3.1, en captcha v2 ou v3. Sinon top pour l'inscription de nouveaux clients!

**Comment by Alex-Besnier** [comment]
> Bonjour et merci pour ce module bien conçu, et efficace, et surtout ce don à la communauté. ;)
> 
> **Prestashop Version** 1.7.6.3
> 
> **Eicaptcha version** 2.0.4
> 
> **Do you use a specific theme** breeze Version 2.0.3 Conçu par Anvanto Team
> 
> **Describe the bug** Le captcha fonctionne correctement et apparaît bien sur la page de contact, mais lorsque l'on affiche le widget de contact sur une page de contenu par exemple, le captcha lui ne s'affiche pas.
> 
> **Screenshots** Le captcha apparaît bien sur la page de contact classique: https://spaservice.fr/nous-contacter Mais pas lorsque j'insère le widget de contact (qui fait appel au formulaire de contact classique, et qui donc devrait être appelé de la même façon) par exemple ici : https://spaservice.fr/content/10-service-apres-vente-garantie-de-votre-spa-gonflable-ospazia (en cliquant en bas sur "PROBLEME TECHNIQUE] FUITE SUR LA STRUCTURE GONFLABLE" puis "LA FUITE SE SITUE SUR UNE SOUDURE, UNE JOINTURE".

Bonjour,

J'ai la même problématique et je vois sur le site donné en exemple que Maxtab semble avoir trouvé une solution car le captcha s'affiche bien sur ces formulaires.
Maxtab, si vous recevez mon message auriez vous une piste à nous partager ?
Merci.

**Comment by Alex-Besnier** [comment]
Je viens de trouver votre article lié à la nouvelle version 2.4.0 qui a répondu à mon problème.
https://www.h-hennes.fr/blog/2022/08/22/prestashop-ajouter-un-captcha-sur-les-formulaires-de-vos-modules/

Merci pour l'ajout de ces hooks fort pratiques.

Je donne le processus que j'ai utilisé dans mon cas :

Je me suis branché directement sur le fichier /modules/contactform/contactform.php 
Dans la fonction getWidgetVariables j'ai ajouté juste avant le return : 
 if ($eicaptcha = Module::getInstanceByName('eicaptcha')) {
            $this->contact['renderCaptcha'] = $eicaptcha->hookDisplayEicaptchaVerification(['module' => $this->name]);
        }

Puis dans le fichier contact-form.tpl de mon thème j'ai utilisé le code suivant pour l'afficher :  
{$contact.renderCaptcha nofilter}

**Comment by nenes25** [comment]
Bonjour @Alex-Besnier ,
Merci pour le partage d'information :smile: !

**Comment by nenes25** [comment]
Ce problème sera sans doute fixé en natif dans la version à venir 2.4.5 
Je ferme ce ticket et le suivi sera dans celui-ci #221 comme c'est l'option que j'ai reprise.
