### ISSUE TITLE
Module Installation

### ISSUE THREAD

**Issue by vladisu** [nenes25/eicaptcha#143]
**Prestashop Version**  
1.6.1.5

**Eicaptcha version**  
0.4.17
**Do you use a specific theme**  
SNS Kanta Theme

**Describe the bug**  
During installation of the module (tired both auto and manual) received following errors: 

eicaptcha (parse error in /modules/eicaptcha/eicaptcha.php)
eicaptcha (class missing in /modules/eicaptcha/eicaptcha.php)

**Comment by nenes25** [comment]
Hi,
Did you download the module from the release page ?
https://github.com/nenes25/eicaptcha/releases/tag/0.4.17

Regards,

**Comment by vladisu** [comment]
Hi, yes I download that

**Comment by vladisu** [comment]
Now I'm getting this type of error...

**Comment by vladisu** [comment]
![image](https://user-images.githubusercontent.com/61218613/74895962-fb6f5500-53cd-11ea-9252-64cfa0ad8def.png)

Now I'm getting this type of error...

**Comment by nenes25** [comment]
Could you please check your php version ?
I'm not able to reproduce your erreur.
Moreover the relase have been downloaded hundred of times without this kind of error
So i guess it should be related with your server configuration

Regards,

**Comment by nenes25** [comment]
No feebacks, issue closed
