### ISSUE TITLE
ReCaptcha n'apparait pas sur le form. de contact / Erreurs dans BO

### ISSUE THREAD

**Issue by rtajmahal** [nenes25/eicaptcha#144]
**Prestashop Version**  
1.7.6.3

**Eicaptcha version**  
0.4.17

**Do you use a specific theme**  
Warehouse 4.3.2

**Describe the bug**  
ReCaptcha n'apparait pas sur le formulaire de contact et des messages d'erreurs sont apparus (Vérifier l'installation du module)  

Errors
the module is not compatible with your version
the module is not registered in hook contactFormAccess
the module is not registered in hook actionBeforeSubmitAccount

**Screenshots**  
![recaptcha](https://user-images.githubusercontent.com/2932178/75295716-a008f100-582b-11ea-9b13-23ad16dfc41d.JPG)

**Comment by nenes25** [comment]
Bonjour,
Merci d'installer la version 2.0 sur prestashop 1.7 https://github.com/nenes25/eicaptcha/releases/tag/2.0.4 
Ceci corrigera votre problème,
Cordialement,

**Comment by rtajmahal** [comment]
Bonjour,

Je viens d'installer la version 2.0.4, recaptcha semble fonctionner sur la page de contact mais au moment de la vérification de l'installation du module, j'ai une erreur (contacform.php override does not exists):

Errors
contacform.php override does not exists
Success
the module is compatible with your version
the module is well registered in hook header
the module is well registered in hook displayCustomerAccountForm
the module is well registered in hook actionContactFormSubmitCaptcha
the module is well registered in hook actionContactFormSubmitBefore
the module contacform is installed
Overrides are enabled on your website
AuthController.php override exists
Authcontroller override is present in class_index.php
Aditionnal informations
Prestashop version 1.7.6.3
Theme name warehouse
Php version 7.2.28

Merci

**Comment by nenes25** [comment]
Bonjour,
C'est un faux positif lié à une faute de frappe dans la vérif.
Ce sera corrigé dans la prochaine release mais le module est bien fonctionnel :)

Cordialement
