### ISSUE TITLE
Captcha error prestashop 1.7

### ISSUE THREAD

**Issue by alfonsolr09** [nenes25/eicaptcha#145]
**Prestashop Version**  
1.7.6.4

**Eicaptcha version**  
2.0.4

**Do you use a specific theme**  
Classic

**Describe the bug**  
Captcha works fine, but
At the end of an order when I must log in or ask as a guest, there is a captcha that does not work, if I do not fill it, let me go to the next step.

**Screenshots**  
https://prnt.sc/rklpba
https://prnt.sc/rklph2

**Additional context** 
is it possible to fix it?

**Comment by alfonsolr09** [comment]
Why you close it?? @nenes25

**Comment by nenes25** [comment]
This issue is inactive since more than a year and there is a new release since.
If this issue is still present with it , feel free to reopen.

Regards

**Comment by alfonsolr09** [comment]
the problem is idle because no one fixed it. I will try the new version and check if it has been fixed or not
