### ISSUE TITLE
I can't install the module

### ISSUE THREAD

**Issue by Maite1976** [nenes25/eicaptcha#147]
**Prestashop Version**  
1.7.6.1

**Eicaptcha version**  
V 0.4.17

I can't install the module, the error is "This file is not a valid ZIP format module."

**Comment by nenes25** [comment]
Hi,
Please download this release : https://github.com/nenes25/eicaptcha/releases/tag/2.0.4
Regards,

**Comment by Maite1976** [comment]
Thanks!!!
