### ISSUE TITLE
The module works fine in the contact form, but the customer account creation doesn't work after installation

### ISSUE THREAD

**Issue by oskr96** [nenes25/eicaptcha#148]
**Prestashop Version**  
1.7.6.4

**Eicaptcha version**  
0.4.17

**Do you use a specific theme**  
Yes, mediastack

**Describe the bug**  
I can install and make work the module in the contact form after edit the limit of the version in the eicaptcha.php file and add a div with the id 'captcha-box' to  contactform.tpl file of my template, but, after installation the customer account creation doesn't work, the captcha is correctly showed under the form but when i submit the page it's not redirected to index of the shop and the account is not created, only reload the form of creation.

**Screenshots**  

**Additional context**

**Comment by nenes25** [comment]
Hi,
you have installed the wrong version
Please download the one for ps 1.7+ here => https://github.com/nenes25/eicaptcha/releases/tag/2.0.4

Regards

**Comment by oskr96** [comment]
Yes, you have reason! :v Thank's for the help!

**Comment by nenes25** [comment]
You're welcome, so i close the issue :)
