### ISSUE TITLE
Error message when submitting: Please validate the captcha field before submitting your request

### ISSUE THREAD

**Issue by onfre** [nenes25/eicaptcha#149]
**Prestashop Version**  
1.7.6.2

**Eicaptcha version**  
2.0.4

**Do you use a specific theme**  
no
**Describe the bug**  
Error message when submitting: Please validate the captcha field before submitting your request.

**Screenshots**  
following message appears : Merci de valider le captcha

**Additional context**  
I already empty the cache
I already replaced the contactform.tpl file with the right one for my version 1.7.6.x from yours
I have red all the other tickets 59 and 85 but it still doesn't work.

Merci pour ce module quoi qu'il en soit ! Il fonctionne juste sur la création de compte à priori.

**Comment by LGx0** [comment]
Hello.

Prestashop version: 1.7.6.4
Eicaptcha version: 2.0.4

Error:Please validate the captcha field before submitting your request

Clear cache, but doesn't work. 

Please help me.

Thank you very much.

Best regards,

**Comment by onfre** [comment]
Still doesn't work for me. I will desinstall it.
