### ISSUE TITLE
v2.0.5 not released

### ISSUE THREAD

**Issue by keeper7** [nenes25/eicaptcha#150]
**Prestashop Version**  
1.7.x.x

**Eicaptcha version**  
2.0.5

**Do you use a specific theme**  
no

**Describe the bug**  
In release notes there is v 2.0.5 from 2019-04-23 but is not released.

**Comment by nenes25** [comment]
Hi,
Thanks for the feedback, i'm planning to work on this module this month
So the next version may be released ;)

**Comment by HartLarsson** [comment]
please fix the language detection is not working
