### ISSUE TITLE
[P1.6 - 0.50] Contact Form refresh on submit

### ISSUE THREAD

**Issue by dutom007** [nenes25/eicaptcha#152]
Bonjour j'ai installé le module 0.5 sur mon presta :
https://www.selleriedumeneur.fr/contactez-nous

A la soumission le formulaire n'est que rafraichi...
![image](https://user-images.githubusercontent.com/11500275/78234604-adbf2f80-74d7-11ea-95c7-6356c31b017b.png)

Je ne peux ajouter ajouter le module au hook "contactFormAccess" il ne fait pas partie de la liste
![image](https://user-images.githubusercontent.com/11500275/78234792-f2e36180-74d7-11ea-8f43-339c687c225a.png)

**Comment by nenes25** [comment]
Bonjour,

Cette version n'est pas encore finalisée.
Merci de télécharger la dernière version releasée depuis cette page : https://github.com/nenes25/eicaptcha/releases/tag/0.4.17

Cordialement,

**Comment by dutom007** [comment]
Bonjour Hervé,

J'avais le souci avec 0.4.17 c'est pour cela que j'ai tenté le 0.5

**Comment by nenes25** [comment]
Il n'est pas nécessaire d'ajouter manuellement les hooks tout est automatique.
Lors de l'installation du module les hooks non existants sont ajoutés automatiquement également.

Ce module a déjà quelques années et fonctionne relativement bien, par contre la version 7.3 de php n'étant pas officiellement supportée par prestashop 1.6 il n'a jamais été testé sur cette version.

Regardez éventuellement dans vos logs d'erreurs si vous trouvez quelque chose.

Cordialement,

**Comment by dutom007** [comment]
Hervé,

Je suis repassé en version 5.6 est effectivement la réinstallation du module à bien mis en place les hook est c'est fonctionnel. 

Je tente la mise à jour 1.6.24 pour assurer la validité 7.3 et tente à nouveau.

Je vous communiquerais le résultat

**Comment by nenes25** [comment]
Merci du retour, en attendant je ferme donc cette issue.
