### ISSUE TITLE
Add newsletter captcha

### ISSUE THREAD

**Issue by nik012003** [nenes25/eicaptcha#154]
**Is your feature request related to a problem? Please describe.**
I'm getting lots of spam account creations thru the newsletter registration form.

**Describe the solution you'd like**
Could we get a captcha to show up even on the newsletter subscribe from?

I'm running ps 1.7.6.4 by the way.

**Comment by nenes25** [comment]
Hi,
Thanks for the feedback.
Unfortunately this update is not planed as it add new problematic to solve,and i've already a lack of time to maintain this module.
I think that some paying modules do it on prestashop addons.

Regards,
