### ISSUE TITLE
Having issue with install package

### ISSUE THREAD

**Issue by rohithudda** [nenes25/eicaptcha#155]
**Prestashop Version**  
1.7.6.4

**Eicaptcha version**  
Latest

**Do you use a specific theme**  
Default

**Describe the bug**  
Unable to install

**Screenshots**  
![Screenshot_2020-04-19 Module manager • Your Shop](https://user-images.githubusercontent.com/9127744/79680766-f80f1300-8230-11ea-88d3-55aa1dc0d2bf.png)

**Comment by neich78** [comment]
Happens the same in 1.7.6.1 version. Thanks

**Comment by kcuk80** [comment]
Same on PrestaShop version: 1.7.2.5
