### ISSUE TITLE
Undefined variables when verifying

### ISSUE THREAD

**Issue by Pinou10001** [nenes25/eicaptcha#156]
**Prestashop Version**  
1.6.1.10

**Eicaptcha version**  
0.4.17

**Do you use a specific theme**  
Bootstrap default theme

**Describe the bug**  
When we want to verify if the module is well installed or not, there is undefined variables.

**Screenshots**  
https://prnt.sc/sjl9mr (When installation is good)

**Comment by nenes25** [comment]
Thanks for the provided fix :)
