### ISSUE TITLE
Captcha v2 not showing in contact form but does show in sign up form

### ISSUE THREAD

**Issue by dragon-sa** [nenes25/eicaptcha#159]
**Prestashop Version**  
Your prestashop version 1.7.6.5

**Eicaptcha version**  
Eicaptcha version 2.0.4

**Do you use a specific theme**  
Classic

**Describe the bug**  
Installed module eicaptcha 2.0.4 successfully, Configured it with my site and secret keys, turned it on for contact form and sign up, cleared my cache, check signup page captcha is visible and works, goto contact form and captcha is not there, but when I submit form it produces an error "Please validate the captcha field before submitting your request"

**Screenshots**  
![captcha-contactform](https://user-images.githubusercontent.com/67693709/86246119-a21ff980-bbe9-11ea-91b1-92dbfc6bb71a.png)

**Additional context**

**Comment by nenes25** [comment]
Hi,

Could you please me give an url to check ?

Regards,

**Comment by dragon-sa** [comment]
Hi
Thanks for getting back, https://cncbloke.com.au/shop

**Comment by nenes25** [comment]
Hi,
Weird i have an error in the console saying that the placeholder does not exists
![image](https://user-images.githubusercontent.com/7163132/86353497-9a069f00-bc67-11ea-9f3d-afdb59ced696.png)
Could you try to add the placeholder manually in the contact form ?
`<div id="captcha-box"></div>`

I am unable to reproduce the issue on my side with the same configuration.

**Comment by dragon-sa** [comment]
Ok I have added that to contactform.tpl, I can see the div tag when I inspect the code but not the captcha box.

here is the code
`{**
 * 2007-2019 PrestaShop and Contributors
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License 3.0 (AFL-3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to https://www.prestashop.com for more information.
 *
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2007-2019 PrestaShop SA and Contributors
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License 3.0 (AFL-3.0)
 * International Registered Trademark & Property of PrestaShop SA
 *}
<section class="contact-form">
  <form action="{$urls.pages.contact}" method="post" {if $contact.allow_file_upload}enctype="multipart/form-data"{/if}>

    {if $notifications}
      <div class="col-xs-12 alert {if $notifications.nw_error}alert-danger{else}alert-success{/if}">
        <ul>
          {foreach $notifications.messages as $notif}
            <li>{$notif}</li>
          {/foreach}
        </ul>
      </div>
    {/if}

    {if !$notifications || $notifications.nw_error}
      <section class="form-fields">

        <div class="form-group row">
          <div class="col-md-9 col-md-offset-3">
            <h3>{l s='Contact us' d='Shop.Theme.Global'}</h3>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-md-3 form-control-label">{l s='Subject' d='Shop.Forms.Labels'}</label>
          <div class="col-md-6">
            <select name="id_contact" class="form-control form-control-select">
              {foreach from=$contact.contacts item=contact_elt}
                <option value="{$contact_elt.id_contact}">{$contact_elt.name}</option>
              {/foreach}
            </select>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-md-3 form-control-label">{l s='Email address' d='Shop.Forms.Labels'}</label>
          <div class="col-md-6">
            <input
              class="form-control"
              name="from"
              type="email"
              value="{$contact.email}"
              placeholder="{l s='your@email.com' d='Shop.Forms.Help'}"
            >
          </div>
        </div>

        {if $contact.orders}
          <div class="form-group row">
            <label class="col-md-3 form-control-label">{l s='Order reference' d='Shop.Forms.Labels'}</label>
            <div class="col-md-6">
              <select name="id_order" class="form-control form-control-select">
                <option value="">{l s='Select reference' d='Shop.Forms.Help'}</option>
                {foreach from=$contact.orders item=order}
                  <option value="{$order.id_order}">{$order.reference}</option>
                {/foreach}
              </select>
            </div>
            <span class="col-md-3 form-control-comment">
              {l s='optional' d='Shop.Forms.Help'}
            </span>
          </div>
        {/if}

        {if $contact.allow_file_upload}
          <div class="form-group row">
            <label class="col-md-3 form-control-label">{l s='Attachment' d='Shop.Forms.Labels'}</label>
            <div class="col-md-6">
              <input type="file" name="fileUpload" class="filestyle" data-buttonText="{l s='Choose file' d='Shop.Theme.Actions'}">
            </div>
            <span class="col-md-3 form-control-comment">
              {l s='optional' d='Shop.Forms.Help'}
            </span>
          </div>
        {/if}

        <div class="form-group row">
          <label class="col-md-3 form-control-label">{l s='Message' d='Shop.Forms.Labels'}</label>
          <div class="col-md-9">
            <textarea
              class="form-control"
              name="message"
              placeholder="{l s='How can we help?' d='Shop.Forms.Help'}"
              rows="3"
            >{if $contact.message}{$contact.message}{/if}</textarea>
          </div>
        </div>

        {if isset($id_module)}
          <div class="form-group row">
            <div class="offset-md-3">
              {hook h='displayGDPRConsent' id_module=$id_module}
            </div>
          </div>
        {/if}

      </section>
		<div id="captcha-box"></div>
      <footer class="form-footer text-sm-right">
        <style>
          input[name=url] {
            display: none !important;
          }
        </style>
        <input type="text" name="url" value=""/>
        <input type="hidden" name="token" value="{$token}" />
        <input class="btn btn-primary" type="submit" name="submitMessage" value="{l s='Send' d='Shop.Theme.Actions'}">
      </footer>
    {/if}
  </form>
</section>
`

**Comment by nenes25** [comment]
Seems good but still not working.
I'll need to investigate more, for now i have no clue from where comes this issue

**Comment by dragon-sa** [comment]
Ok thanks, let me know if you need me to do anything else,

 it does work on the sign up page so it is strange its not working here

**Comment by TboneCoder** [comment]
I've been having the same problem on 1.7.6.5. Chased down a few dead ends within PrestaShop. Not sure if this helps but this is what I get on Chrome.

![screencap1](https://user-images.githubusercontent.com/62967181/87975034-e5021e00-ca7f-11ea-80a1-f0fe2b6e5816.png)

**Comment by dragon-sa** [comment]
This is what mine throws on page load
![captch-error-contact](https://user-images.githubusercontent.com/67693709/88003842-ef3a2000-cb44-11ea-9095-d6083a33728d.jpg)

**Comment by dragon-sa** [comment]
In the backend when I run the test for EI captch installed well I get the following error
contacform.php override does not exists
