### ISSUE TITLE
Getting erro in 1.7.6.5

### ISSUE THREAD

**Issue by pks891618** [nenes25/eicaptcha#160]
**Prestashop Version**  
1.7.6.5
**Eicaptcha version**  
2.0.4

**Do you use a specific theme**  
its default theme

**Describe the bug**  
Failed to load resource: the server responded with a status of 400 () contact-us:87
 Uncaught ReferenceError: Recaptcha is not defined

**Screenshots**  

http://i.imgur.com/o9Fx066.png

**Comment by pks891618** [comment]
http://i.imgur.com/WOQ7teV.png

another error on the same version

**Comment by cl-consulting** [comment]
I confirm that it's not compatible with Prestashop 1.7.6.7 : error  when downloading in Backoffice

**Comment by HartLarsson** [comment]
PS 1.7.6.7
Theme Warehouse
PHP: 7.2
Eicaptcha version: 2.0.4

All works.
