### ISSUE TITLE
eicaptcha-ajax.php is indexed

### ISSUE THREAD

**Issue by BoutiquesInternet** [nenes25/eicaptcha#161]
**Prestashop Version**  
1.7.6

**Eicaptcha version**  
0.4.17

**Describe the bug**  
The file eicaptcha-ajax.php is indexed by Google (Indexée malgré le blocage par le fichier robots.txt)

**Comment by nenes25** [comment]
Bonjour,

Désolé mais pour le coup cela n'a rien à voir avec le module.
Je ne pourrais malheureusement rien faire pour corriger cela.

Cordialement,

**Comment by matasskarzauskas** [comment]
Hi @BoutiquesInternet 
Check your shops robots.txt file, it is not possible for Google to index the file if it is blocked. Also, give it a day or two to completely reindex.

**Comment by BoutiquesInternet** [comment]
Hi,

Thanks for the replies. 
robots.txt prestashop file is generate automaticaly, all custom modification can be lost.
So it's a problem :/

It's not possible to add noindex for this file ?

**Comment by matasskarzauskas** [comment]
Well, the robots.txt doesn't regenerate if you dont tell Prestashop to, so you can do the changes and leave it something like so:

User-agent: Googlebot 
Disallow: /modules/eicaptcha/
