### ISSUE TITLE
V2.0.4 not detect PS language switching

### ISSUE THREAD

**Issue by HartLarsson** [nenes25/eicaptcha#162]
**Prestashop Version**  
1.7.6.7

**Eicaptcha version**  
Eicaptcha version 2.0.4

**Do you use a specific theme**  
Theme Warehouse

**Describe the bug**  
When, on multilanguage PS instalaltion, you switch language the captcha not detect the language and continue to ask information in the default PS language selected.
Even forcing in the configuration "it | en" not works.

**Screenshots**  

English site:
![image](https://user-images.githubusercontent.com/16102074/91454155-eabe0100-e880-11ea-8420-8991fc26790f.png)

Italian Site:
![image](https://user-images.githubusercontent.com/16102074/91454194-f7daf000-e880-11ea-927f-c7175429fe9b.png)

Also accessing the web site from USA the captcha language still in Italian (the default language of the site)

in eicaptcha.php the code:

```
			if ( ($this->context->controller instanceof ContactController && Configuration::get('CAPTCHA_ENABLE_CONTACT') == 1) ){
				$js .= '<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit&hl=' . Configuration::get('CAPTCHA_FORCE_LANG') . '" async defer></script>';
			}
```
works only if the CAPTCHA_FORCE_LANG variable is setup in the module.
Should be different:

if not specified CAPTCHA_FORCE_LANG get the language ISO Code ( https://developers.google.com/recaptcha/docs/language) of actual PS theme language using like {$lang_iso}

also in Customer account creation this part of code have a variable that is not assigned based on theme language switch:

`    <script src="https://www.google.com/recaptcha/api.js?hl={$captchaforcelang}" async defer></script>`

Could be nice to add an option in the plugin config to Follow the Prestashop language and not autodetect.

**Comment by metacreo** [comment]
https://github.com/nenes25/eicaptcha/pull/220

**Comment by metacreo** [comment]
can be closed. Thanks for all.
