### ISSUE TITLE
Problème lors de la validation de mon formulaire

### ISSUE THREAD

**Issue by LeoMonterrat** [nenes25/eicaptcha#169]
Bonjour,

Je rencontre un problème avec votre module Prestashop

J'arrive à l'intégrer, il est visible et bien placé.

Mais le problème arrive lorsque je clique sur ENVOYER : La page met beaucoup de temps à charger pour qu'au final: la validation a expiré....

Dans les logs du module:
j'ai " invalid-json" qui remonte.

Voici le contenu de mon eicaptcha-contact-form.js:
```
$(document).ready(function () {
    $('.form-fields').append('<div id="captcha-box"></div>');
});
```

Du coté google recaptcha, j'ai une pop up qui remonte communiquant:
Nous avons détecté que votre site ne vérifiait pas les solutions fournies aux tests reCAPTCHA. Vous devez les vérifier afin d'utiliser correctement la fonctionnalité reCAPTCHA sur votre site. 

Voici mes versions de boutique

Version de PrestaShop : 1.7.6.8
Thème actif : blck
Version de PHP : 7.0.33-0+deb9u10
Version de EiCaptcha : V2.0.6

En attente de votre retour
Cordialement

**Comment by nenes25** [comment]
Bonjour,

Est-ce possible d'avoir une url ?
Je pense que le problème doit etre lié au thème car le module fonctionne globalement bien sur les versions 1.7.6

Cordialement,

**Comment by LeoMonterrat** [comment]
Voici l'url : https://boutique.legoutdenice.fr/fr/nous-contacter

J'utilise le thème **blck Version 3.0.2**

**Comment by nenes25** [comment]
Bonjour,

J'ai effectivement testé votre boutique et j'ai bien le problème également.
Je pense que ce problème est lié à votre hébergement.
Est-ce que vous pouvez vous assurer que l'option https://www.php.net/manual/fr/filesystem.configuration.php#ini.allow-url-fopen est bien définie ?
Si ce n'est pas le cas la réponse ne peut pas être postée vers google pour soumettre le captcha.
Et c'est ce qui doit bloquer.

Cordialement,

**Comment by acabaud1** [comment]
Bonjour,

Je viens de rencontrer ce problème et après quelques recherches il provenait bien de `allow_url_fopen` qui n'était pas activé sur l'hébergement.

Il est possible de contourner le problème en utilisant cURL à la place, pour cela il faut modifier le fichier `eicaptcha.php` du module : 

`$captcha = new \ReCaptcha\ReCaptcha(Configuration::get('CAPTCHA_PRIVATE_KEY'));`
par
`$captcha = new \ReCaptcha\ReCaptcha(Configuration::get('CAPTCHA_PRIVATE_KEY'), new \ReCaptcha\RequestMethod\CurlPost());`

dans les méthodes `hookActionBeforeSubmitAccount` et `hookContactFormAccess`

Solution trouvée ici : https://stackoverflow.com/questions/30106668/nocaptcha-returning-error-invalid-json

**Comment by nenes25** [comment]
Bonjour @h3r0xfr 

Merci pour ce retour :)
Je vais voir si il est possible de conditionner l'utilisation de curl uniquement si allow_url_fopen n'est pas actif sur l'hébergement.
Cela fixera ce soucis qui semble assez rare ( premier retour sur ce points depuis pas mal d'années )

Cordialement,

**Comment by nenes25** [comment]
Fix
