### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by demmonin** [nenes25/eicaptcha#170]
**Prestashop Version**  
1.7.1.6

**Eicaptcha version**  
2.0.6

**Do you use a specific theme**  
default theme

**Describe the bug**  
1/1) FatalErrorException
Compile Error: require_once(): Failed opening required '/home/mocanail/public_html/modules/ps_featuredproducts/vendor/composer/autoload_real.php9y9�q���' (include_path='/home/mocanail/public_html/vendor/pear/pear_exception:/home/mocanail/public_html/vendor/pear/console_getopt:/home/mocanail/public_html/vendor/pear/pear-core-minimal/src:/home/mocanail/public_html/vendor/pear/archive_tar:.:/opt/alt/php72/usr/share/pear')
**Screenshots**  

**Additional context**  
and error 500 in frontend

![image](https://user-images.githubusercontent.com/76456390/102831344-51d06a00-43ca-11eb-934a-ac1fe99bcb1c.png)

**Comment by nenes25** [comment]
Hi,
Please read the installation instructions ;)
https://github.com/nenes25/eicaptcha#installation

Regards
