### ISSUE TITLE
Eicaptcha now doesn't work - Need composer version

### ISSUE THREAD

**Issue by Neldor89** [nenes25/eicaptcha#171]
**Prestashop Version**  
1.7.7.0

**Eicaptcha version**  
2.0.7

**Do you use a specific theme**  
Angar Theme

**Describe the bug**  
Now i install the new release 2.0.7 of the EiCaptcha, but it doesn't work, it takes me to a blank page. And in the module config page, appears this message (see screenshot). What i have to do?

**Screenshots**  
https://i.gyazo.com/b1046912ba4a161226a2bb8183fd39d3.png

**Comment by Stephane1874** [comment]
Hi @Neldor89,

I also tried this version 2.0.7, the "vendor" folder is missing, try adding the "vendor" folder from version 2.0.6.

https://github.com/nenes25/eicaptcha/releases/tag/2.0.6

For me it works locally, I haven't tried it on my store yet.

![Capture](https://user-images.githubusercontent.com/46202635/103155254-3389b600-479e-11eb-920d-4e74789ac19f.PNG)

**Comment by Neldor89** [comment]
Hi! Hope @nenes25 can confirm us if thats a bug or if it will work too with that change.

**Comment by nenes25** [comment]
Hello,
Sorry you are right my archive miss the vendor directory ...
I've uploaded a new archive file which should correct the issue @Stephane1874  @Neldor89 can you confirm that it's ok now ?

**Comment by Neldor89** [comment]
Yes! Now work completely fine (i tried it with and without checking the captcha and works fine). Merci beaucoup, @nenes25 !!

**Comment by nenes25** [comment]
Great thanks for the feedback :)
I close the issue

**Comment by Stephane1874** [comment]
Hello @nenes25,

The version 2.0.7 now works perfectly, the only problem is that it adds twice the block `<div id="captcha-box"></div>`, nothing too serious.

![Capture](https://user-images.githubusercontent.com/46202635/103274998-5ba62e80-49c3-11eb-9d14-120154deb6f2.PNG)

Personally I prefer the version 2.0.6 and add manually the block `<div id="captcha-box"></div>` directly on the contact form and empty the eicaptcha-contact-form.js file, it's much easier to add class around the block `<div id="captcha-box"></div>` to adjust it to my theme.

Anyway, thank you very much for this free module 🥇

**Comment by nenes25** [comment]
Hello @Stephane1874 
Thanks for your feedback :)
I'll try to fix this in next release.

Best regards,
