### ISSUE TITLE
EICAPTCHA (V2 or V3 is visible but has a message : ERREUR pour le propriétaire du site : Clé de site non valide even after regeneration of Keys

### ISSUE THREAD

**Issue by aerodiscount** [nenes25/eicaptcha#172]
**Prestashop Version**  
Your prestashop version :PS1.61.7

**Eicaptcha version**  
Eicaptcha version : (AM) eicaptcha v0.4.3 - par eicaptcha

**Do you use a specific theme**  
Are you using a specific theme, if yes please tell which : warehouse version 3.8.2 Conçu par IQIT-COMMERCE.COM 

**Describe the bug**  
EICAPTCHA (V2 or V3 is visible but has a message :
ERREUR pour le propriétaire du site : Clé de site non valide

So we regenerated Captcha private key  and Captcha public key but it is still the same problem.
Google detect that the website do not have a correct answer to recaptcha

When we regenerate the module and the 2 keys in V2 with a new web site creation ( same one as before www.aerodiscount.com adress) even when we say visible for the captcha (as we tried invisible), we have the same problem.
We noticed that the captcha position has changed from the time of the occurence of the problem (at that time no message inthe captcha square but google was saying not recognized) it is now NOT UNDER the client creation formular as it was before but under the added RGPD information of the page, that was not the case before.

**Screenshots**  
(do not know if it warks but everything is explained above)

![image](https://user-images.githubusercontent.com/76946335/103529994-fa7cd000-4e86-11eb-908e-279529c5028f.png)

**Additional context**  

Regards

**Comment by nenes25** [comment]
Bonjour,

En dehors d'une erreur de configuration de la clé recaptcha je ne vois malheureusement pas d'autres possibilité à cette erreur.
Le module supporte uniquement l'api V2 "Case à cocher"
J'ai encore configuré récemment des sites sans problèmes particuliers.

Cordialement,
Hervé
