### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Lauriane75** [nenes25/eicaptcha#178]

**Comment by nenes25** [comment]
Bonjour,

Je ne vois aucune trace du module sur l'url que vous m'avez fourni.
Du coup difficile d'identifier ce qui ne va pas.
Votre thème renvoie également une erreur js c'est peut être lié.

Cordialement,
Hervé

**Comment by Lauriane75** [comment]
Pardon je l’avais désactivé pour faire des tests d’inscription.
Le voilà à nouveau activé.

**Comment by nenes25** [comment]
C'est bizarre car les données sont bien envoyées.
![image](https://user-images.githubusercontent.com/7163132/110382126-c1193a00-805a-11eb-899d-4b1a57d13de1.png)
Est-ce que vous avait fait une mise à jour du module ou est-ce que vous l'avez installé sur un nouveau site ?
Est-ce que la surcharge du module contactform est bien prise en compte ?

**Comment by Lauriane75** [comment]
Bonjour et merci pour votre réponse.

Est-ce que vous avez fait une mise à jour du module ou est-ce que vous
l'avez installé sur un nouveau site ?
Non je n'ai pas fait de mise à jour, j'ai installé ce module sur un nouveau
site.

Est-ce que la surcharge du module contactform est bien prise en compte ?

Quel fichier dois-je overrider pour répondre à cette question ?

(Je suis débutante en dev sur prestashop.

Voici les accès si vous le souhaitez.

Prestashop target new V 1.7


link :
https://test2021.larouteduthe.com/admin046dxlmtt/index.php?controller=AdminLogin&token=517a21a39ba6bf03dba20ee2f3c5d6fb&redirect=AdminDashboard

Id : dev@help.com

Pw : devHelpPrestashop

Merci de votre aide.

Cordialement,

Lauriane Haydari.

**Comment by nenes25** [comment]
Bonjour,

Parfait si tout fonctionne alors :)
Je ferme donc cette demande.

Bonne journée,
Cordialement,
Hervé
