### ISSUE TITLE
Dont shown on Open account

### ISSUE THREAD

**Issue by dariodipa** [nenes25/eicaptcha#18]
Versión de PrestaShop: 1.7.2.4
Captcha dont appear on creation step, but required!

**Comment by nenes25** [comment]
Hello,

Thanks your feeback, but with so few informations i can't tell you what's wrong.
I've alrealdy tested this version with no issues.

Do you have a specific theme ?
Any Js error on the page ?

By the way, hello and thank you for the issues are welcome ..

**Comment by dariodipa** [comment]
Maybe This ? 

recaptcha__es_419.js:399 Uncaught Error: ReCAPTCHA placeholder element must be an element or id
    at Object.Qr [as render] (recaptcha__es_419.js:399)
    at onloadCallback (iniciar-sesion?create_account=1:74)
    at recaptcha__es_419.js:403
    at Br (recaptcha__es_419.js:394)
    at recaptcha__es_419.js:403
    at recaptcha__es_419.js:414

**Comment by nenes25** [comment]
Hello,

I guess you have a specific theme ?
The placeholder is added with this code : 
https://github.com/nenes25/eicaptcha/blob/master/eicaptcha.php#L362

If it doesn't work you can add the code <div id="captcha-box"></div> where you want the captcha to be displayed ( inside the form spans  )

Regards,

**Comment by dariodipa** [comment]
just this line ? L362 ?

**Comment by nenes25** [comment]
Yes just adapt the ".submit" in order or add manualy the div captcha-box ( it was written in my previous message but escpaed in the comment )
`<div id="catptcha-box"></div>`

**Comment by nenes25** [comment]
No feedback, issue closed
