### ISSUE TITLE
Erreurs et version

### ISSUE THREAD

**Issue by Gardella-Web** [nenes25/eicaptcha#183]
**Prestashop Version**  
Prestashop version 1.7.7.1

**Eicaptcha version**  
Eicaptcha version 2.1.0

**Do you use a specific theme**  
Theme parent : ZOneTheme
Theme enfant : destockphenix

**Describe the bug**  
Le cadre apparait et est fonctionnel mais le formulaire part même si je ne valide pas le Captcha.

Voici les erreurs données.
- the module is not registered in hook actionContactFormSubmitCaptcha
- the module is not registered in hook actionContactFormSubmitBefore
- AuthController.php override does not exists
- contactform.php override does not exists
- Authcontroller override is not present in class_index.php
- Module ps_emailsubscription version do not allow to use captcha on newsletter ( minimum version 2.6.0 required)

Le module ps_emailsubscription 'Inscription à la newsletter' est en v2.6.1 - par PrestaShop
Il était aussi manquant sur le Hook Header mais je l'y ai ajouté.

**Screenshots**  
![captcha](https://user-images.githubusercontent.com/71068367/113870161-d5636a80-97b1-11eb-9ebf-313358c6097c.PNG)

**Additional context**  
https://destockphenix.fr/

**Comment by nenes25** [comment]
Bonjour,

Le message de debug est plutôt clair.
Le module n'est pas bien installé car il manque pleins de chose nécessaires à son bon fonctionnement.
Essayez de le réinstaller et de vider le cache pour voir si cela corrige.
En dehors de l'information sur le formulaire de newsletter vous ne devriez avoir aucune erreur pour que le module fonctionne.
