### ISSUE TITLE
Don't require recaptcha for logged in clients

### ISSUE THREAD

**Issue by Triloworld** [nenes25/eicaptcha#184]
User create account and resolve captcha. He buy product and is now shop client. Then he need to ask question (about product etc). He is annoyed with another layer of protection to click in boxes (because reCaptcha is not ideal solution)

**Describe the solution you'd like**  
After first buy we might to disable protections for this particularly person. 

**Describe alternatives you've considered**  
Just for signed in user? It can be enought.

**Additional context**  
Real people don't need to be checked another time in any way. This is big benefit to have account.

**Comment by nenes25** [comment]
Hello,

I guess that this needs will be fixed with the implementation of recaptcha V3
Which is planned for later this year i hope.

Regards,

**Comment by atudosz** [comment]
What I've did in modules/eicaptcha/views/templates/hook/hookDisplayCustomerAccountForm.tpl (for v2, which I use)

    {if $captchaVersion == 2}
        <label class="col-md-3 form-control-label">{l s='Captcha' mod='eicaptcha'}</label>
        {if !$customer.is_logged}
        <div class="col-md-9">

**Comment by nenes25** [comment]
This functionality is implemented in the new version 2.4.0
