### ISSUE TITLE
Logged in user can have switch to force resolve captcha task

### ISSUE THREAD

**Issue by Triloworld** [nenes25/eicaptcha#185]
We have shop before installing this module. We need to check all peoples that they aren't boot and have some mark in account about state. 

**Describe the solution you'd like**  
We can use that state to be ensure about state of account.

**Describe alternatives you've considered**  
We can mail but this can be used cheap and by person who is logged in and in real time. 

**Additional context**  
Old account or exist but suspicious can be force to do test another time.
Then we have some count how much we force that person to resolve task or is forced by google.

**Comment by nenes25** [comment]
Hello,

This task is in addition of #184 and is related to your specifics needs.
So this will not be done, as this module is a generic one.
Feel free to fork it to implement this logic ;)

Regards,
