### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by koltatiq** [nenes25/eicaptcha#187]
**Prestashop Version**  
1.7.7.3
**Eicaptcha version**  
 V 2.1.0

the module is not registered in hook header 
**how to register it?**

Overrides are disabled on your website
![2021-04-17](https://user-images.githubusercontent.com/82684133/115121315-51c82b80-9fb2-11eb-9210-7e153aba2741.png)

**what replacements are you talking about?**

Module ps_emailsubscription version do not allow to use captcha on newsletter ( minimum version 2.6.0 required)
**I have v2.6.1**

**Comment by koltatiq** [comment]
I will be grateful for any help.
greetings

**Comment by nenes25** [comment]
Hello,

In order to fix the wrong detection of module ps_emailsubscription please update the module to version 2.1.1 ( which fix this issue )
For the override issue it is related with your website configuration.
Overrides are required as the module need to rewrite some function from modules and controllers
You need to let the configuration to "no " on the page "Advanced Parameters / Performances"
![image](https://user-images.githubusercontent.com/7163132/115236418-a63aea80-a11b-11eb-8517-a091acb3a12b.png)*

Regards,

**Comment by num47** [comment]
I was facing kinda the same problem. 

My eiCaptcha Module Version- 2.1.1. And my newsletter module version is - v. 2.0.2 and the Newsletter subscription module v. 2.6.1. All are updated, i think. Prestashop version 1.7.7.4. 

When i have turned on the option for recaptcha to newsletter subscription then it does not show the reCaptcha in the homepage. But, it doesn’t let you subscribe either saying that "Please validate the captcha field before submitting your request". That means that it is working partially. But, unfortunately it is not showing me the option to complete the reCaptcha challenge.

It shows the following error in the module page while i was checking if the module was installed properly. 

`Errors
the module is not registered in hook header
Missing hook displayNewsletterRegistration in template /server_folder/themes/classic//modules/ps_emailsubscription/views/templates/hook/ps_emailsubscription.tpl
Please check in original module file to adapt : /server_folder/modules/ps_emailsubscription/views/templates/hook/ps_emailsubscription.tpl`

Attaching Two image: Front and Back office
![Untitled](https://user-images.githubusercontent.com/33420890/116945530-b913fa00-ac99-11eb-92dc-882c1807be8b.png)
![Untitledp](https://user-images.githubusercontent.com/33420890/116945542-c03b0800-ac99-11eb-9223-110d06f258b1.png)

**Comment by nenes25** [comment]
Hello @num47 ,
In your case the error is self-explanatory
You need to update the template of your theme with the required hook.
You can read more about it in this article ( in french ) => https://www.h-hennes.fr/blog/2021/03/15/prestashop-ajouter-un-captcha-sur-linscription-a-la-newsletter/

**Comment by num47** [comment]
Hello @nenes25 ,
Thank you for the link. 
I have solved the problem and it seems working fine. But, in the back office in the module it kinda still showing this error: 
![Untitled](https://user-images.githubusercontent.com/33420890/117000461-ee086700-ad02-11eb-90e1-e482eae075eb.png)

**Comment by nenes25** [comment]
Hello,
This is error is  a wrong positive but everything should works fine.

**Comment by irisia4** [comment]
Hello,

In my case I have v2.7.0 suscription module (from prestashop) and v2.4.0 eicaptcha module and don't work the option "Enable Captcha for newsletter registration". Could you please help me?

**Comment by nenes25** [comment]
Hello,
As this issue is closed could you please open a new one with required information ?
Regards,
