### ISSUE TITLE
Compatible with reCaptcha V3 (V2 is not available anymore on Google reCaptcha Entreprise)

### ISSUE THREAD

**Issue by 8ternity** [nenes25/eicaptcha#188]
I try to install with version 2.0 but Google has discontinued the version 2.0.

We can only setup new version 3.0.
[You can refer here](https://cloud.google.com/recaptcha-enterprise/docs/migrate-recaptcha?hl=en#before-you-begin)

Is it possible to have a upgraded version to reCaptcha 3 ?

Thank you.

**Comment by nenes25** [comment]
Hi,

With an existing account i'm still abble to create a new key with the v2 version.
![image](https://user-images.githubusercontent.com/7163132/116305074-91a5c480-a7a3-11eb-8243-6ba30feff3d9.png)
Can you confirm that it's not possible anymore for new account ?
Enterprise version seems to be usefull only if you display more than 1M/captcha month

V3 is planed but not before some weeks.
Thanks for the link, i was not aware of this change.

Regards,

**Comment by bramvdp** [comment]
I can confirm I couldnt find a way to generate a v2 key as well.
Then I googled for it specifically, and I could create one via this link https://www.google.com/recaptcha/admin/create
