### ISSUE TITLE
La reCaptcha est en dessous du bouton "Envoyer"

### ISSUE THREAD

**Issue by RidaLeFou** [nenes25/eicaptcha#191]
**Prestashop Version**  
![image](https://user-images.githubusercontent.com/48444886/117581339-8c7a3b00-b0fc-11eb-89b8-fa071f4e370b.png)

**Eicaptcha version**  
2.1.1

**Do you use a specific theme**  
Lacausa

**Describe the bug**  
Est ce que c'est possible d'inverser l'emplacement du bouton Envoyer dans le formulaire de contact et de la reCaptcha?

**Screenshots**  
![image](https://user-images.githubusercontent.com/48444886/117581318-73718a00-b0fc-11eb-86e0-1c91e0dc9fad.png)

**Additional context**

**Comment by nenes25** [comment]
Bonjour,

Le problème est sans doute lié aux positionnement de votre thème.
Pour corriger cela, vous pouvez ajouter manuellement le tag du captcha dans le template du formulaire de contact de votre thème à l'endroit ou vous souhaitez l'afficher  ( themes/_themeName_/modules/contactform/views/templates/widget/contactform.tpl
`<div id="captcha-box"></div>`
et vous pouvez commenter le code dans le fichier views/js/eicaptcha-contact-form.js ( qui rajoute automatiquement ce code )

**Comment by RidaLeFou** [comment]
ok merci :)
