### ISSUE TITLE
The send to contact button does not work

### ISSUE THREAD

**Issue by koltatiq** [nenes25/eicaptcha#192]
**Prestashop Version**  
1.7.7.4
**Eicaptcha version**  
v2.1.1

**Do you use a specific theme**  
Classic Wersja 1.0.0

**Describe the bug**  
After enabling recaptcha on the contact page - the button SEND A MESSAGE stopped working (the mouse does not notice the link).
You can only send a message by changing tabs and characters.
It also does not work in the inkognito window, for browsers in Chrome with google and Edge with Microsoft. (The button in the account registration works normally).

Everything works fine in Firefox - here it is ok.

**Screenshots**  
![niewysyla](https://user-images.githubusercontent.com/82684133/118876854-02955380-b8ee-11eb-9ded-a4edc4f10a42.jpg)

**Comment by koltatiq** [comment]
Check for yourself from the chrome google and edge settings: https://koltat.com/kontakt

**Comment by nenes25** [comment]
Hello,
Weird issue but seems related with your theme, i see no issue on classic theme.
Could you try to add the following line in views/css/eicaptcha.css
#captcha-box { overflow:hidden }

Regards,

**Comment by koltatiq** [comment]
Thank you for your interest..
I pasted where I could.
But it doesn't work either.

Strange that firefox works normally.
`.contact-form form .form-fields #captcha-box > div{float: right;}
.contact-form form .form-footer{clear: both;padding-top: 1rem;}
.contact-form form .form-footer{#captcha-box { overflow:hidden };}
@media screen and (max-width: 767px){
    #contact #left-column,
	#captcha-box { overflow:hidden }

    #contact #content-wrapper{padding-left: 0!important;padding-right: 0!important;width: 100%;}
    .contact-form form .form-fields #captcha-box{position: relative;min-height: 78px;}
    .contact-form form .form-fields #captcha-box > div{float: none;position: absolute;left: 50%;top: 0;transform: translate(-50%,0);}
}
@media screen and (max-width: 379px){
    .register-form form .form-group .g-recaptcha{position: relative;min-height: 78px;}
    .register-form form .form-group .g-recaptcha > div{float: none;position: absolute;left: 50%;top: 0;transform: translate(-50%,0);}
	#captcha-box { overflow:hidden }

}`

**Comment by koltatiq** [comment]
[](url)
![2021-05-20 (2)](https://user-images.githubusercontent.com/82684133/118979616-edb1d200-b978-11eb-94cb-73736521419e.png)

**Comment by nenes25** [comment]
Hi,

You have a wrong  syntax on line 3 you should have
`.contact-form  #captcha-box {overflow:hidden}`
if you want to target the element
![image](https://user-images.githubusercontent.com/7163132/119035339-c0cce180-b9af-11eb-841f-f5219952949b.png)

**Comment by koltatiq** [comment]
Improved and Works!
Hurray 👍 
Thank you very much. 
Best Regards

**Comment by nenes25** [comment]
Great !  I close this issue :smile:
