### ISSUE TITLE
Impossible de trouver le module "Formulaire de contact" 

### ISSUE THREAD

**Issue by MOD-PROD** [nenes25/eicaptcha#194]
**Prestashop Version**  
1.7.32

**Eicaptcha version**  
2.1.1

**Do you use a specific theme**  
Non 

**Describe the bug**  
Apres quelques heures de recherches web impossible de trouver le module "Formulaire de contact" qui a disparu de mon prestashop , il est plus dispo a l instalation non plus !
Que faire ? Auriez vous une solution ?
Merci d' avance

**Screenshots**  
![Screenshot 2021-07-25 at 16-46-15 Modules et services • ACTIVE POWER](https://user-images.githubusercontent.com/62851595/126904403-50ce9acb-eb16-41f4-9f9a-1efbf3bd9e74.png)

**Comment by nenes25** [comment]
Bonjour,

Vous pouvez télécharger le module de contact de prestashop directement depuis github :
https://github.com/PrestaShop/contactform/releases 

Cordialement,
Hervé
