### ISSUE TITLE
Prestashop 1.6.1.1 with default theme and V0.4.5 Module Version

### ISSUE THREAD

**Issue by StefArts** [nenes25/eicaptcha#2]
Hello,
Thank you so much for this module!
It is working on my prestashop 1.6.1.1 with default theme and V0.4.5 Module Version.
The only thing is that product comment still keep the default prestashop captcha… I do not know why.

One other strange thing is that the captcha is correctly installed and displayed on the contact form on my computer
The problem is that it is not displayed when I visit the contact form from a mobile phone (iPhone).
I have make a test and I have been able to send a message…

It is also impossible for me to have it displayed on  the "Send to a Friend Form"

Captcha is diplayed correctly on registration form on booth devices…
Someone have the same problem?
Some help on these issues?

![post-1106501-0-17581000-1444250922](https://cloud.githubusercontent.com/assets/15027588/10359396/898d10c8-6d98-11e5-8fc8-2e8e04a62076.png)
![post-1106501-0-29709100-1444250927](https://cloud.githubusercontent.com/assets/15027588/10359397/899b3482-6d98-11e5-96c5-6ddb102c3c54.png)
![post-1106501-0-33890100-1444250923](https://cloud.githubusercontent.com/assets/15027588/10359398/89a98b68-6d98-11e5-9627-97000b61421c.png)
![post-1106501-0-44196000-1444250924](https://cloud.githubusercontent.com/assets/15027588/10359399/89dbb7fa-6d98-11e5-94d8-8300df835317.png)
![post-1106501-0-70351100-1444250925](https://cloud.githubusercontent.com/assets/15027588/10359400/89e62b0e-6d98-11e5-976f-3ca21308f9fe.png)

**Comment by nenes25** [comment]
As see with you the problem is solved.
Regards,
