### ISSUE TITLE
With v. 0.4.17 incorrect response and js error.

### ISSUE THREAD

**Issue by Idas86** [nenes25/eicaptcha#200]
With the version 0.4.17 I can read this message in account creation form:
 _

> "incorrect response to CAPTCHA challenge. Please try again."

_

I also see a js error: 
_

> "window.grecaptcha.render is not a function"

_
This is the link: [http://www.sacco-matto.com/login](http://www.sacco-matto.com/login)

**Comment by nenes25** [comment]
Hello,

I cannot reproduce this issue
![image](https://user-images.githubusercontent.com/7163132/136837779-2a718469-5395-4272-8e89-f68b0951c3e1.png)

By the way this version is not supported anymore.

Regards,
