### ISSUE TITLE
V2.3.1: les modes sombre et clair sont inversés

### ISSUE THREAD

**Issue by gringo1er** [nenes25/eicaptcha#202]
**Prestashop Version**  
1.7.7.8

**Eicaptcha version**  
2.3.1

*Bonjour. Rien de grave, juste les modes sombre et clair inversés: pour avoir l'un il faut juste cocher l'autre....

Merci pour cet excellent module!

**Comment by nenes25** [comment]
Bonjour @gringo1er,

Merci pour votre retour.
Je confirme effectivement le soucis

**Comment by nenes25** [comment]
Le problème sera corrigé dans la prochaine release.
