### ISSUE TITLE
v2.3.1 invalid site key (While it is the correct one)

### ISSUE THREAD

**Issue by jonathanromain** [nenes25/eicaptcha#203]
Prestashop 1.7.6.8
Module v2.3.1
Thème : classic children

The site tells me that the site key is incorrect even though it is the correct one that I just copied from google's reCAPTCHA site.

I tested to reverse them, in v2 or V3, same result ..
![Capture d’écran 2021-10-07 à 11 32 52](https://user-images.githubusercontent.com/34910831/136359432-5be0bb00-5bac-46a1-aaef-8af26a8b99d0.png)
![Capture d’écran 2021-10-07 à 11 28 50](https://user-images.githubusercontent.com/34910831/136359437-e4b06a48-37cf-48df-997d-8c991d2821e7.png)

**Comment by nenes25** [comment]
Hi jonathan,

I'm not able to reproduce your issue.
Are you sure that your key is the good one and that your site domain is allowed on it ?

Regards,
