### ISSUE TITLE
Captcha box is not visible

### ISSUE THREAD

**Issue by StudioDel** [nenes25/eicaptcha#205]
**Prestashop Version**  
1.7.6.7

**Eicaptcha version**  

17

**Do you use a specific theme**  

PRS080191 Version 1.0.0
made by TemplateMela

**Describe the bug**  

Hi ! I'm a webdesigner and I'm trying to add the captcha security to the contact form of a client website.
I already add the module, and I configured it using api key and secret key provided by google.
Everything seems ok but there is no captcha box. I have the visual element on the bottom right corner of the webpage display but nothing else. Could you please help me ? Thanks.

**Screenshots**  
![image](https://user-images.githubusercontent.com/92372144/136946860-3fc712ad-501d-4d54-acb9-d4e592c85594.png)

**Additional context**  
/

**Comment by StudioDel** [comment]
Hi.
I just figured out that i'ts working if I use captcha V2 instead of the V3. Maybe this information can help.

**Comment by nenes25** [comment]
Hello,
Yes the new behaviour with v3 is only displayed to the customer if needed.
By default it is invisible, but it works this way :smile: 
But you are right I need to update the readme in order to be clearer about this.

Regards,

**Comment by panacy** [comment]
Hello!
I have similar problem, box is not visible. I use warehouse theme with Syle 8. Here is the address: https://www.rubyvocalbooth.com/pl/content/7-kontakt-z-nami

Can't get keys for reCAPTCHA v2 because it's not available in my admin console :/

Help pls!

![obraz](https://user-images.githubusercontent.com/33621903/137151432-7fe4dce4-1de7-4d33-bc85-94078feb2ebc.png)

**Comment by nenes25** [comment]
Hello,
As written before it's not a bug.
It's the new behaviour of recaptcha, i've clarified it in the README file.

Regards,

**Comment by panacy** [comment]
Hello!

I've read README file but it does not solve my problem :( I did 
everything exactly with the instruction but reCaptcha box is still not 
visible. When I do the test message contact form tells me to fill up the 
captcha box, but no box :(

Regards
Paul

------ Wiadomość oryginalna ------
Od: "Hervé H." ***@***.***>
Do: "nenes25/eicaptcha" ***@***.***>
DW: "panacy" ***@***.***>; "Comment" ***@***.***>
Data: 19.10.2021 08:43:35
Temat: Re: [nenes25/eicaptcha] Captcha box is not visible (#205)

**Comment by nenes25** [comment]
Hello Paul,

I've found why you have an issue on your website.
Your contact form is not on the native dedicated page but in a cms page.
The module will not work with this behavior.
The default contact page on your site will be this one : https://rubyvocalbooth.com/pl/kontakt

Regards,
Hervé

**Comment by CamilleVDP** [comment]
Hi Herve, 
The captcha works fine in the registration form but not on contact forms added on CMS pages. Do you know how to make it work? Or if there is another module that allows a captcha on those pages? 
Thanks a lot.
