### ISSUE TITLE
Bug après installation 

### ISSUE THREAD

**Issue by Franck-J** [nenes25/eicaptcha#208]
**Prestashop Version**  
Your prestashop version
1.7.8.0
**Eicaptcha version**  
Eicaptcha version
2.3.1
**Do you use a specific theme**  
Are you using a specific theme, if yes please tell which
Classic
**Describe the bug**  
Demande envoyée après vérification recaptcha, formulaire non reçu dans le backoffice, message "Merci de valider le captcha"
**Screenshots**  
![image](https://user-images.githubusercontent.com/93387373/139441154-2d1e9d39-b3d9-48fb-93c9-129473f5d5e2.png)

**Additional context**

**Comment by nenes25** [comment]
Bonjour,
Je viens de tester sans problèmes particuliers.
Le captcha est bien fonctionnel sur une version 1.7.8.0 que ce soit en v2 ( case à cocher ) ou en v3 ( invisible )
Pouvez-vous fournir une url ?
Est-ce que vous avez des modules additionnels installés ?

Cordialement,
