### ISSUE TITLE
Security prompt is not displayed

### ISSUE THREAD

**Issue by AreSee** [nenes25/eicaptcha#209]
**Prestashop Version**  
1.7.7.8

**Eicaptcha version**  
2.3.1

**Do you use a specific theme**  
Special Theme from templatemonster

**Describe the bug**  
Users do not seem to see a security prompt and can no longer register. I don't know how to test this as I don't get a security prompt from reCaptcha v3.
I only know the bug from user feedback.

How can i test the Security Check?

**Comment by nenes25** [comment]
Hello,

Sorry for the late reply.
With private navigation you can have a different behavior.
Have you try the v2 version ?

Regards,
