### ISSUE TITLE
Compatibilité avec PS 1.7.8.x

### ISSUE THREAD

**Issue by gringo1er** [nenes25/eicaptcha#210]
Bonjour
Le module crée des soucis de compatibilité avec la version 1.7.8.x (actuellement 1.7.8.2).
Après déploiement, la page de contact (contact form) ne fonctionne plus si elle est surveillée, et fonctionne 10 mn quand elle n'est pas surveillée par Captcha, mais le module actif.
Quand la page contact est surveillée il marche aussi une dizaine de minutes, puis "erreur inattendue".
Je pensais au départ qu'il s'agissait d'un souci de compatibilité avec le template, mais d'après sa hotline, c'est plutôt une incompatibilité avec PS 1.7.8.x
https://www.agnesdelaguila.com/fr/nous-contacter

**Comment by nenes25** [comment]
Bonjour,

Merci pour votre retour.
Je n'ai jamais eut ce type de comportement ( 10 min de fonctionnement  même si désactivé )
Quelles sont les actions effectuées pour obtenir cette erreur ?

Cordialement,

**Comment by gringo1er** [comment]
Bonsoir

Sur notre site de préprod, j'ai mis en protection captcha v3 la page de 
contact et la création de compte.

https://www.agnesdelaguila.com/fr/nous-contacter

Vous verrez, si vous laissez un message, il y aura "une erreur s'est 
produite pendant l'envoi".

Ce bug ne survient qu'une dizaine de minutes après la mise en 
protection. Avant, les messages partent sans problème.

Si je protège la création de compte uniquement, et que la page contact 
n'est plus protégée, les messages fonctionnent une dizaine de minutes, 
et passé ce délai, le message d'erreur est plutôt "undefined".

A votre convenance, je déprotègerai la page contact.

En captcha v2, si la méthode de sécurisation est différente, les 
symptômes sont les mêmes. Du coup, la question suivante se pose: votre 
module est-il compatible avec tout template, y compris des templates 
Elementor, ou n'est-il compatible que avec "classic"?

Merci!

Hervé (comme vous...)

Le 21/12/2021 à 21:05, Hervé H. a écrit :
