### ISSUE TITLE
demande de validation de captcha apres validation du formulaire 

### ISSUE THREAD

**Issue by juliendhl** [nenes25/eicaptcha#214]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.8.x

### Eicaptcha version

2.3.x

### Do you use a specific theme ?

Warehouse 

### Describe the bug

a chaque fois que je valide le captcha et le formulaires j'ai un message d'erreur 'valider le captcha'

### Screenshots

*

### Additional context

*

**Comment by nenes25** [comment]
Bonjour,

Désolé pour le délai de réponse.
Si le problème est toujours en place, est-ce possible d'avoir une url du site ?

Cordialement,
Hervé
