### ISSUE TITLE
Le Captcha n'apparait pas sur le formulaire de contact - Erreur à la validation. 

### ISSUE THREAD

**Issue by Ananda4h20** [nenes25/eicaptcha#216]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.8.x

### Eicaptcha version

2.3.x

### Do you use a specific theme ?

Monstera

### Describe the bug

Salut, j'ai tout bien configuré il me semble, mais le Captcha n'apparait pas sur le formulaire de contact donc impossible de le cocher. 

Pourtant, à la validation du formulaire, une erreur apparait : «Veuillez cocher le Captcha ». 

Sur le formulaire de création de compte pas de souci il apparait bien.

**Comment by Ananda4h20** [comment]
Sur un Captcha V3, idem. Je peux créer un compte sans souci... Mais sur le formulaire de contact, cela ne fonctionne pas...

Merci en tout cas pour le boulot et merci pour l'aide si jamais ;-)

**Comment by Ananda4h20** [comment]
Sur la console : 

Uncaught ReferenceError: require is not defined
    at 10-contact:164:11
(anonyme) @ 10-contact:164

**Comment by nenes25** [comment]
Bonjour,

Est-ce que vous pouvez me donner une url ?
Je ne connais pas ce thème il est possible qu'il ne soit pas compatible avec le natif.
Vous pouvez regarder l'article suivant si il est nécessaire de cibler le positionnement du captcha dans le formulaire.
https://www.h-hennes.fr/blog/2018/02/23/eicaptcha-ajout-dune-configuration-avancees-des-selecteurs/

Cordialement,
Hervé

**Comment by Ananda4h20** [comment]
Bonjour, merci pour la réponse https://la-jacquerie.fr

**Comment by nenes25** [comment]
Bonjour,

En fait le captcha ne fonctionne que sur le formulaire de contact par défaut de prestashop.
Qui est ici : https://la-jacquerie.fr/nous-contacter ( on voit bien que la protection par captcha est active )
En revanche votre formulaire mis en avant est dans une page cms : https://la-jacquerie.fr/content/10-contact
Du coup le captcha ne pourra malheureusement pas fonctionner sur celui-ci.

Cordialement,
Hervé

**Comment by Ananda4h20** [comment]
Ahhh bien oui évidemment. Ca roule merci !
