### ISSUE TITLE
Problem on contact form

### ISSUE THREAD

**Issue by slay334** [nenes25/eicaptcha#219]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.6.x

### Eicaptcha version

2.3.x

### Do you use a specific theme ?

akira theme

### Describe the bug

Captcha Code doesn't appear in my contact form

**Comment by slay334** [comment]
https://www.somedis-hygiene.fr/content/19-contactez-nous

**Comment by nenes25** [comment]
Hello,

The url you have provided is not on the real contact page of Prestashop.
Which is https://www.somedis-hygiene.fr/nous-contacter and where the recaptcha works as expected.
Unfortunately it will not works on other custom pages.
This issue is the same as this one #216

Regards,
