### ISSUE TITLE
Recaptcha is not displayed on my contact form

### ISSUE THREAD

**Issue by Jnetcom** [nenes25/eicaptcha#222]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

< 1.7

### Do you use a specific theme ?

panda

### Describe the bug

Hi, the recaptcha is not displayed on the contact form of my website.
I noticed that those errors are displayed when I check the installation of the module:
- the module is not registered in hook contactFormAccess
- ContactController.php override does not exists
- ContactController.php override is not present in class_index.php => Please remove file cache/class_index.php in order to fix the issue

I searched on other topics but I didn't find a solution to my issue... 
The ContractController.php file exists in the FTP of my site.
I removed the cass_index.php as asked but the last error occurs always.

I don't know what to do...
Thank you for your help.

**Comment by nenes25** [comment]
Hello,

Sorry for the late response.

I guess you should try to reinitialize the module in order to let it install as expected.

Regards,
