### ISSUE TITLE
initContent method in class AuthController has been overriden already - can not enable module

### ISSUE THREAD

**Issue by ButcherFromHell** [nenes25/eicaptcha#223]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

< 1.7

### Eicaptcha version

2.3.x

### Do you use a specific theme ?

custom

### Describe the bug

I have uploaded module but can not enable it. 

**Error!
Cannot enable module eicaptcha. Unable to install override: The method initContent in the class AuthController is already overridden.**

### Additional context

I have cecked if module is installed well.

Success

    the module is compatible with your version
    the module contactform is installed
    the module well registered in hook header
    the module well registered in hook displayCustomerAccountForm
    the module well registered in hook actionContactFormSubmitCaptcha
    the module well registered in hook actionContactFormSubmitBefore
    Overrides are enabled on your website
    AuthController.php override exists
    contactform.php override exists
    Authcontroller override is present in class_index.php

    Recaptcha version : 2
    Prestashop version : 1.7.6.1
    Theme name : custom
    Php version : 7.2.33

**Comment by nenes25** [comment]
Hello,

You need to check the content of the file override/controllers/front/Authcontroller.php and you'll see which other module has overwrite it.
Unfortunately it's not possible for 2 different modules to rewrite the same function.

Regards,
