### ISSUE TITLE
Hook not setup

### ISSUE THREAD

**Issue by Garfield2013** [nenes25/eicaptcha#224]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.8.x

### Eicaptcha version

2.3.x

### Do you use a specific theme ?

Please check the screenshots:

[https://www.screencast.com/t/MRv0kl2s2W7j](https://www.screencast.com/t/MRv0kl2s2W7j)
[https://www.screencast.com/t/kQXNKkmuZXU](https://www.screencast.com/t/kQXNKkmuZXU)

### Describe the bug

Please check the screenshots

**Comment by Garfield2013** [comment]
FIXED! I added it to my custom theme as well and now the error disappeared :)

**Comment by nenes25** [comment]
Hello,
Great so i close this issue :smile:

**Comment by Garfield2013** [comment]
Actually I didn't manage to get your module to work.
I just thought it worked because the recaptcha icon showed up. But it still
complained when I used our site.
So I went with this free module instead:
https://www.team-ever.com/prestashop-google-captcha-anti-spam/
It adds the recaptcha on all pages - without a single issue ;)
