### ISSUE TITLE
Recaptcha bug create account

### ISSUE THREAD

**Issue by TFF1604** [nenes25/eicaptcha#225]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.3.x

### Eicaptcha version

2.3.x

### Do you use a specific theme ?

Flatone theme
editor : Atchworks

### Describe the bug

the module appears and functions correctly on the contact page.
But it does not show on the account creation page and prevents the account creatio
![Capture d’écran 2022-07-15 à 09 19 37](https://user-images.githubusercontent.com/63454932/179220113-623a0c49-b4ff-4644-b731-4a175ca1a094.png)
![recaptcha copie](https://user-images.githubusercontent.com/63454932/179220159-13bcb4ed-0208-4b35-889d-978929ccb839.png)
n

### Screenshots

Debug function of module is actived, but no erro
![recaptcha copie](https://user-images.githubusercontent.com/63454932/179220485-870f09d2-7bfa-4b35-b8d7-223ca0fb6eba.png)
r

### Additional context

Steps to reproduce

    connexion
    creation a new account
    Please complete the following
    validate
    5 after validation registration of the new customer impossible

**Comment by nenes25** [comment]
Hello,

Can you send me an Url to check ?
I guess it should be related with the theme.
You can also check if you find the hook displayCustomerAccountForm in it. 

Regards,

**Comment by TFF1604** [comment]
Bonjour,
voici l'url
https://www.1001couteaux.fr/connexion?create_account=1
c'est le v3 invisible qui est installé

**Comment by TFF1604** [comment]
![Capture d’écran 2022-07-18 à 08 56 50](https://user-images.githubusercontent.com/63454932/179458963-bf39ccda-ffed-4f9b-b886-2db291bc39fa.png)

**Comment by TFF1604** [comment]
Bonjour Hervé, avez-vous eu le temps de checker pour voir d'où pourrait venir le problème.
Cordialement,
Christophe.

**Comment by nenes25** [comment]
Bonjour Christhope,

De mon côté j'ai vérifié sur une version de base en 1.7.3.4 et tout fonctionne comme attendu.
Dans le cas ou le formulaire est protégé on peut voir en bas de page l'icône recaptcha
![image](https://user-images.githubusercontent.com/7163132/179973662-9340722d-d4dc-462c-ab33-5beb614f0509.png)
Ce qui n'est pas le cas sur votre site.

Est-ce que vous pouvez vérifier dans le fichier de votre thème themes/*nomDeVotreTheme*/templates/customer/_partials/customer-form.tpl que le hook **hook_create_account_form** est bien présent ?
![image](https://user-images.githubusercontent.com/7163132/179974191-a6b0f173-abd9-46eb-880b-1bf49acd8902.png)

**Comment by TFF1604** [comment]
Effectivement, le hook n'était pas présent, après l'avoir ajouté et vidé le cache le captcha fonctionne.
merci de votre aide.
Cordialement,
Christophe.

**Comment by nenes25** [comment]
Parfait, 

Merci pour votre retour.
Je laisse votre demande ouverte et je me note de voir si je ne peux pas améliorer le debug du module pour identifier ce cas.
Car ce n'est pas la première fois qu'il arrive.

Cordialement,
Hervé

**Comment by TFF1604** [comment]
Pour info:
4 sites en PS 1.7.3 à chaque fois le hook n'était pas présent et après installation de celui-ci il a fallu vider le cache et tout est ok sur ces 4 sites.
1 site en PS 1.7.6.7
tout a fonctionné correctement, le hook était bien présent.
Cordialement,
Christophe.

**Comment by nenes25** [comment]
C'est possible que l'éditeur du thème n'avait pas repris correctement le hook dans son template, la version 1.7.3 est relativement ancienne déjà.
Sur les versions plus récentes il n'y a généralement pas de soucis.

Merci pour vos retours,
Cordialement,
Hervé

**Comment by diegofrancesco** [comment]
> Bonjour Christhope,
> 
> De mon côté j'ai vérifié sur une version de base en 1.7.3.4 et tout fonctionne comme attendu. Dans le cas ou le formulaire est protégé on peut voir en bas de page l'icône recaptcha ![image](https://user-images.githubusercontent.com/7163132/179973662-9340722d-d4dc-462c-ab33-5beb614f0509.png) Ce qui n'est pas le cas sur votre site.
> 
> Est-ce que vous pouvez vérifier dans le fichier de votre thème themes/_nomDeVotreTheme_/templates/customer/_partials/customer-form.tpl que le hook **hook_create_account_form** est bien présent ? ![image](https://user-images.githubusercontent.com/7163132/179974191-a6b0f173-abd9-46eb-880b-1bf49acd8902.png)

Hello,
I had the same problem and the solution also works in my case. 
PS v 1.7.2.4

Thank you!

**Comment by nenes25** [comment]
Great thanks all for the feedbacks :smiley:  i close the issue as it's not related with the module
