### ISSUE TITLE
reCaptcha doesn't show anywhere Presta 1.7.8.6

### ISSUE THREAD

**Issue by TecnoHands** [nenes25/eicaptcha#226]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.8.x

### Eicaptcha version

2.3.x

### Do you use a specific theme ?

Classic and Warehouse

### Describe the bug

I install the module in clean prestahop installation, don't appears have any wrong but Captcha don't appears anywhere in the pages.

Success
the module is compatible with your version
the module contactform is installed
the module well registered in hook header
the module well registered in hook displayCustomerAccountForm
the module well registered in hook actionContactFormSubmitCaptcha
the module well registered in hook actionContactFormSubmitBefore
Overrides are enabled on your website
AuthController.php override exists
contactform.php override exists
Authcontroller override is present in class_index.php
Module ps_emailsubscription version allow to use captcha on newsletter
Additional information
Recaptcha version : 3
Prestashop version : 1.7.8.6
Theme name : classic
Php version : 7.4.30

I config the option to write in a log, but don't works

**Comment by nenes25** [comment]
Hello @TecnoHands  and sorry for the late reply.
Could you please provide some urls to check ?
Pay attention that with v3 version the display of the captcha is just a small box in the bottom right corner as see in the documentation.
Regards,
