### ISSUE TITLE
[enhancement]: enable https://www.hcaptcha.com/ too

### ISSUE THREAD

**Issue by HartLarsson** [nenes25/eicaptcha#227]
### Check if your feature request exists

- [X] My feature request does not already exists

### Is your feature request related to a problem?

Due to recent Problem with Google tools and GDPR why not implementing the compatibility with hCaptcha too? ( https://www.hcaptcha.com/ )

### Describe the solution you'd like

Have a possibility to choose between google recaptcha and hcaptcha

**Comment by nenes25** [comment]
Hello @HartLarsson ,

Thanks for your suggestion, your issue is a duplicate of #199 
So i'll close it and let the other one opened.
Currently i've no time to work on this, but maybe in the future.

Regards,
