### ISSUE TITLE
Not registered on hook actionContactFormSubmitCaptcha

### ISSUE THREAD

**Issue by nenes25** [nenes25/eicaptcha#230]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.8.x

### Eicaptcha version

2.3.x

### Do you use a specific theme ?

Not related with theme

### Describe the bug

When running the debug , the module report that it's not registered on hook actionContactFormSubmitCaptcha
This issue should be related with the rename of this hook on version 2.4.0

**Comment by HartLarsson** [comment]
ps 1.7.8.7 same problem with latest version 2.4.0

![image](https://user-images.githubusercontent.com/16102074/204569959-72900019-1db7-429a-adfa-af1c000dd06d.png)

ps_emailsubscription version v2.7.0

**Comment by AmadaniSASDESMELIE** [comment]
Same here, any solution ? Captcha validation asked but don't showup

**Comment by inspectaclueso** [comment]
I too have the same issue...

    Recaptcha version : 2
    Prestashop version : 1.7.7.3
    Theme name : classic
    Php version : 7.3.33
![captcha_error](https://user-images.githubusercontent.com/4586772/216147340-a1a80428-8f42-4b8e-9c8c-cd5fad2e57b0.jpg)

**Comment by nenes25** [comment]
This issue is fixed in version 2.4.1

**Comment by Toshiakea** [comment]
Hi @nenes25 . Thanks for the answer in my thread. And thanks for the version 2.4.1. The message has dissapeared.

But I have a second problem. We can see the "Captcha" icon in the bottom rigth, but I can see the "I am not a Robot" question.

Any ideas? 

Thanks a lot!!!

![imagen](https://user-images.githubusercontent.com/125131903/218307712-815126a4-d390-4ec2-b1b5-f8988f566f26.png)

**Comment by matik4** [comment]
> Hi @nenes25 . Thanks for the answer in my thread. And thanks for the version 2.4.1. The message has dissapeared.
> 
> But I have a second problem. We can see the "Captcha" icon in the bottom rigth, but I can see the "I am not a Robot" question.
> 
> Any ideas?
> 
> Thanks a lot!!!
> 
> ![imagen](https://user-images.githubusercontent.com/125131903/218307712-815126a4-d390-4ec2-b1b5-f8988f566f26.png)

You are using v3 captcha, so there is no checkbox - it is only present in v2
https://www.google.com/recaptcha/about/

**Comment by Toshiakea** [comment]
Oh! I think that there was a checkbox in v3 too.

Thanks for your help ☺️

**Comment by HartLarsson** [comment]
> This issue is fixed in version 2.4.1

Thank you!

Please next time keep release version consistency because the 2.4.1 was already released with the bug you have fixed now and you call this new version 2.4.1 again instead of 2.4.2 as the logic suppose.

![image](https://user-images.githubusercontent.com/16102074/219127912-7981732d-7194-45f5-9baf-f25ee2c9e339.png)

**Comment by nenes25** [comment]
Hello,
Thanks for feedback.
In fact i use only the branch, "Master" on this repository.
It s only the release file which represent the release :smile:  . 
I undserstand that it could be an issue,  i ll take care of this, next time

Regards,

**Comment by HartLarsson** [comment]
thank you i was getting crazy because i found I'd already installed the 2.4.1 and had a bug and now you release 3 days ago the new 4.2.1 lol
