### ISSUE TITLE
Recaptcha affiché mais ne fonctionne pas

### ISSUE THREAD

**Issue by Paul-88** [nenes25/eicaptcha#231]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.8.x

### Eicaptcha version

2.3.x

### Do you use a specific theme ?

MegaShop 2.3.0

### Describe the bug

Le logo reCAPTCHA est bien affiché sur la page d'inscription et de contact, il y a bien {$hook_create_account_form nofilter} dans le fichier du thème, cependant j'ai toujours l'erreur comme quoi il faut valider un captcha. 
J'ai testé une désinstallation/réinstallation complète du module, sans succès. 
J'ai un autre site ou le module fonctionne, avec le même thème, je ne comprend pas vraiment d'où cela pourrait venir…

### Screenshots

![image](https://user-images.githubusercontent.com/116373181/197234780-c92b742c-73dc-488c-b4ef-2a9f3a900ee0.png)
![image](https://user-images.githubusercontent.com/116373181/197234879-34e4da8f-d83a-4241-8d6d-68c8358bf9c8.png)
![image](https://user-images.githubusercontent.com/116373181/197235005-558763e8-7b3e-4d57-94ef-747262122ad5.png)
![image](https://user-images.githubusercontent.com/116373181/197239512-2d9e0792-1ad2-45e3-97c6-06f286a1a1a2.png)

**Comment by nenes25** [comment]
Bonjour,

Je ne saurais pas vous dire en détail quelle pourrait être la cause de votre erreur.

Mais plusieurs pistes :
- Vérifier si d'autres modules sont greffés sur le mêmes hooks que le module
- Activer le mode debug et regarder les messages d'erreurs du fichier de log

Cordialement,

**Comment by Paul-88** [comment]
![image](https://user-images.githubusercontent.com/116373181/197567495-a5e5ddc3-a3d2-42cd-92a4-9fea5cbcc7e9.png)
Tout semble correcte en comparant avec mon autre boutique Prestashop. 

J'ai bien activé le mode debug depuis plusieurs jours, cependant je n'ai aucun fichier présent dans le FTP...

**Comment by nenes25** [comment]
Bonjour,

Difficile de pouvoir vous en dire plus sur la cause de l'erreur.
Je pense qu'il va falloir débuguer via le code afin de vérifier ce qu'il se passe.
Peut être un problème de droits concernant le fichier de logs car comme vous pouvez le voir ici : https://github.com/nenes25/eicaptcha/blob/17/eicaptcha.php#L425 dès lors qu'il y'a une erreur de validation il devrait y avoir un log avec l'erreur.

Essayer de faire un dump de $result pour voir la réponse apportée par le captcha.

Cordialement,

**Comment by Paul-88** [comment]
Après avoir activé le mode debug de Prestashop, il ne s'agit pas du tout d'un problème du module mais à l'extension php Allow_url_fopen qui n'était pas activé. 
Concernant le fichier de log, en le créant effectivement il arrive à écrire dedans. 

Merci pour le coup de pouce ;)

**Comment by nenes25** [comment]
Bonjour,

Super merci pour votre retour !
C'est bizarre normalement j'avais un contournement pour ce cas, mais il ne semble donc pas marcher.
Je vais rajouter ce point dans la partie debug du module :smile:
