### ISSUE TITLE
reCaptcha on form contact always return the error "incorrect response to CAPTCHA challenge. Please try again"

### ISSUE THREAD

**Issue by leah68** [nenes25/eicaptcha#232]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

< 1.7

### Do you use a specific theme ?

We use our specific theme.

### Describe the bug

It seems that in the hookContactFormAccess $result->isSuccess() does not return anything so that we always pass in the condition if (! $result->isSuccess()).
Is this an API issue ?
Thanks in advance.

**Comment by Paul-88** [comment]
Hi,

See on your PHP config if Allow_url_fopen is enabled. 
For me, it's solved the problem
