### ISSUE TITLE
The modulo not save change

### ISSUE THREAD

**Issue by ddv1976** [nenes25/eicaptcha#234]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.5.x

### Do you use a specific theme ?

warehouse version 4.2.1

### Describe the bug

When I add the information to the fields, after saving, the changes are not saved, it does not allow selecting the type of captcha v2 or v3, it does not allow saving the recaptcha keys. the fields always permanent empty.

### Screenshots

https://i.imgur.com/Bp9Q2Bb.png
https://i.imgur.com/3cki91l.png

**Comment by nenes25** [comment]
Hello,

This error should be related with your hosting provider, the configuration form is really basic.
Could you please check if back office is well configured ( ie https enable everywhere for example ? )

Regards,
