### ISSUE TITLE
No show in form contact, form account onli in form newsletter

### ISSUE THREAD

**Issue by andres79** [nenes25/eicaptcha#235]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.8.x

### Eicaptcha version

2.3.x

### Do you use a specific theme ?

Warehouse 4.5.5.

### Describe the bug

Hello

I have a problem, Recaptcha is only showing in newsletter form, but not showing in contact form or registration form.

Can you help.

I hope to hear from you.

Thank you very much in advance.

**Comment by nenes25** [comment]
Hello,
Could you please provide an url so i can check ?
Regarding the contact form please be aware that it works only on default contact form of Prestashop.
Regards,

**Comment by andres79** [comment]
Hello

I understand, the contact form is from Elementor, although it says that it is from Prestashop.

The URL is cafecaminos.com

Thank you

**Comment by nenes25** [comment]
I confirm that you use the contact form in a non standard way.
You can check here, another user post a solution for the issue : https://github.com/nenes25/eicaptcha/issues/221#issuecomment-1129939889

Regards,
