### ISSUE TITLE
Can't set the captcha theme and language.

### ISSUE THREAD

**Issue by nicmorais** [nenes25/eicaptcha#236]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.7.x

### Eicaptcha version

2.3.x

### Do you use a specific theme ?

Classic 1.0.0

### Describe the bug

The "I'm not robot" label is in french, and the theme is not chaning to the light one. 

### Screenshots

![](https://i.imgur.com/hYknUC2.jpg)

### Additional context

I've also tried the "Force Captcha language" option. I just installed the 2.4.0 version of this module, but such version is not present in the Eicaptcha version combobox above.

**Comment by nenes25** [comment]
Hello,

Sorry for the very late reply.
I've checked on the last version ( 2.4.1 ) and no issue appears.
I'm able to force a language without issue, for example in the following screenshot i force the use of the swedish language in a french website.
![image](https://user-images.githubusercontent.com/7163132/230735590-a42e2de1-635a-4bf6-9854-be25b5953278.png)

I'll close this issue, feel free to reopen it if needed.

Regards,
