### ISSUE TITLE
 eicaptcha and custom registration and login forms

### ISSUE THREAD

**Issue by Fera** [nenes25/eicaptcha#237]
I have a custom theme with a modal window for login and registration. The module is not showing up there. I tried inserting it with code but then there is no validation. The form without the filled captcha is sent.
Is it possible to create some code that will be validated after pasting into any form?

**Comment by nenes25** [comment]
Hello,
If you want to personalize some forms it is possible as described in the blog post (in french ) https://www.h-hennes.fr/blog/2022/08/22/prestashop-ajouter-un-captcha-sur-les-formulaires-de-vos-modules/
But it will not work out of the box you will need do make some code modifications.

Regards,
