### ISSUE TITLE
customer-form.tpl verified only in '_PS_THEME_DIR_' and not in '_PS_PARENT_THEME_DIR_' too

### ISSUE THREAD

**Issue by HartLarsson** [nenes25/eicaptcha#242]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.8.x

### Eicaptcha version

2.4.x

### Do you use a specific theme ?

Warehouse 4.5.5

### Describe the bug

When you have a **childtheme** activated and you enable the captcha module chck the presence of the file:

`templates/customer/_partials/customer-form.tpl`

This create an error during verification of installation.

If a **childtheme** not have that tpl file , before give an error, must be checked also if in the **parenttheme** is present.
The error must appear only if in both; **child** and **parent** is not present the "templates/customer/_partials/customer-form.tpl" file

### Screenshots

![image](https://user-images.githubusercontent.com/16102074/211299601-107628dd-7022-470a-b414-a6545f5a10ec.png)

### Additional context

none

**Comment by nenes25** [comment]
Nice catch :+1:  , i'll check to fix this !
Thanks for the report.

Regards,

**Comment by nenes25** [comment]
The debugger have been upgraded to deal with this case.
And i also fix the same behavior for the newsletter module :smile: 
Thanks !
