### ISSUE TITLE
[enhancement]: Integrate Cloudflares Turnstile

### ISSUE THREAD

**Issue by Chrisi1321** [nenes25/eicaptcha#245]
**Check if your feature request exists**
 
- [ ] My feature request does not already exists

**Is your feature request related to a problem?**

No

**Describe the solution you'd like**

There is a nice description on the cloudflare website. It seems that is a not a huge effort to integrate it

https://developers.cloudflare.com/turnstile/

**Comment by nenes25** [comment]
Hello,
Thanks for the suggestion but such a module already exists :smile:
See https://github.com/Pixel-Open/prestashop-cloudflare-turnstile for example.

Regards
