### ISSUE TITLE
Registration check on prestashop 8.x

### ISSUE THREAD

**Issue by nenes25** [nenes25/eicaptcha#247]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

8.0.x

### Eicaptcha version

2.4.x

### Do you use a specific theme ?

Nope

### Describe the bug

Due to the fact that the registration have moved to a new controller on V8 , the check of the captcha seems not working anymore.
This must be fixed.

**Comment by nenes25** [comment]
This issue is more annoying than expected.
I think i'll make a new major version for Prestashop 8+ only with a new way of checking the customer registration form

**Comment by nenes25** [comment]
I'll first release the 2.4.2 version and think about this issue in the next one.

**Comment by nenes25** [comment]
A fix is already available on the dev branch in the future 2.4.5 version ( see : https://github.com/nenes25/eicaptcha/milestone/7 )

**Comment by futurowebpl** [comment]
Hello @nenes25 

When do you plan to release a version for Prestashop 8?

It seems to me that even after the changes you made, it still allows the registration form to pass without verification (version 2, version 3, it's hard to check whether anything is verified)
