### ISSUE TITLE
recaptcha doesn't work with google maps on the same page

### ISSUE THREAD

**Issue by narsil71** [nenes25/eicaptcha#25]
### Theme Warehouse 3.7.4 

I'm using eicaptcha on a custom contact form page built with Custom Contact Page v 1.2, where I can put a google map of my shop.
The captcha works fine on account creation page, but it doesn't appear on the contact form page.

Below the error showed on debug console:

Uncaught Error: ReCAPTCHA placeholder element must be an element or id
    at Object.Qr [as render] (recaptcha__it.js:393)
    at onloadCallback (contattaci:250)
    at recaptcha__it.js:397
    at Br (recaptcha__it.js:388)
    at recaptcha__it.js:397
    at recaptcha__it.js:408

If I disable google maps, recaptcha starts to work.

**Comment by nenes25** [comment]
Hello,
This error appears when the captcha div container is not present, it should be linked with your theme.

In order to correct this you have to add manually the code 
`<div id="captcha-box"></div>` where you want the captcha to be displayed.
Regards,

**Comment by nenes25** [comment]
Closed as no user feedback.
Please reopen if needed
