### ISSUE TITLE
V3 probleme ?

### ISSUE THREAD

**Issue by phil31** [nenes25/eicaptcha#252]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.8.8

### Eicaptcha version

2.4.2

### Do you use a specific theme ?

no standard theme

### Describe the bug

not working with google key V3 : no captcha for new user (not tested others case)

work if i put some V2 keys only

**Comment by nenes25** [comment]
Hello,

Can you provide an url ?
A new version should be release in the next weeks, i'll test again all the possibilities of the module.

Regards,

**Comment by phil31** [comment]
Hi,

 

Sorry i can’t provide an url for now because my site is in « maintenance mode » 

But it’s working anly if i set some V2 keys.

Prestashop 1.7.8.8

 

 

Thanks for your works !

Regards

 

 

De : Hervé H. ***@***.***> 
Envoyé : jeudi 13 avril 2023 21:05
À : nenes25/eicaptcha ***@***.***>
Cc : phil31 ***@***.***>; Author ***@***.***>
Objet : Re: [nenes25/eicaptcha] V3 probleme ? (Issue #252)

 

Hello,

Can you provide an url ?
A new version should be release in the next weeks, i'll test again all the possibilities of the module.

Regards,
