### ISSUE TITLE
Ooops cant install mudule

### ISSUE THREAD

**Issue by WebGF** [nenes25/eicaptcha#253]
Hello I am trying to install the module but i get a window saying oops, cant update.

I am doing the intalation trough the module manager selecting the module zip file.

It is a fresh prestashop instalation.

Please could you advise me?

PS: I am brazilian if my english is not clear let me know.

Bellow information:

prestashop 
Versão do PrestaShop: 1.7.8.0

Informação do servidor: Linux #1 SMP Wed Aug 24 21:31:23 UTC 2022 x86_64

Versão do software do servidor: LiteSpeed

Versão do PHP: 7.4.33

Limite de memória: 768M

Tempo máximo de execução: 300

Tamanho máximo de arquivo para o envio: 128M

**Comment by nenes25** [comment]
Hello,

In order to have a real error message could you please enable to debug mode and post it ?
Without it's pretty hard to find which issue occurs.

Regards,
