### ISSUE TITLE
Can't enable the module

### ISSUE THREAD

**Issue by pozen80** [nenes25/eicaptcha#254]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

< 1.7

### Eicaptcha version

2.4.x

### Do you use a specific theme ?

Ecolife

### Describe the bug

Error!
Impossibile enable il modulo eicaptcha. Impossibile installare l'override: Il metodo initContent nella classe AuthController è già stato annullato.

### Screenshots

![1](https://github.com/nenes25/eicaptcha/assets/135120886/f5ee93a2-30f5-41cd-8e76-9670bb20ec3e)

**Comment by nenes25** [comment]
Hello,

This issue is related to the fact that another module already override the same file than the module.
The next version will allow to use another way and to get rid of this error.
For now you'll need to fix this manually.

Regards,

**Comment by pozen80** [comment]
where can i find a guite to fix it manually? thanks

**Comment by nenes25** [comment]
Hello,

First rename the file **of the module** override/controller/AuthController.php to _AuthController.php ( with a underscore before )
After that you will be able to install the module.

Then open the content of this file and the content of the file override/controllers/front/AuthController.php.
You have to compare both and to merge the content of them to allow all the modules to works.
Unfortunately as i don't know with which module is the conflict i can't tell you exactly how to do.

Regards
