### ISSUE TITLE
Debug not working

### ISSUE THREAD

**Issue by manufourc** [nenes25/eicaptcha#259]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.7.x

### Eicaptcha version

2.4.x

### Do you use a specific theme ?

Customized PRS006 theme from [ThemeDelights](http://www.themedelights.com/)

### Describe the bug

ContextErrorException
Warning: file_put_contents(/var/www/vhosts/.../modules/eicaptcha/src/logs/debug.log): failed to open stream: No such file or directory in Debugger.php line 342

I think :
dirname(__FILE__) . '/logs/debug.log',

should be replaced by : 
_PS_MODULE_DIR_ . $this->module->name . '/logs/debug.log',

**Comment by nenes25** [comment]
This fix is released in v 2.4.5
