### ISSUE TITLE
How to install the module in Prestashop 1.6.1.13?

### ISSUE THREAD

**Issue by jorgearamuni** [nenes25/eicaptcha#26]
### Your prestashop version
1.6.1.13
### Eicaptcha Version
module for PS 1.6 and above
### Do you use a specific theme
no
### Issue description
I downloaded the zip file, and used the function ADD NEW MODULE in prestashop administration (Modules menu). I selected the zip file and sent it. But after that, the module does not appear in the modules list. After sending the module, what I have to do?

**Comment by jorgearamuni** [comment]
It seems that this module is not compatible with prestashop 1.6.1.13, since it does not appear in the modules list after sending it.

**Comment by nenes25** [comment]
Hello,
The problem seems to be related with your platform.
As i've tested with no problems on a fresh version 1.6.1.13 
![captcha-1-6-1-13](https://user-images.githubusercontent.com/7163132/36586588-ac6d7cd0-1882-11e8-9b6d-06167ccb46d4.JPG)
Regards,
Hervé

**Comment by DanGB1** [comment]
I Had the same problem.
After using the GUI to upload, it said it had installed it but didnt appear.
The only way to make it appear was to manually upload the module via ftp in the /modules dir. Then it worked fine. not had this issue before.

**Comment by nenes25** [comment]
Hello,

Have you download the last version from the release page ?
https://github.com/nenes25/eicaptcha/releases/tag/0.4.12

Regards,

**Comment by jafraco** [comment]
Do you have any version to prestashop 1.6.1.4?

I have the following problem:

![image](https://user-images.githubusercontent.com/36769839/36604194-62f0de06-1893-11e8-8ccc-62d6bb5fd961.png)

**Comment by nenes25** [comment]
Hello,

For the upload issue, an user seems to have the same problem and give a solution on PS forum : https://www.prestashop.com/forums/topic/442633-add-recaptcha-to-prestashop-version-16014-for-free/?do=findComment&comment=2686014

**Comment by nenes25** [comment]
@jafraco your problem is not related with this issue.
I guess you have downloaded the release v 2.0.2 for PS 17, please download the 0.4.x version.

Regards,

**Comment by jorgearamuni** [comment]
Thanks very much, Nenes25! I downloaded the version 0.4.12 and could upload it! I will try to configure it later, since I'm very busy now.
![image](https://user-images.githubusercontent.com/8009510/36606715-5686ad70-18a3-11e8-90b4-dac1d958223f.png)

**Comment by jorgearamuni** [comment]
I installed version 0.4.12 and tested it. Everything is OK!
Is this the latest version (for Prestashop 1.6.1.13)?

**Comment by nenes25** [comment]
Yes it is the latest version ... for now.
I'm planning a new release with a few improvments in the next days.

If everything is ok i close the issue.

Regards,

**Comment by jafraco** [comment]
Thank you, version 0.4.12 is installed in prestashop 1.6.1.4

**Comment by Premitium** [comment]
I cannot install the module version 0.4.13 to presta 1.6.1.5. It is downloaded but doesn't appear in the admin panel for installation. I've tried to remove the hyphen from the module name  also I moved the module in the modules folder manually still with no success. Where can I find the 0.4.12 version for download, please?
