### ISSUE TITLE
 "GDPR" checkbox does not appear in the contact page if the Eicaptcha module is activated (and send message button is inactive)

### ISSUE THREAD

**Issue by gouna15** [nenes25/eicaptcha#262]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.8.x

### Eicaptcha version

2.4.x

### Do you use a specific theme ?

I use the "BLCK" theme (based on prestarocket), its description can be found here : [BLCK Thème](https://www.arnaud-merigeau.fr/produit/theme-prestashop-1-7-responsive-blck/)

### Describe the bug

EDIT : It's OK on Chrome, Firefox and Edge

On Brave :
If the Eicaptcha module is activated on the Contact page, AND if the GDPR module is disabled on the Contact page, then the "GDPR" checkbox is displayed correctly, and it is therefore possible to validate the form.

If the Eicaptcha module is activated on the Contact page, AND if the GDPR module is activated on the Contact page, then the "GDPR" checkbox is not displayed, and it is impossible to validate the form.

### Screenshots

![Sans titre](https://github.com/nenes25/eicaptcha/assets/107960598/626871e2-ba04-4cbc-a397-2ebe7b79923b)

### Additional context

PS 1.7.8.10
Thème BLCK (base on prestarocket)

URL : [https://gounacreations.com/nous-contacter](url) (RGPD is disabled now)

**Comment by gouna15** [comment]
OK !

The culprit is the BRAVE browser.

The solution is to uncheck the “EasyList Cookie” option in the filter options.

Problem fixed.

**Comment by nenes25** [comment]
Thanks for your return :smile: , maybe this issue will help other users which may encounter the same issue as you !

Regards,
