### ISSUE TITLE
Captcha not working on prestashop 8.1

### ISSUE THREAD

**Issue by nandosendraa** [nenes25/eicaptcha#265]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

8.0.x

### Eicaptcha version

2.4.x

### Do you use a specific theme ?

The theme I've been used is ebusiness, I check it and there is all the hooks registered

### Describe the bug

In captcha v2 If I don't check the checkbox I'm not a robot and I press to register customer, should appear an error saying that you can't register without checking the checkbox but, no error appear and the customer can register

**Comment by nenes25** [comment]
Should be fix in next version, as you have opened another issue I close this one.
