### ISSUE TITLE
Not error displayed

### ISSUE THREAD

**Issue by nandosendraa** [nenes25/eicaptcha#269]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

8.1.x

### Eicaptcha version

2.5.x

### Do you use a specific theme ?

I use a theme called ebusiness

### Describe the bug

I've downladed your new version, but when I create an account without checking the recaptcha, no errors displayed, the web redirects to a blank page with the text not human.

**Comment by nenes25** [comment]
Hello,

Weird, with v2 ou v3 keys ?

Regards,

**Comment by nandosendraa** [comment]
I'm using v2 keys

**Comment by nenes25** [comment]
Hello,
I'm not abble to reproduce this issue.
As you can see in the following screencast.
![eicaptcha-register-form](https://github.com/nenes25/eicaptcha/assets/7163132/3e858019-2a14-463b-83ee-ccac4b78e75e)
If you already installed the previous version of the module have you applied the upgrade ?
You can also try to reinitialize it.

Regards,

**Comment by nandosendraa** [comment]
I've tried to reinitialize it and now the error is displayed, thanks!!!

**Comment by nenes25** [comment]
Great so i close this issue :smile:
