### ISSUE TITLE
Error ReCAPTCHA placeholder element must be empty

### ISSUE THREAD

**Issue by hey-FilipaSimao** [nenes25/eicaptcha#27]
### Your prestashop version 
1.6.1.0

### Eicaptcha Version
v0.4.3

### Do you use a specific theme 
Warehouse

### Issue description
Can you help me please? I have this error: 

Uncaught Error: ReCAPTCHA placeholder element must be empty
    at Object.Qr [as render] (VM5826 recaptcha__pt_pt.js:396)
    at onloadCallback (contacte-nos:1296)
    at VM5826 recaptcha__pt_pt.js:400
    at Br (VM5826 recaptcha__pt_pt.js:391)
    at VM5826 recaptcha__pt_pt.js:400
    at VM5826 recaptcha__pt_pt.js:411

**Comment by nenes25** [comment]
Hello,

The error message seems to well describe the issue.
Do you have a div an id="captcha-box" in your contact form page ?
Is this div empty ? ( If it's not the case, the error is linked to that )

By the way you use an old version of the module.
Please download the latest release for prestashop 1.6 ( 0.4.x ) from this page
https://github.com/nenes25/eicaptcha/releases 

Regards,

**Comment by hey-FilipaSimao** [comment]
Hello! 

I have a id and isn't empty. The id must be empty?
I install a new version (v0.4.11) and the error, in contact page, still there.

**Comment by nenes25** [comment]
Hello,

As told in my previous comment : 
Is this div empty ? ( If it's not the case, the error is linked to that )

You have to let this div empty, so the recaptcha lib will add dynamically the captcha inside it.

Please let me know if everything is ok after.

Regards,

**Comment by hey-FilipaSimao** [comment]
Hello, 
The div is empty and then is dynamically filled.

**Comment by nenes25** [comment]
So everthing is ok now ?
Otherwise what is the problem ?

**Comment by hey-FilipaSimao** [comment]
No, sorry. I think I misunderstood.
The div is filled when i'm in the page, I inspected. the reCaptcha is there but gives that error.

**Comment by nenes25** [comment]
Can you send me an url ?

**Comment by hey-FilipaSimao** [comment]
Here: [Kitess](https://kitess-clothing.com/contacte-nos)

Thanks!

**Comment by nenes25** [comment]
Have you made change in the module ?
The recaptcha library is loaded twice, that's why you have an error.

How are your js optimisations configured ?
In the last 1.6.1.x version it works well with the current configuration
![js-optimisations](https://user-images.githubusercontent.com/7163132/36670710-64a14246-1af9-11e8-8444-d7b8a2bef22d.JPG)

I have to try on a fresh 1.6.1.0 to check if it's related with your ps version

**Comment by hey-FilipaSimao** [comment]
I found the problem. I had "Move JavaScript to the end" activated. Now works because this option is disabled.
Thanks 👍 :)

**Comment by hey-FilipaSimao** [comment]
Sorry, another problem.
The recaptcha don't validate. We do the check and the message isn't send.

**Comment by hey-FilipaSimao** [comment]
Any new?

**Comment by nenes25** [comment]
Hello,

My dev web server is currently down, so i'm not able to check or correct anything.
I hope to fix this by the end of the week in order to check issues during the next one.

Regards,

**Comment by hey-FilipaSimao** [comment]
OK, I Wait. Thanks.

**Comment by zodit** [comment]
I had Prestashop 1.6.0.11 and it was doing the same bug (the reCaptcha was working, but the email was not sent, the form was stuck with filled fields, no submit, no refresh).

Then i removed the module and override, I updated to PS 1.6.1.18 (latest subversion today),  and reinstalled EiCaptcha. Now the form is submitted, but it is giving a generic error happening during the "sending" (i have the message in my language). Yet the message is not sent.

**Comment by hey-FilipaSimao** [comment]
Hello,

I tried add this but nothing... Doesn't work... 
```
<input type="text" name="url" value="" class="hidden" />
<input type="hidden" name="contactKey" value="{$contactKey}" />
```

**Comment by zodit** [comment]
Yes, your version (1.6.1.0) is older, and I am pretty sure it is not working for that reason (I had the same problem with my older version). Try to update PS to the latest subversion (1.6.1.18), they solved many bugs, and they finally supported PHP 7 (much faster, if you can use it in your server).
Don't worry, do a full backup of files and database, so you can revert back safely. Then, using the module 1 Click Update you can update in less than 10 minutes (set it to work for slow server, then check to NOT disable your modules, let it update default theme and mails, you can disable data and images backups as you did it manually already. All should work very fine, then remember to fix the contact form template, as i told before).

**Comment by hey-FilipaSimao** [comment]
I think I can't update the version...

**Comment by hey-FilipaSimao** [comment]
We have this module in another website, same version and it's works.

**Comment by zodit** [comment]
If you confirmed that PS 1.6.1.0 is working then i guess the problem is strictly related to the theme (i suspect it because you switched Javascript from bottom to the head of the page and it started working, so it could be some script error, you should debug it with your browser console... but I can't help you more from here. Anyway, in my general configuration i have all CCC enabled, and all is working).
May I ask you why you can't update PS? Have you done some custom code in the core? If you haven't, all should work fine. Then, perhaps your theme needs some bug fix, but this is another story :).

**Comment by hey-FilipaSimao** [comment]
I made a small change in the backoffice but the client has already changed her mind about this functionality, so it isn't important anymore.
This version's update would imply that the website would remain in maintenance and I'm not sure if that's what the client wants.

If I enable "Move JavaScript to the end" it  gives me the initial error.

**Comment by nenes25** [comment]
Hello,
The problem on your see may be linked with this issue #34 
The new release give you the ability to change the default selector directly from the admin side.
As you can see on the screenshot : 
<img src="https://www.h-hennes.fr/blog/wp-content/uploads/2018/02/captcha-configuration-avancee.jpg" />

**Comment by hey-FilipaSimao** [comment]
Is the new release compatible with my version of Prestashop?

**Comment by nenes25** [comment]
yes it's a release for all ps version > 1.4 and < 1.7

**Comment by nenes25** [comment]
https://github.com/nenes25/eicaptcha/releases/tag/0.4.13

**Comment by hey-FilipaSimao** [comment]
Hello, 

I installed the release 0.4.13 but the problem still there... The message isn't sent. 
I don't have any error in console.

**Comment by hey-FilipaSimao** [comment]
Can I do something else?

**Comment by zodit** [comment]
I think your only option is to take some time for maintenance, i could solve all my problems with older PS versions only updating, i had a PS 1.6.0 and also a very old PS 1.5.
Just take care of the override, if there is one already, do a backup, delete it, let EI captcha make it, then paste your old code and modify it manually with Ei Captcha functions, because i notice the automatic injection is failing inserting them.

**Comment by hey-FilipaSimao** [comment]
Can the problem be from theme I'm using? I'm not using the default.

**Comment by zodit** [comment]
It is possible, as i said earlier, it is strange that changing javascript loading order you get errors, there could be something wrong in the template. Anyway, the main problem of "Captcha working, but PS not sending the email" is something different. I had the same issue in my 2 PS. After update the mail was working, and I haven't changed the theme (also the PS 1.5 theme was working fine hopefully). I don't know why it worked, but I guess something changed in the way PS sends email.

**Comment by hey-FilipaSimao** [comment]
So I need update the PS... There is no other solution.

**Comment by zodit** [comment]
Yes, also, uninstall the module and reinstall it in the updated PS, i did it too for the "previously" PS 1.5, the module was installed but not working, then i resetted it with fresh installation and it worked.

**Comment by hey-FilipaSimao** [comment]
I'll try. Thanks!

**Comment by nenes25** [comment]
Hello,
Could you please update to the last release ?
https://github.com/nenes25/eicaptcha/releases/tag/0.4.14
It add a tools which check if the module is well installed ( for backend code )

Regards,

**Comment by hey-FilipaSimao** [comment]
Hello, 
I install the new release but the problem still there.

> Success 
> the module is compatible with your version
> the module is well registered in hook header
> the module is well registered in hook displayCustomerAccountForm
> the module is well registered in hook contactFormAccess
> Overrides are enabled on your website
> ContactController.php override exists
> ContactController.php override is present in class_index.php

> Aditionnal informations 
> Prestashop version 1.6.1.0
> Theme name warehouse
> Php version 5.6.34

**Comment by nenes25** [comment]
Well i'm afraid to be out of new ideas of where the problem come on your website.
If hooks are ok, and frontend is ok everything sould work.
