### ISSUE TITLE
[enhancement]: Hiden recaptca until is invalid?

### ISSUE THREAD

**Issue by sefirosweb** [nenes25/eicaptcha#270]
### Check if your feature request exists

- [X] My feature request does not already exists

### Is your feature request related to a problem?

No

### Describe the solution you'd like

To avoid dirtying the client "view" I would recommend hiding the repactcha unless the validation fails,

I have seen some websites that do it like this, they have it hidden but if any validation failure is detected then it is shown

**Comment by nenes25** [comment]
Hello,

Thanks for the suggestion.
If you use the v3 version you can simply hide the box using a simple css code 
Then no distraction for the user.
But I'm not sure that it is accepted in the term and conditions of the service.
So I'll not bundle this feature within this module.
Regards,
