### ISSUE TITLE
Create only 1 key on google site ?

### ISSUE THREAD

**Issue by defaliz** [nenes25/eicaptcha#272]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

1.7.8.x

### Eicaptcha version

2.5.x

### Do you use a specific theme ?

classic

### Describe the bug

Hi,
i've installed eicaptcha 2.5 on my prestashop 1.7.8 but this module ask for 2 keys (private and public)
but on google web site you can create only one key ? how can we configure this module ?
excuse my bad english
regards.

**Comment by nenes25** [comment]
Hello,

The link for the configuration is provided in the configuration page of the module in back office.
https://www.google.com/recaptcha/intro/index.html
Then click on the link V3 admin console to create your keys.
![image](https://github.com/nenes25/eicaptcha/assets/7163132/86e809d0-ea17-414b-9118-ad808a072125)

Regards,

**Comment by defaliz** [comment]
Merci beaucoup Hervé... c'était sous mon nez et n'ai pas vu le lien ! , j'utilisais le lien Entreprise
Thanks a lot Hervé, i didn't see the good link..., i used "entreprise" link...

**Comment by nenes25** [comment]
Parfait si vous avez trouvé :) 
Je ferme donc cette demande.

Pour la version enterprise je me suis noté de gérer ce point pour la prochaine version.

Cordialement,
Hervé
