### ISSUE TITLE
Captcha box not appear in contact form

### ISSUE THREAD

**Issue by jafraco** [nenes25/eicaptcha#28]
### Your prestashop version
1.6.1.4
### Eicaptcha Version
0.4.12
### Do you use a specific theme
theme1209 version 1.0
### Issue description
The module is installed and configured but captcha box not appear.

In account creation if work correctly.

**Comment by jafraco** [comment]
![image](https://user-images.githubusercontent.com/36769839/36621068-9ad08d74-18cc-11e8-967f-4f61dd7bbee7.png)

**Comment by jafraco** [comment]
![image](https://user-images.githubusercontent.com/36769839/36621093-b44e35e4-18cc-11e8-8629-7bb7033da79d.png)

**Comment by nenes25** [comment]
Hello,

Do you have a js error in the console ?
( F12 / console tab )

Regards,

**Comment by jafraco** [comment]
No, I don't have errors
![image](https://user-images.githubusercontent.com/36769839/36621468-85efa1d6-18ce-11e8-8efa-73fed7d2b242.png)

**Comment by mspann** [comment]
I am experiencing the same Issue. Captcha appears in Login widget but not in the contact form. There is a div id="captcha-box" under the contact form, but its empty. There's also a div id="captcha-box"  further up on the page in the login widget and its being displayed correctly.

**Comment by nenes25** [comment]
Hello,

Thanks for your feebacks, can you send me url of the concerned website ?

@mspann i guess you have found what is the problem, because the captcha-box is added before element with "submit" class. If there is more than on element an issue can appear.

https://github.com/nenes25/eicaptcha/blob/master/eicaptcha.php#L362

If it's linked with that, the next release will avoid this by giving you the possibility to define the selector in the administration.

Regards,

**Comment by mspann** [comment]
I have changed line 362 to $(".contact-form-box .submit").before and it was displayed correctly at the contact form page. However, even after validating the captcha I got a error message saying that the contact message could not be sent.
![grafik](https://user-images.githubusercontent.com/25685094/36630629-028a432c-196a-11e8-9a2d-8aa9c1952d2a.png)

**Comment by nenes25** [comment]
Can you send me an url, 
Are the captcha information being send through POST values of the form ?

**Comment by MarMolillo** [comment]
Same issue. I make the change that mspann comment.
Same result, captcha appears but same error and message don't send.
¿any suggestion?

**Comment by nenes25** [comment]
Hello,
Could you please update to the last release ?
https://github.com/nenes25/eicaptcha/releases/tag/0.4.14
It add a tools which check if the module is well installed ( for backend code )

Regards,

**Comment by thomark1** [comment]
Hello,
Well, the same problem here - not displaying captcha wher you visit the site as a guest. The captcha appears when the user is logged in though.

Regards,

**Comment by nenes25** [comment]
Hello @thomark1 ,
The version 0.4.14 only add a tool in administration which check if the module is well installed .
Can you check if everything is ok on your website. ( if it is a frontend problem it will not change anything )

Regards,

**Comment by thomark1** [comment]
Well,

It seems to be fine - no errors in the FO console. I checked with your checking tool and the installation is OK either. 

<div id="captcha-box'> is just empty when I'm not logged in. When I'm logged in I can see the captcha, but I cound not send the message. I used zodit's solution (adding 2 hidden fields before the submit ):
<input type="text" name="url" value="" class="hidden" />
<input type="hidden" name="contactKey" value="{$contactKey}" />

and it solved the problem with sending.

regards,

**Comment by nenes25** [comment]
Can you try @kazuyevon  solution, i guess you have several item with class "submit" when the customer is not loggued on your site.

**Comment by nenes25** [comment]
just a few comments before ^^

**Comment by thomark1** [comment]
I don't know how to insert this js query to get it working. I tried for a couple of ways, but always getting 500 ERROR in FO.

Regards,

**Comment by kazuyevon** [comment]
![admin-site](https://user-images.githubusercontent.com/12174847/37282253-0e2ff01e-25f4-11e8-86e1-c7ca467ef0e7.jpg)
![capture-script](https://user-images.githubusercontent.com/12174847/37282260-144d9c1c-25f4-11e8-8f95-f761957ca991.jpg)
Installer la version 0.4.14, ne s'affiche pas, il est bien présent puisque l'erreur "Merci de valider le captcha" apparait, j'espère que les screens vous aideront.

**Comment by thomark1** [comment]
Thank you, I understand what you mean, but I was not able to apply this :  
$(".contact-form-box .submit").before (I can't create a proper syntax)
line in eicaptcha.php file - the site crashed and returns 500 ERROR in FO.

Nonetheless I was able to resolve the problem by changing the selector class name (submit -> submit2) in proper template files and set the same class in captcha module configuration.

**Comment by tomgug** [comment]
Hi,
I have same problem on my site:

https://www.scontolo.net/it/contattaci

catpha-box is empty under inspection

![image](https://user-images.githubusercontent.com/22656453/37702316-6e10f01e-2cf2-11e8-9576-8fef59245b92.png)
![image](https://user-images.githubusercontent.com/22656453/37702326-721421f4-2cf2-11e8-90f2-3ab7351ff9eb.png)

**Comment by zodit** [comment]
Hello, I had to update another Prestashop, and I installed the latest module 0.4.14 (tested also 0.4.13), i found that the particular theme was breaking the javascripts (LeoTheme Fashion, i guess very old one, it was not loading JQuery and i had to fix the header.tpl). I really don't know the cause, but i solved switching off the "performance" parameters about Javascript, so: Smart Cache, compression, and move to the end of page. After this the eicaptcha is working fine, no loop that breaks <script> tags.

**Comment by tomgug** [comment]
unfortunately not works...

**Comment by oldlastman** [comment]
ok i'm ussing old leo theme
when i use registered user recaptcha works ok, but if i'm not logged .. not work

this theme has a lot of .submit classes on p elements
so i modify the div container of my submit button #submitMessage and add one specifc class = submit-recaptcha
then on module advanced configuration "Custom css selection contact form" i put .submit-recaptcha

and every thing looks work ok

**Comment by tauaje** [comment]
Saludos 
Tengo instalado Eicaptcha, se ve en formulario de registro y formulario de contacto, ¿ pero como puedo ponerlo en Newsletter popup
