### ISSUE TITLE
Move or hide Google reCAPTCHA badge

### ISSUE THREAD

**Issue by PaccoRobin** [nenes25/eicaptcha#280]
Is it possible to show the badge on the left side of the website? We already use a messaging service that has a badge on the right side. See attachement.
![recaptcha](https://github.com/nenes25/eicaptcha/assets/30149569/1ec6ed3d-bef9-4264-9127-917ce63f066b)

Or is it possible to hide the badge and reference to Google reCAPTCHA in the form that is displayed?

**Comment by nenes25** [comment]
Hello,

You can make this modification using css with something like this  :
.grecaptcha-badge { display:none }
This code can be added in your theme global css or you can override the module css into your theme.
As I'm not sure it's legal to do this, this code won't be included in the module code.

Regards,

**Comment by PaccoRobin** [comment]
It is allowed if you add this to the page where you use reCAPTCHA v3.

_This site is protected by reCAPTCHA and the [Google Privacy Policy](https://policies.google.com/privacy) and [Terms of Service](https://policies.google.com/terms) apply._

What if I want to display the badge on the left?

**Comment by nenes25** [comment]
OK great, in order to do so you can follow this tutorial : https://divimundo.com/en/blog/how-to-move-the-recaptcha-v3-badge-to-the-left/  (as recaptcha is platform agnostic )

Regards,
