### ISSUE TITLE
Not working with v3 and v2 on PS 1.7.8.x with template PRS098

### ISSUE THREAD

**Issue by JulFeraud** [nenes25/eicaptcha#282]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

< 1.7

### Eicaptcha version

2.5.x

### Do you use a specific theme ?

PRS098

### Describe the bug

L'action enable est impossible pour le module eicaptcha. Impossible d'installer la surcharge : Ce répertoire doit être modifiable

**Comment by nenes25** [comment]
Bonjour,

Je pense que vous avez mal rempli les champs de l'issue.
Car si votre version de prestashop est inférieure à 1.7 le module ne doit pas pouvoir s'installer.

Sinon concernant l'erreur que vous remontez elle est liée à votre configuration serveur et pas au fonctionnement du module.
Merci de contacter votre hébergeur afin d'ajouter les droits en écriture sur le dossier "override" de votre site.

Cordialement,
