### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by dogsmart** [nenes25/eicaptcha#29]
I'm running Prestashop 1.6.0.9

I Download the latest eicaptcha version 0.4.12

After the Installation i had on the Modules Page the following error:

[PrestaShop] Fatal error in module Module.php(1224) : eval()'d :
Can't use function return value in write context

Any Idea's?

**Comment by nenes25** [comment]
Hello,
Can you check your php version ?  ( via menu Advanced parameters / Configuration information )
It it's php 5.4 your issue should be linked with #14 , and will be fixed in next release.

Regards,

**Comment by dogsmart** [comment]
Hi there
I'm running PHP 5.2
How can i fix mit BO Modules now? Just delete the files in the server?

**Comment by nenes25** [comment]
Hello,
Waiting for the next release you juste have to apply the folowing commit : 
https://github.com/nenes25/eicaptcha/commit/53ab55e4778515c60f12a72f5d57d4c7fe671209
Regards,

**Comment by Hanibull** [comment]
Hi, I download the last version extract and renamed the zip folder and added to modules, but once i go to the admin/modules it dosen't appear on the list to be activate..
PrestaShop 1.6.1.7 - PHP 5.6.33  French lenguage,  Any Idea's? tks

**Comment by nenes25** [comment]
@Hanibull : téléchargez la release 0.4.12 depuis la page https://github.com/nenes25/eicaptcha/releases et installez le module depuis l'adminstration, ça devrait fonctionner.

**Comment by Hanibull** [comment]
Ok, tks now i have a non compatiblity issue PrestaShop 1.6.1.7when activated

**Comment by nenes25** [comment]
Can you give me a screenshot ?
Have you take the release https://github.com/nenes25/eicaptcha/releases/tag/0.4.12 ?

**Comment by Hanibull** [comment]
It works now! I don't know what happened.. tks a lot  !

**Comment by hyggli** [comment]
Hello I have this problem, any ideas? (1.7 prestashop, 5.6 php) 
![image](https://user-images.githubusercontent.com/37663630/37775437-39c6123e-2de3-11e8-905c-c5c0cb132609.png)

**Comment by nenes25** [comment]
Hello,
The error is self explained.

You have to install the module contact form before installing the module. ( as it depends on it )
Search it in the module list, it's a prestashop native module.

Regards,
