### ISSUE TITLE
Declare this module as a packagist package

### ISSUE THREAD

**Issue by Soullivaneuh** [nenes25/eicaptcha#3]
I'm using [composer/installers](https://github.com/composer/installers) package to insall prestashop package from `composer`.

It would be great if you can create a `package.json` file and publish proper versions of your module on [Packagist](https://packagist.org/).

I suggest this way:

```json
{
    "name": "nenes25/eicaptcha",
    "type": "prestashop-module",
    "require": {
        "composer/installers": "~1.0"
    }
}
```

The `prestashop-module` type is not abitrary, this is recognized by `composer/installers` package.

Regards.

**Comment by nenes25** [comment]
Hello,

Thanks for your suggestion, it is a good idea.
I'll update this asap.

Regards,

**Comment by nenes25** [comment]
Hello,

The module is now available on packagist : https://packagist.org/packages/nenes25/eicaptcha

Regards,
Hervé
