### ISSUE TITLE
Le module n'apparait pas en back office

### ISSUE THREAD

**Issue by vivi0103** [nenes25/eicaptcha#30]
### J'ai d'abord obtenu un message d'erreur en installant le module en zip via le back office. Pourtant après vérification via FTP le dossier eicaptcha a bien été envoyé dans le dossier modules. Je l'ai supprimé et l'ai replacé manuellement. Quelle que soit la méthode d'installation choisie, il n'apparait pas dans le back office donc impossible de le paramétrer. Merci pour votre aide.

**Comment by nenes25** [comment]
Bonjour,

Avez-vous bien : 
- télécharger la release du module depuis la page :  https://github.com/nenes25/eicaptcha/releases 
- installé le module contactform avant celui de captcha comme mentionné dans l'article  https://www.h-hennes.fr/blog/2017/07/11/module-catpcha-pour-prestashop-1-7/

Cordialement,

**Comment by vivi0103** [comment]
Bonjour,

Oups j’avais effectivement oublié l’installation du module formulaire de contact.
Ca fonctionne à présent !

Un grand merci pour votre disponibilité et votre bienveillance.
Bonne fin de journée !

Virginie

Le 26 févr. 2018 à 10:03, Hervé H. <notifications@github.com<mailto:notifications@github.com>> a écrit :


Bonjour,

Avez-vous bien :

  *   télécharger la release du module depuis la page : https://github.com/nenes25/eicaptcha/releases
  *   installé le module contactform avant celui de captcha comme mentionné dans l'article https://www.h-hennes.fr/blog/2017/07/11/module-catpcha-pour-prestashop-1-7/

Cordialement,

**Comment by nenes25** [comment]
Super , merci du retour je ferme donc le ticket.

Cordialement,
Hervé
