### ISSUE TITLE
Recapcha ne s'affiche pas sur la page d'identification.

### ISSUE THREAD

**Issue by GuillaumePEL** [nenes25/eicaptcha#303]
### Check if your issue exists

- [X] I confirm that i've search that my issue does not already exists

### Your prestashop version

< 1.7

### Eicaptcha version

2.5.x

### Do you use a specific theme ?

Classic theme

### Describe the bug

{"error":true,"message":"404 not found!"}

**Comment by GuillaumePEL** [comment]
PS 1.7.8.9
J'ai suivis les tutos... vérifiés les fichiers css ou php... rien. 
essayé de créer un custom.css comme indiqué sur le forum PS... rien.

Le recapcha fonctionne bien sur le formulaire de contact... mais ne s'affiche pas sur la page d'identification! 

https://boutiquepel.fr/fr/connexion?back=my-account

Le mode débugg ne remonte aucune erreur.

**Comment by GuillaumePEL** [comment]
Succès
Le module est compatible avec votre version de Prestashop
Le module "contactform" est installé
Le module est bien greffé sur le hook displayHeader
Le module est bien greffé sur le hook displayCustomerAccountForm
Le module est bien greffé sur le hook displayNewsletterRegistration
Le module est bien greffé sur le hook actionCustomerRegisterSubmitCaptcha
Le module est bien greffé sur le hook actionSubmitAccountBefore
Le module est bien greffé sur le hook actionContactFormSubmitBefore
Le module est bien greffé sur le hook actionNewsletterRegistrationBefore
Le module est bien greffé sur le hook actionAdminControllerSetMedia
Les surcharges sont activées sur le site
La surcharge du fichier AuthController.php existe
La surcharge du fichier contactform.php existe
La surcharge du fichier Authcontroller est présente dans le fichier class_index.php
Le hook displayCustomerAccountForm est présent dans le template du formulaire par défaut
La version du module ps_emailsubscription vous permets d'utiliser le captcha sur la newsletter
Informations complémentaires
Version de recaptcha : 2
Version de prestashop : 1.7.8.9
Nom du thème : classic
Version de php : 7.3.33
 

En cas d'erreur, merci d'ouvrir une demande avec les informations demandée à l'adresse : [github](https://github.com/nenes25/eicaptcha/issues)

**Comment by GuillaumePEL** [comment]
Bon, y a pas de recapcha sur la page d'ID.... 

J'avais installé plusieurs module de recapcha et dans la barre de recherche faut mettre recaPtcha et pas recapcha... 

En désactivant les autres modules.... miracle.

**Comment by nenes25** [comment]
Bonjour,

Le module n'est pas prévu pour s'afficher sur la page de login, mais sur le formulaire de création de compte uniquement.
On le vois bien sur cette page : https://boutiquepel.fr/fr/connexion?create_account=1 
En revanche il y'a un problème dans la saisie des clés recaptcha ou quelque chose qui rentre en conflit sur votre site.
On peut le voir dans la console d'erreur du navigateur.
![image](https://github.com/user-attachments/assets/e4e3aeff-efce-4d52-953c-3c0f0b4e2ba2)

Comme vous utilisez les clé V2, il faut vérifier que c'est bien ce type de clés que vous avez généré.

Cordialement

**Comment by GuillaumePEL** [comment]
Merci!
