### ISSUE TITLE
div captcha-box reste vide

### ISSUE THREAD

**Issue by Picoteur** [nenes25/eicaptcha#31]
Bonjour
Le js est bien présent dans le header et le div captcha-box est correctement créé mais reste désespérément vide.
Je n'ai pas d'autre submit sur la page pouvant parasiter la chose ni d'erreur js dans la console.
Une idée svp ?
Merci d'avance
Pierre

PS 1.5 - Theme spécifique mais les sélecteurs sont corrects - eicaptcha v0.4.12

**Comment by nenes25** [comment]
Bonjour,

Quelle version exacte de PS 1.5 ?
Effectivement je ne vois aucune erreur et rien ne s'affiche.

A priori vous n'êtes pas le seul à avoir ce problème, mais je n'ai pas encore réussi à identifier quelle est sa cause.

Cordialement,
Hervé

**Comment by Picoteur** [comment]
Bonjour Hervé
PS version 1.5.6.2. Si besoin d'aide pour débugguer, c'est possible. ;)

**Comment by Picoteur** [comment]
Du coup, j'ai fait autrement, sans votre module.
Si vous voulez que nous revoyons la chose ensemble sur cette version 1.5, dites le, je le remettrai en place sur un dev.
Merci
Pierre

**Comment by nenes25** [comment]
Bonjour Pierre,
Merci de votre retour, votre proposition m'intéresse car la version 1.5 de prestashop ne fonctionne plus sur mon serveur de développement ( elle n'est pas compatible avec mysql 5.7 )

Pouvez-vous me préciser quelle est votre infrastructure ?
Je n'aurais pas le temps dans l'immédiat mais dans les prochains jours éventuellement.

Cordialement,
Hervé

**Comment by nenes25** [comment]
A tester avec la dernière release 0.4.13 qui permet de mieux cibler l'élément ou ajouter le captcha

**Comment by addicte** [comment]
Bonjour,
J'ai essayé la dernière version sur 1.6.1.9 et 1.6.1.14 et j'ai le même problème.
La div se crée mais elle reste vide dans le formulaire de contact.
En revanche, le module fonctionne sur le formulaire de connexion.
Si ça peut vous aider .

Johan

**Comment by nenes25** [comment]
Duplicate of #28

**Comment by tomgug** [comment]
Hi,
I have same problem on my site:

https://www.scontolo.net/it/contattaci

catpha-box is empty under inspection

![image](https://user-images.githubusercontent.com/22656453/37701880-f2ab7c1a-2cf0-11e8-954b-b5a13c71da60.png)

![image](https://user-images.githubusercontent.com/22656453/37701910-0cc7d670-2cf1-11e8-8c41-1575e75a0083.png)
