### ISSUE TITLE
 Vous n'avez pas la permission de configurer ce module. 

### ISSUE THREAD

**Issue by Repitol** [nenes25/eicaptcha#35]
### Installation OK, mais configuration impossible (compte SuperAdmin)

J'ai essayé d'autres versions de eicaptcha, mais toujours pareil ou bien erreur après installation (que je peux corriger en supprimant le module par ftp et sa référence dans la Base de données)

**Comment by nenes25** [comment]
Bonjour,

Dans un premier temps merci d'installer la dernière release pour prestashop 1.6 : 
https://github.com/nenes25/eicaptcha/releases/tag/0.4.12

Si le problème persiste : 
- pouvez-vous me fournir une capture d'écran du problème.
- pouvez-vous également vérifier les droits de vos dossiers

Cordialement,

**Comment by Repitol** [comment]
là j'ai une erreur PHP avec cette version et plus accès aux modules de PS
[PrestaShop] Fatal error in module file :/var/www/clients/client1/web46/web/modules/eicaptcha/eicaptcha.php:
Can't use function return value in write context

**Comment by nenes25** [comment]
Duplicate of #14

**Comment by Repitol** [comment]
Eh bien en appliquant le commit, je me retrouve à la situation initiale malheureusement
"Vous n'avez pas la permission de configurer ce module."
![image 2018-03-01 a 13 45 59](https://user-images.githubusercontent.com/25481741/36845446-110e50fa-1d57-11e8-9f6c-b37ab754cc3b.jpg)

**Comment by nenes25** [comment]
ok donc c'est bien un problème inédit.
Pouvez-vous me donner une capture de l'écran des autorisations de votre utilisateur ?

**Comment by Repitol** [comment]
euh... SuperAdmin
je n'ai pas d'info supplémentaire à copier/coller
le profil n'apparait pas si je me connecte avec mon compte et que j'édite mon profil
![image 2018-03-01 a 14 09 22](https://user-images.githubusercontent.com/25481741/36846240-2fa84680-1d5a-11e8-98fc-742fbdef9414.jpg)

**Comment by Repitol** [comment]
je vais tenter d'accéder aux paramètres du module en utilisant un nouveau compte SuperAdmin

**Comment by Repitol** [comment]
Idem avec un autre compte SuperAdmin
![image 2018-03-01 a 14 13 12](https://user-images.githubusercontent.com/25481741/36846404-bf4862f2-1d5a-11e8-87d1-38c449b5fe7b.jpg)

**Comment by nenes25** [comment]
Désolé je n'arrive pas à reproduire votre problème.
Est-ce que vous avez la possibilité de tester le module sur une autre instance ?

**Comment by Repitol** [comment]
Bonjour,
j'ai pu l'installer sur un autre site en effet et le configurer mais il est perméable au spam. je reçois quand-même des spams venant de boites mail.ru (texte en russe donc) depuis le formulaire de contact Prestashop (version 1.6.1.11)
J'ai pourtant paramétré avec recaptcha V2 qui fonctionne, je ne sais pas comment le spammeur arrive à passer le filtrage.
Pour le site en question, je ne vois pas ce qui 'empêche de le configurer. Ça reste un vrai mystère.
Merci

**Comment by Repitol** [comment]
AARGH !
j'ai voulu mettre à jour Eicaptcha en mettant la dernière version pour prestashop 1.6 (en raison de spam qui passe)
et j'ai l'erreur suivante
[PrestaShop] Fatal error in module file :/var/www/clients/client1/web84/web/controllers/admin/AdminModulesController.php:
Undefined class constant 'CACHE_FILE_MODULES_LIST'

Je retire le dossier et le module via PhPMyadmin. Mais si je peux avoir un fix pour arriver à l'installer... Merci.

**Comment by nenes25** [comment]
Essayez de videz le cache, pour corriger ce problème.
Je ne l'ai jamais eut.

**Comment by Repitol** [comment]
oui, bizarre. Je n'ai plus accès à rien quand j'ai ce message d'erreur, même en vidant le cache directement en FTP. Il me faut passer par la BDD et supprimer le module, puis supprimer le fichier class_index.php du dossier cache pour que ça reparte.

**Comment by nenes25** [comment]
J'ai réussi à obtenir votre erreur avec le module lorsque j'ai tenté une déinstallation ( avec suppression des fichiers qui a échoué ).
Par contre il m'a suffit ensuite de réinstaller le module pour que tout fonctionne à nouveau.

**Comment by Repitol** [comment]
Bonjour Hervé
en dépit de l'installation de eicaptcha sur certains site PS où j'ai pu
l'installer (version PS 1.6)
je reçois pas mal de message en russe qui arrive à passer par le formulaire
de contact
pourtant le captcha est bien présent et si je fais un test, il bloque bien
le message si je ne remplis pas le captcha.
Une idée de la façon dont ces messages de *@mail.ru arrivent à passer le
filtre ?
Merci

**Comment by nenes25** [comment]
Bonjour,
Dans ce cas votre problème est plutôt le suivant  #36 
Est-ce qu'on peut fermer cette issue  ou le problème est toujours présent ?

Je l'ai constaté sur un site aussi, mais je n'ai pas encore identifié la source
Une solution serait de rajouter une exclusion de certaines adresses emails
