### ISSUE TITLE
ROBOT still sending messages!

### ISSUE THREAD

**Issue by jorgearamuni** [nenes25/eicaptcha#36]
### Your prestashop version
1.6.1.13
### Eicaptcha Version
0.4.12
### Do you use a specific theme
no
### Issue description
The module is installed OK, and I tested it OK. If I try sending a message without checking the field, an error message appears. Everything seems to be working right, but a russian robot is still sending messages (I received them today)! Please give a look at my form: https://xadrezshop.com/xadrezshop/entrar-em-contato-conosco

**Comment by nenes25** [comment]
I've tried again and it works well, so the module is not well installed on your side.
As the contactform controller is overrided, please remove file cache/class_index.php to force the override if it is not the case.

**Comment by jorgearamuni** [comment]
Thanks nenes25! I removed the file class_index.php, but with javascript disabled the message can still be sent. After removing the file, there is something else I need to do?

**Comment by nenes25** [comment]
You can check in directory overrides/controller/front of prestashop if the content of my override is well displayed : https://github.com/nenes25/eicaptcha/blob/master/override/controllers/front/ContactController.php

**Comment by jorgearamuni** [comment]
The file ContactController.php wasn't in the folder overrides/controller/front. There was only an index.php. I created one ContactController.php file, like the one in your link, and sent it to the folder. But the same happen: when javascript is disabled, the captcha does not appear, and the message can be sent.
I remember that the form I use is not the original from Prestashop. The files have some modification, to correct some design issues with the original form. Maybe if I delete all files from the form folder, and replace with the originals, and install eicptcha again, the problem can be solved. What do you think?

**Comment by matasskarzauskas** [comment]
Buy some security software for your server that regulates incoming traffic and actions.

**Comment by jorgearamuni** [comment]
Thanks matasskarzauskas! Can you suggest one?

**Comment by nenes25** [comment]
@jorgearamuni  ok it explains why it's not working, my module will only work with default prestashop behavior.
I cannot adapt it to every spécific ones.

So please go back the initial one and check if everything is ok

**Comment by fredviv** [comment]
Bonjour, It's the same for me, if we disable the javascript, the message can be send. 
And it's the original contact form, i don't change that. Do you have an idea ? (  i remove file cache/class_index.php ), i upload the file contactcontrol.php like you said (  in directory overrides/controller/front of prestashop if the content of my override is well displayed : https://github.com/nenes25/eicaptcha/blob/master/override/controllers/front/ContactController.php)  but nothing work. Thanks to your help.
Prestashop : 1.6.1.5 / eicaptcha : 0.4.12

**Comment by bocianl** [comment]
Same here :( PS 1.6.X disabled JS and spammer still can send information.

**Comment by jorgearamuni** [comment]
nenes25, can eicaptcha work in the new prestashop 1.7.3? I'm thinking of upgrading my store to the new version.

**Comment by nenes25** [comment]
@jorgearamuni  yes you can use the releases 2.x for ps 1.7

**Comment by jorgearamuni** [comment]
@nenes25 Even with javascript disabled, the 2.x releases will work OK for ps 1.7?

**Comment by nenes25** [comment]
yes it works well with ps 1.7,
But it also works for PS 1.6 , it should be related with something on your website.
You can test one of my prestashop demo  : https://web.h-hennes.fr/dev/prestashop/prestashop_1-6-1-18/fr/nous-contacter

**Comment by bocianl** [comment]
Yes, I can confirm. This is related to override/controllers/front/ContactController.php - when this file exist and all caches are clear module works even if JS is disabled.

**Comment by jorgearamuni** [comment]
@bocianl I didn't clear the cache. Maybe this is the reason of eicptcha not working with disabled javascript. I'll try clearing the cache and post hear the result.

**Comment by nenes25** [comment]
Hello,
Could you please update to the last release ?
https://github.com/nenes25/eicaptcha/releases/tag/0.4.14
It add a tools which check if the module is well installed ( for backend code )

Regards,

**Comment by fredviv** [comment]
Thanks you Nenes25, it's ok for me, i disable and delete the module and i re install and it's work perfectly even the javascript disable. Message don't send anymore. Thanks

**Comment by nenes25** [comment]
@jorgearamuni Can you try to remove completely the module and to install last release.
as @fredviv says it must work

Regards

**Comment by jorgearamuni** [comment]
@nenes25 Thanks for the tip! I'll try removing the module and installing 0.4.14. Will post the results hear.

**Comment by DrupaListo-com** [comment]
Hi, the real problem seems to be that this module is not overriding the contact page controller well enough.

To quote Vekia from https://www.prestashop.com/forums/topic/465606-spam-from-contact-us-form/

"module doesnt block form from submit, it only adds recaptcha, but if bot sent before the form, it will be able to sent it even with this module.

it is necessary to change controllers. this is the only way to protect form."

What I think he means is this:
seeing this eicaptcha module override/controllers/front/ContactController.php file and the default prestashop 1.6 same file...

I see that the eicaptcha module works entirely on js level, while some spam bots work by directly submitting the form's $_POST to the presta controller.

If recaptcha can't be used for php-level spam defence this module needs a 2nd spam detection mode of some kind. If recaptch can be used - we should use it - extend it.

**Comment by nenes25** [comment]
Hello @DrupaListo-com, 

You quote an old message from 2015.
As you can see in the repository, the module well override the contactform controller : 
https://github.com/nenes25/eicaptcha/blob/master/override/controllers/front/ContactController.php 
Please check what you say before posting ;)

Regards,

**Comment by DrupaListo-com** [comment]
Hi, @nenes25 can you please point me to the exact file and line(s) of code where your module defends against a raw $_POST request aimed at the contact page's form submit url?

Merely adding initCursedPage() and checkAccess() in the controller override seems to not be doing a back-end defense.

I might be wrong, so pls point me to the code line where this happens.
Thanks.

**Comment by DrupaListo-com** [comment]
@nenes25 
PS. I see 2 methods in your override: initCursedPage and checkAccess. I also see those in classes/controller/Controller.php and classes/controller/FrontController.php

So maybe the magic happens because those two methods you used there.
The easiest thing to do is to test the module in real world and I will get back to you.

**Comment by DrupaListo-com** [comment]
.. saw hookContactFormAccess in main module .php file. This module indeed should be defending against a pure $_POST based spam attack/submit.... looking good. Seems indeed the 2015 post by Vekia is now outdated.

**Comment by nenes25** [comment]
Hello,

The process is the following : 

- In the contactform controller is an override of the function checkAccess()
- This function call a custom hook where the module is hooked.
- Depending of the validation of the captcha content it returns true or false.
- So based on the behaviour of the function run in Controller class 
https://github.com/PrestaShop/PrestaShop/blob/1.6.1.x/classes/controller/Controller.php#L168
If the content is not validated nothing will be processed

Regards,

**Comment by DrupaListo-com** [comment]
Thanks! Before my 1st comment above, I checked superficially if similar things happen and it was not very obvious on first glance, then I got deeper into the code and indeed you did it great!

So I guess the current issue can be closed?

1. Code looks very good.
2. I installed, tested and the contact form captcha works OK - stops submit when checkbox not clicked, and allows it when all checked.

**Comment by nbexiga** [comment]
HI
i am having an error after submit the contact form... 
it validates the captcha but does not send message.
i am using prestashop 1.7.3 and the module updated to the last version.
can you kindly help?
thanks
![captchaerrorwhensendind](https://user-images.githubusercontent.com/34128424/38731774-9df56d90-3f13-11e8-99b2-9970dd3b0d49.JPG)
