### ISSUE TITLE
Probleme recaptcha

### ISSUE THREAD

**Issue by djomobil** [nenes25/eicaptcha#37]
## Your prestashop version
prestashop > 1.7

### Eicaptcha Version
2.0.2
### Do you use a specific theme
Martinlupe
### Issue description

Le recaptcha s'affiche bien, pas de probleme de se cote la, Cependant il n'est pas necessaire de confirmer le recaptcha le message s'envoie quand meme.

Merci probleme resolu avec l'issue#16 
-- Mise en place du module avec l'option debug activer
-- Probleme resolu sans rien faire (Magie?)

Merci quand meme

**Comment by nenes25** [comment]
Merci de votre retour je ferme donc l issue.
Le seul changement de la version que vous avez téléchargé est l'ajout de logs.
Je suppose donc que le module n était pas installé correctement.
