### ISSUE TITLE
[PrestaShop] Fatal error in module file: Module.php(1242)

### ISSUE THREAD

**Issue by sting5** [nenes25/eicaptcha#38]
### After unzipping the archive into the "modules" folder, I receive this error:
[PrestaShop] Fatal error in module file :/home/nanodemo/domains/inovatyvus.lt/public_html/classes/module/Module.php(1242) : eval()'d code:
Can't use function return value in write context

In Prestashop forums it's written that this error is being produced when trying to install modules, made for version 1.7, when having shop v 1.6.xx.
Tried all the versions 0.4.10/0.4.11/0.4.12 from Github depository, all produce the same error. Any ideas?

**Comment by nenes25** [comment]
Hello,
Can you check your PHP version ?
See #14

**Comment by sting5** [comment]
Hi,
Yes, might be the case - my PHP server version is 5.4 - should I change to 5.6 (like suggested in other thread)?

**Comment by nenes25** [comment]
No it's not needed, i'll release a new version which will fix this today.
So I close the issue as it's the same as #14 

Regards,

**Comment by sting5** [comment]
Hi - thanks, close this thread and waiting for the update!
