### ISSUE TITLE
Can't install - Fatal error (2794)

### ISSUE THREAD

**Issue by leo7baez** [nenes25/eicaptcha#39]
### Your prestashop version
PS 1.6.1.6
### Eicaptcha Version
0.4.13
### Do you use a specific theme
Amaltea 1.0
### Issue description
I'd like to try this fantastic module because need to update captcha to V2. I added to modules but can't install it. This is the error:

**[PrestaShop] Fatal error in module file :/home/movilpla/public_html/classes/module/Module.php(2794) : eval()'d code:
require_once(): Failed opening required '/home/movilpla/public_html/classes/module/../../../modules/recaptcha/lib/recaptchalib.php' (include_path='/home/movilpla/public_html/tools/htmlpurifier/standalone:.:/opt/alt/php55/usr/share/pear:/opt/alt/php55/usr/share/php')**

Also another captcha before maybe let some junk files, I uninstalled and removed it, but one captcha still appears on contact form in my site https://www.movilplanet.eu

Please somebody or creator can help me? Congratulations, very good joob and thanks!

**Comment by nenes25** [comment]
Hello,
I don't know which version your are using but it's not 0.4.13 as the error is linked to path which was in an older version.
Please download and try the latest release for PS 1.6 
https://github.com/nenes25/eicaptcha/releases/tag/0.4.13

**Comment by leo7baez** [comment]
Hello nene25,
Many thanks for your kindly response!
Finally I got uninstall junk files from older version, now I could install it and it seems it works propertly.
Yes, I was already trying last version, but problem were that junk files.
Best regards,
leo

**Comment by nenes25** [comment]
OK great thanks for the feedback.
So i close this issue.
Regards,
Hervé
