### ISSUE TITLE
contact form does not send emails

### ISSUE THREAD

**Issue by mcelotti** [nenes25/eicaptcha#42]
### Your prestashop version
1.6.0.9

### Eicaptcha Version
0.4.14

### Do you use a specific theme
No, default theme

### Issue description
After installing the plugin the contact form does not send messages. Captcha works fine though.
Check module installation says:  
1- the module is not registered in hook header
2- no class_index.php found

For n.1: what should I do?
For n.2: I deleted previous "class_index.php" file as suggested but it's not automatically recreated. I tried disabling/cleaning cache but with no luck.

Thanks,
Marco

**Comment by nenes25** [comment]
Hello,
Try to reset the module to fix the hook.
Otherwise you can manually add the module in the hook through the "position" page.

Regards,

**Comment by mcelotti** [comment]
Hi Nenes, 
unfortunately I did several reset/reinstall and tried the manual hook (displayHeader) but nothing changes.
These are the hooks:
![image](https://user-images.githubusercontent.com/3830092/37272975-969056a4-25d8-11e8-8027-a70937233d99.png)

**Comment by nenes25** [comment]
In back office it seems good.
Maybe a front office issue, do you have any js erros on the contact page ?

**Comment by mcelotti** [comment]
No, console is clean, with "preserve log" I get only this: 
Navigated to http://...  (the "http://..." is the address of my contact-page)
The XHR to check reCAPTCHA work as expected.
