### ISSUE TITLE
After adding eicaptcha, module Alerts stopped sending emails

### ISSUE THREAD

**Issue by sting5** [nenes25/eicaptcha#43]
PS v. 1.6.1.5
Module version 0.4.11
Theme name: Transformer

Hi again,

I've been using this for over a month, and noticed an issue with module sending alert messages to administrators - after eicaptcha was installed, we do not receive emails notifying about new orders and products running out of stock (which are sent by alerts module).

**Eicaptcha settings at the moment:**
Enable Captcha for contact form:
Enabled

Enable Captcha for account creation:

Disabled
Force Captcha language:

Theme:
Light

**Comment by nenes25** [comment]
Hello,

Please check your php errors or your junk mail directory it seems simply impossible.
As they are not linked in anyway.
The mailalerts module use backend hooks and not the same as the module.

**Comment by sting5** [comment]
Hi again,

thank You for a prompt reply - I have identical thoughts..! Neither changes in controller, nor the php files in eicaptcha module has anything to do with mailalert module. I've checked spam catalogue for emails, nothing there. That's why I've wrote here - because as soon as the module's disabled, I start getting both spam and mailalert emails again. I'll check for PHP errors in admin module in the evening and will update the thread.

**Comment by sting5** [comment]
Hi again,
PHP is ok. Don't know how or why, but as soon as emails about new orders start coming into the email, spam emails flow as well. Need some more time to find the reason, but might be the problem of our hosting service provider or something else. Please close the thread as solved for now, I will send more information when things clear up.

**Comment by nenes25** [comment]
OK thanks for the feedback, i close the issue.
