### ISSUE TITLE
Error: the module is not registered in hook header

### ISSUE THREAD

**Issue by Nikodemsky** [nenes25/eicaptcha#45]
### Your prestashop version
1.6.1.18
### Eicaptcha Version
0.4.14
### Do you use a specific theme
Yes: https://livedemo00.template-help.com/prestashop_45426
### Issue description
On one of my installations i'm getting error with module check: "the module is not registered in hook header" - thing is, that eicaptcha is listed normally on positions in displayCustomerAccountForm and displayHeader hooks, am i missing something here?

**Comment by nenes25** [comment]
I may be a false issue. ( As hook "header" was the old name of the hook "displayHeader" )
Did the module works properly ?

**Comment by Zaurelien** [comment]
Same error message for me in the back office, when I try to send a message via contact form, I got the message "Please validate the captcha". But its not showing up anywhere in the contact page. 
I've checked the source code, and the div captcha-box is empty.

**Comment by Nikodemsky** [comment]
Might be false issue in my case, recaptcha shows and works properly(at least from what i see). Just thought i should mention it.

**Comment by nenes25** [comment]
yes, thanks, i'll see for updating the verification script for this hook

**Comment by DrupaListo-com** [comment]
too lazy to provide a PR, but at least I outlined the steps. HTH

**Comment by nenes25** [comment]
Lol , i'm working on prestashop for years so i already know for updates but thanks.

I will see for update, but this part of the code is just used to detect and explain potential issues.

**Comment by DrupaListo-com** [comment]
yep, lol, sorry. This improvement is rather minor and the module works perfectly anyways.

**Comment by iSung951** [comment]
Hi, I had the same prob...
The captcha in front-office isn't working and say "ERREUR pour le propriétaire du site : Type de clé non valide"
Through the back-office it say "Errors: the module is not registered in hook header"
Any help?..

**Comment by FilipMielczarek** [comment]
> Same error message for me in the back office, when I try to send a message via contact form, I got the message "Please validate the captcha". But its not showing up anywhere in the contact page.
> I've checked the source code, and the div captcha-box is empty.

I know it's been a while, but did you manage to fix this problem? I am facing exactly the same sittuation.

**Comment by HartLarsson** [comment]
PS 1.7.6.7
Theme Warehouse 4.3.7
PHP 7.2
Module 2.4.1 (dev)

i have the same check error:

- the module is not registered in hook **displayHeader**

**Comment by 10tribu** [comment]
Hello, I had the same problem
The captcha in front-office isn't working and say "ERREUR pour le propriétaire du site : Type de clé non valide" the back-office it say "Errors: the module is not registered in hook header"
Any help please
