### ISSUE TITLE
Not working on order history

### ISSUE THREAD

**Issue by 007good** [nenes25/eicaptcha#46]
### Issue description : Work perfectly on contact form but do not working on order history page, do not show the recaptcha but still wait few second and reply not human !

![capture d ecran 2018-03-14 a 17 32 00](https://user-images.githubusercontent.com/37377805/37416277-a6c4fea4-27ad-11e8-8896-b26f2a4ee450.png)

![capture d ecran 2018-03-14 a 17 32 56](https://user-images.githubusercontent.com/37377805/37416331-c6782b0e-27ad-11e8-98db-5514afad4d45.png)

**Comment by nenes25** [comment]
Bonjour,
Le module n'est pas prévu pour fonctionner sur la page d'historique de commandes.
C'est donc normal qu'il ne fonctionne pas.

**Comment by 007good** [comment]
Ok... Si il ne fonctionnait pas cela ne serait pas un gros soucis. Mais la il bloque carrement l'envoi du message puisqu'il attends le Captcha !

**Comment by nenes25** [comment]
Je ne vois pas comment c'est possible.
Comme vous pouvez le voir https://github.com/nenes25/eicaptcha/blob/master/eicaptcha.php#L337 le script recaptcha est uniquement ajouté sur la page du formulaire de contact, et sur la page des produits.
La page de l'historique n'est pas impactée.
Le seul point qui pourrait entrainer ça serait si le js du module est dans le fichier js global minifié de la page. Est-ce que vous pouvez vérifier ?
