### ISSUE TITLE
Blank contact form after install + Errors when trying to uninstall

### ISSUE THREAD

**Issue by gdvgc** [nenes25/eicaptcha#47]
Hi,

### Your prestashop version
1.6.1.4

### Eicaptcha Version
0.4.14

### Do you use a specific theme
specialdev212-bootstrap / modified ...

### Issue description
**blank Contact page after module install.**
Contact page tpl has been modified to include a Google Map (iframe) and some text.
ContactController is also overriden by the FormMaker module.

Module deactivation doesn't help.

**When trying to uninstall i get the following error :** 
[PrestaShop] Fatal error in module file :/path[...]/htdocs/classes/module/Module.php:
Uncaught exception 'ReflectionException' with message 'Class ContactControllerOverrideOriginal_remove5aaa387f3689a does not exist' in /path[...]/htdocs/classes/module/Module.php:2944 
Stack trace: 
#0 /path[...]/htdocs/classes/module/Module.php(2944): ReflectionClass->__construct('ContactControll...') 
#1 /path[...]/htdocs/classes/module/Module.php(2749): ModuleCore->removeOverride('ContactControll...') 
#2 /path[...]/htdocs/classes/module/Module.php(647): ModuleCore->uninstallOverrides() 
#3 /path[...]/htdocs/modules/eicaptcha/eicaptcha.php(76): ModuleCore->uninstall() 
#4 /path[...]/htdocs/controllers/admin/AdminModulesController.php(681): EiCaptcha->uninstall() 
#5 /path[...]/htdocs/

The module won't uninstall.

Built-in installation checkup says everything is ok :
> Success
> 
>     the module is compatible with your version
>     the module is well registered in hook header
>     the module is well registered in hook displayCustomerAccountForm
>     the module is well registered in hook contactFormAccess
>     Overrides are enabled on your website
>     ContactController.php override exists
>     ContactController.php override is present in class_index.php
> 
> Aditionnal informations
> 
>     Prestashop version 1.6.1.4
>     Theme name specialdev212-bootstrap
>     Php version 5.6.31-1+0~20170711121957.3+jessie~1.gbp94bb71

Do you have any idea on how i could at least get the contact page running again ? Or at best, with the module working ?

Thanks anyway for sharing your work !

**Comment by gdvgc** [comment]
Hi,

deletion of override/controllers/front/ContactController.php restored the contact page and the captcha is working.

I didn't re-check the uninstallation process yet.

Thanks again.

Guillaume

**Comment by nenes25** [comment]
Hello,
Thanks for the report, it should be linked with this pull request. https://github.com/nenes25/eicaptcha/pull/44 and It'll be corrected in next release.
