### ISSUE TITLE
don't compare index.php?controller=order

### ISSUE THREAD

**Issue by microsoul** [nenes25/eicaptcha#48]
### 

### Do you use a specific theme

in checkout registration form dont compare captcha

**Comment by nenes25** [comment]
Hello,

I don't understand the issue.
Please give additionnal information

Regards,

**Comment by microsoul** [comment]
when you are not registered and the products is in the cart.
and you checkout from the cart
a customer can be added.

**Comment by eramirezprotec** [comment]
Solution [here](https://github.com/nenes25/eicaptcha/issues/124#issuecomment-710041812).
