### ISSUE TITLE
Cant install the module

### ISSUE THREAD

**Issue by MetalSniper** [nenes25/eicaptcha#50]
### Your prestashop version
1.7.2
### Eicaptcha Version
2.03 - 2.04
### Do you use a specific theme
Pos_Aboss
### Issue description
Can't install the module, it just gives me a 500 error, i can install every other module just fine. Is just this one that gives me the problem.

**Comment by nenes25** [comment]
Hello,

Have you installed the contactform module before ?
If you display error what is the message ?

Regards,

**Comment by MetalSniper** [comment]
Hello, well what i did at the end was upload the folder via FTP and then
installed it. I really don't know what the problem was but i was able to
solve it. rthank you

2018-03-20 10:15 GMT-06:00 Hervé H. <notifications@github.com>:

**Comment by nenes25** [comment]
OK thanks, so i close the issue.
