### ISSUE TITLE
Fresh instal presta 1.7.3 and module EIcaptchta 2.0.4 - error contacform.php override does not exists

### ISSUE THREAD

**Issue by Kerami82** [nenes25/eicaptcha#51]
### Your prestashop version
1.7.3
### Eicaptcha Version
2.0.4
### Do you use a specific theme
no - only default
### Issue description
When I check "Check module installation" i got Errors:  "contacform.php override does not exists
"
When I check file on the server there is a file in folder overrride/modules/contactform with

```
<?php
class ContactformOverride extends Contactform
{
    public function sendMessage() {
       Hook::exec('actionContactFormSubmitBefore');
       if ( !sizeof($this->context->controller->errors)) {
           parent::sendMessage();
       }
    }
}
```

Is there all OK?

**Comment by nenes25** [comment]
It may be a false positive.
Does the module works well with js disabled ?

Regards,

**Comment by Kerami82** [comment]
Ok. I check this. It works ok without javascript.

**Comment by Webmaster2xeral** [comment]
Hi, i have the same problem but on Prestashop version 1.7.2.5.
I fix the problem when i change in folder overrride/modules/contactform the file "conta**t**cform.php" for "contacform.php" i think a "t" letter is lost, can be?

**Comment by nenes25** [comment]
Hi,
This is a really weird behaviour.
I really don't know from where it comes.

Regards,
