### ISSUE TITLE
Contact form with recaptcha on cms page

### ISSUE THREAD

**Issue by tomi02** [nenes25/eicaptcha#52]
1.7.2.2 - Your prestashop version
2.0.4 - Eicaptcha Version
classic/modified - Do you use a specific theme
Issue description
Hi
I put the contact form on the cms page in the following way:
/themes/classic/templates/cms/page.tpl
I added:
```
{if $ cms.id == 8}
      {widget name = "contactform"}
{/} If
```
id == 8 - id cms with contact form
 
/themes/classic/modules/contactform/views/templates/widget/contactform.tpl

`<form action="{$urls.pages.contact}" method="post" {if $contact.allow_file_upload}enctype="multipart/form-data"{/if}>`

I exchange for: 

```
{if isset ($ cms) && $ cms.id == 8}
      <form action = "{$ link-> getCMSLink (8)}" method = "post" {if $ contact.allow_file_upload} enctype = "multipart / form-data" {/ if}>
} Else {
      <form action = "{$ urls.pages.contact}" method = "post" {if $ contact.allow_file_upload} enctype = "multipart / form-data" {/ if}>
{/} If
```

But unfortunately the recaptcha is not displayed in the contact form on the cms page.
Is there any possibility that eicaptcha would also work on the cms page?

**Comment by nenes25** [comment]
Hello,

In order to make it work with your implementation, you need to edit the line : https://github.com/nenes25/eicaptcha/blob/17/eicaptcha.php#L314
and to add 
`` || $this->context->controller instanceof CmsController``

So the specific js will be loaded in cms page too.

Regards,

**Comment by tomi02** [comment]
Hello
Thank you for your answer.
I added to the eicaptcha.php
` //Add Content box to contact form page in order to display captcha
if ( $this->context->controller instanceof ContactController
|| $this->context->controller instanceof CmsController
&& Configuration::get('CAPTCHA_ENABLE_CONTACT') == 1)`

On the cms page, the head section has been added
`<link rel="stylesheet" href="http://localhost/11/modules/eicaptcha/views/css/eicaptcha.css" type="text/css" media="all">`

It has not been added
` <script type="text/javascript">
            //Recaptcha CallBack Function
            var onloadCallback = function() {grecaptcha.render("captcha-box", {"theme" : "light", "sitekey" : "6Ldv3EsUAAAAACjUJxxxxxxxxxxxx"});};
            </script><script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit&hl=" async defer></script>`

In body section was added only
`<div id="captcha-box"></div> `
It has not been added
`<div id="captcha-box"><div style="width: 304px; height: 78px;"><div><iframe src="https://www.google.com/recaptcha/api2/anchor?k=6Ldv ......`

So the recaptcha window did not appear on the cms page.

**Comment by nenes25** [comment]
OK great if it works :-)
So i close the issue 

Regards,
