### ISSUE TITLE
How can I install it for product comments in Prestashop 1.7.X?

### ISSUE THREAD

**Issue by Wuala** [nenes25/eicaptcha#54]
### Your prestashop version
1.7.3.0
### Eicaptcha Version
2.0.4
### Do you use a specific theme
Venas
### Issue description
Hi,

I have installed it, and looks like is working fine, like I have read in another comment, when I check the module appears the error "contacform.php override does not exists", but it is working ok.

What I need now, is to install it for product comments, I tried with your install notes for that, but these notes are for 1.6, in 1.7 doesn't appears that folders.

Thanks in advance!

**Comment by nenes25** [comment]
Hello,

I'm sorry but this functionnality is no more avalaible for PS 1.7 
As the module is not packaged in default prestashop package.
It is not planed yet to do this.

Regards,
Hervé
