### ISSUE TITLE
Add release for Prestashop 1.4

### ISSUE THREAD

**Issue by pgrimaud** [nenes25/eicaptcha#57]
### Your prestashop version
1.4.8.2

### Eicaptcha Version
0.3.1

### Do you use a specific theme
No

### Issue description

Hello,

First, thanks for this awesome module!

Since March 31, 2018, Google forced upgrade to reCAPTCHA v2.

Here, 3 lines of the changelog : 
 - V 0.3.0 - 2015-01-20 : Option pour passer sur l'API V2 sur le formulaire de contact // Possibility to use API V2 for the contact form
-  **V 0.3.1 - 2015-01-22 : Gestion de l'API V2 pour le formulaire de création de compte // API V2 for account creation**
 - V 0.4.0 - 2015-02-12 : /!\ Compatible Prestashop > 1.5., API (Re)Captcha V2

The last version compatible with Prestashop 1.4 is the 0.3.1. I think it could be interesting to add a release from the commit ac0dadc1f87e03cec3c005b1115b45db011ee549 in the release page.

What do you think about it?

p.s. I manually cloned the repo, checkout to ac0dadc1f87e03cec3c005b1115b45db011ee549 and added the module with the code of this commit to my Prestashop 1.4. Everything is working perfectly, with reCAPTCHA v2 API.

**Comment by nenes25** [comment]
Hello,
Thanks for the suggestion, a new release have been added for ps 1.4

Regards,

**Comment by pgrimaud** [comment]
@nenes25 Great, thanks !
