### ISSUE TITLE
contacform.php override does not exists

### ISSUE THREAD

**Issue by jyves47** [nenes25/eicaptcha#58]
Prestashop version : **1.7.2.1**

Eicaptcha Version : **2.0.4**

Utilisez-vous un thème spécifique ? **Non**

**_Description :_**

Quand j’essaie d’envoyer le formulaire de contact j’obtiens le message suivant :
« An error occurred while sending the message, please try again. » (message non traduit par la même occasion ;-))

Dans les paramètres avancés du module j’ai ceci en error :
« contacform.php override does not exists »

Et dans la log :
2018-04-06 13:13:05: Captcha soumis avec succès
2018-04-06 13:13:12: Merci de valider le captcha
2018-04-06 13:13:12: Réponse recaptcha Array
(
[0] => missing-input-response
)
2018-04-06 13:13:25: Captcha soumis avec succès

Pouvez-vous m’aider ? Merci

**Comment by lemusa** [comment]
I have the same issue. Captcha loads and accepts input but form does not send email. "An error occurred while sending the message, please try again."
![captcha issue](https://user-images.githubusercontent.com/162462/38455885-2b758362-3ad2-11e8-89f1-97eba39aacbe.jpg)

**Comment by Jeremie32** [comment]
Hello,
thanks a lot for this module.
Same issue here.
Version de PrestaShop : 1.7.2.2
Eicaptcha Version : 2.0.4
![image](https://user-images.githubusercontent.com/38226442/38517385-1d8c409c-3c3a-11e8-8c0e-adf84550c0e6.png)

**Comment by Picoteur** [comment]
Bonjour à tous
Il semblerait que la mise à jour du module formulaire de contact de la v3.0 à la v4.0 génère ce message d'erreur. J'avais le même souci d'envoi d'email impossible mais ne l'ai plus depuis un retour à la v3.0.
Quelqu'un pour confirmer ?

[english short version]
Try downgrading contactform from v4.0 to v3.0 and everything should be ok

Merci
Pierre
Version de PrestaShop : 1.7.2.5
Eicaptcha Version : 2.0.4

**Comment by nenes25** [comment]
Bonjour Pierre,
Votre solution n'est pas une option.
La version 0.3 n'est pas faite pour prestashop 1.7 et elle ne fait que vérifier le captcha en ajax et n'a donc aucun effet si le javascript est désactivé.

**Comment by nenes25** [comment]
Please check in issue #59 
The override message error is a false positive related to a wrong path.
The real error is that the message is not send and is related with the module contactform
