### ISSUE TITLE
Not effective

### ISSUE THREAD

**Issue by marcochiesi** [nenes25/eicaptcha#6]
Hi there,
I decided to test this Prestashop addon, as it seems it's the only free plugin integrating Google Nocaptcha Recaptcha.
While apparently working as expected, unfortunately it's not effective in fighting spam. That's because the recaptcha integration is made through ajax and not upon form submission. So it's sufficient to disable javascript to be able to bypass the captcha validation. Of course spam bots totally ignore javascript and ajax, so they are able to send spam as if no captcha was present.

**Comment by nenes25** [comment]
Hi,
Thanks for your feedback.
I'll check this asap.
I'm planning to do a new version for PS > 1.7 , i'll include your notices for it.

Regards,
Hervé

**Comment by enumag** [comment]
I noticed this issue as well. However I need it for PS 1.6.

**Comment by olivier-at-doric** [comment]
Just adding my voice for PS1.6. The module seems to work properly for humans, but still receiving spam through the contact form.

**Comment by drzraf** [comment]
This module is not implemented.
The "recaptcha_check_answer" from the recaptcha lib would need to be call at least once in order to check the captcha value.
Otherwise spammer just disable the captcha server-side, trigger a POST and submit the spam successfully (what happens currently)

**Comment by drzraf** [comment]
http://forge.prestashop.com/browse/PSCFV-6677

**Comment by nenes25** [comment]
Hi,

Your fix seems to be great.
Can you do a pull request ?

I'll check for other places to make it works like in the contact form.
Regards,

**Comment by drzraf** [comment]
PR #7

**Comment by nenes25** [comment]
Thanks it's merged ;-)
