### ISSUE TITLE
Fatal error when trying to install.

### ISSUE THREAD

**Issue by Zalito** [nenes25/eicaptcha#63]
### Your prestashop version
1.6.1.12
### Eicaptcha Version
0.4.14
### Do you use a specific theme
Amaltea - From WebEmpresa
### Issue description
I can upload the module without problems, but when i try to install it, i get this error....

[PrestaShop] Fatal error in module file :[...]/public_html/classes/module/Module.php(2794) : eval()'d code:
require_once(): Failed opening required '[...]/public_html/classes/module/../../../modules/recaptcha/lib/recaptchalib.php' (include_path='[...]/public_html/tools/htmlpurifier/standalone:.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php')

**Comment by nenes25** [comment]
Hello,

Do you download the last version from the release page ?
What is your php version ?

Regards,

**Comment by Zalito** [comment]
Yes, i have downloaded the last version!

Versión de cPanel | 70.0 (build 23)
Versión de Apache | 2.4.33
Versión PHP | 5.6.30
Versión de MySQL | 10.1.31-MariaDB-cll-lve

**Comment by nenes25** [comment]
that's the good one weird.
Can you uninstall it and remove file, then try again.
And clean the cache ?

Regards,

**Comment by Zalito** [comment]
Hi! Had no luck trying that. Any other idea? Thanks!

**Comment by EspinoLeandro** [comment]
Hi! I have the same problem, i download https://github.com/nenes25/eicaptcha/releases/download/0.4.14/eicaptcha.zip and when I try to install in prestashop I get this error
[PrestaShop] Fatal error in module file :/home2/blizzard/public_html/classes/module/Module.php(2794) : eval()'d code:
require_once(): Failed opening required '/home2/blizzard/public_html/classes/module/../../../modules/recaptcha/lib/recaptchalib.php' (include_path='/home2/blizzard/public_html/tools/htmlpurifier/standalone:.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php')
