### ISSUE TITLE
Eicaptcha seems to work but error message when pressing send

### ISSUE THREAD

**Issue by baggen78** [nenes25/eicaptcha#65]
### Your prestashop version
1.7.2.4

### Eicaptcha Version
2.0.3

### Do you use a specific theme
Classic

### Issue description

Captcha seems to work but when im pressing send i get the following error message and no message shows up in backend.

Strange thing is that module and messages where working fine for me when i installed it a couple of months ago and i havent touched anything to my knowledge and now its not working.

Best regards 

![image](https://user-images.githubusercontent.com/39280415/40021733-fcfe1074-57c5-11e8-9349-d8d35ed56bd9.png)

**Comment by nenes25** [comment]
you have to take this one , the link you provide will not work as it's the old template.
https://github.com/PrestaShop/PrestaShop/blob/1.7.3.x/themes/classic/modules/contactform/views/templates/widget/contactform.tpl

**Comment by baggen78** [comment]
Ok, im running 1.7.2.4 though, i tried it but i am afraid still same problem.

Used this path also: \themes\classic\modules\contactform\views\templates\widget\contactform.tpl

**Comment by baggen78** [comment]
If i inactivate the module i can send messages again, but when activating same stuff is back.

**Comment by nenes25** [comment]
Can you give me your version of the module contactform ?
Have you tried to update it ?

**Comment by bormil66** [comment]
I have the same error in my presta shop ( 1.7.4.2)

**Comment by bormil66** [comment]
I've downloaded file proposed under the link https://github.com/PrestaShop/PrestaShop/blob/1.7.4.x/themes/classic/modules/contactform/views/templates/widget/contactform.tpl

and this I compared my original presta shop tpl file with the  file from the download link and they are similar !
