### ISSUE TITLE
Ei Captcha not appearing in registration account!

### ISSUE THREAD

**Issue by Nimstery** [nenes25/eicaptcha#66]
### Your prestashop version
1.7.3.2
### Eicaptcha Version
2.0.4
### Do you use a specific theme
Yes, TechOne https://themeforest.net/item/techone-modern-prestashop-theme/20383869
### Issue description

After installing Ei Captcha everything is working fine in the contact form, I can see the captcha screen and if I input it correctly I can send messages, when I go to the register screen nothing appears there if I have the captcha active, besides if I try to register it tells me that the captcha is incorrect but no box appears. Can you help me please? thank you so much

**Comment by Nimstery** [comment]
Already try to check all the files but no luck....the only problem is that the captcha box does not appear, but somehow works cause it tells me that the captcha is incorrect...well it is since i didnt click anything :)

**Comment by nenes25** [comment]
Can you give me your website url ?
Do you see any javascript error on the contact page ?

**Comment by Nimstery** [comment]
Yes I can, www.CoolChip.net. Do you want me to enable captcha for register
form? It's now disabled cause if enabled users are unable to register
because it says captcha is not correct. But it's working in contact form.
No java errors...no error at all.

A quarta, 23/05/2018, 09:53, Hervé H. <notifications@github.com> escreveu:

**Comment by Nimstery** [comment]
Anyone?

**Comment by nenes25** [comment]
Hi,

Can you check if the hook "DisplayCustomerAccountForm" is well implemented in your theme ?
You should see something like this in your theme file : themes/THEMENAME/templates/customer/_partials/customer-form.tpl

``{$hook_create_account_form nofilter}``

Regards,

**Comment by nenes25** [comment]
And is the module well hooked on this hook ?
You can check how the field is added in https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/customer/_partials/customer-form.tpl

Do not forget to clear the cache to refresh the templates.

Regards,

**Comment by Nimstery** [comment]
It is working, thank you so much! By the way can you tell me how can I put it on the right just on top of submit button instead of middle? Thank you!

**Comment by nenes25** [comment]
If you want to do this : 
![image](https://user-images.githubusercontent.com/7163132/40767584-34a2ceda-64b3-11e8-8867-9ab7396cf71c.png)
Change the class of the parent container to md-12, anb add a float:right on the div captcha-box

Regards,
