### ISSUE TITLE
Debug Errors  contacform.php override does not exists

### ISSUE THREAD

**Issue by bibidinu** [nenes25/eicaptcha#67]
### Your prestashop version 

1.7.3.3

### Eicaptcha Version

2.0.4

### Do you use a specific theme

prestacrea creamakeup

### Issue description

On debug i have this error 

Errors 
contacform.php override does not exists 

how to fix ?

**Comment by nenes25** [comment]
Hi,
Is the module working well
It's a false positive detection which will be corrected in the next relase.

Regards,

**Comment by HartLarsson** [comment]
PS 1.7.6.7 - v2.0.4 same false positive

**Comment by nenes25** [comment]
Fixed since 2.0.7
