### ISSUE TITLE
Erreur : An error occurred while sending the message, please try again

### ISSUE THREAD

**Issue by Kamduras** [nenes25/eicaptcha#68]
### Your prestashop version
1.7.2.4 

### Eicaptcha Version
2.0.4

### Do you use a specific theme
No

### Issue description
Lorsque j'essais d'envoyer un message par le formulaire de contact, j'ai ce message d'erreur : An error occurred while sending the message, please try again.

Pourtant dans les log d'eicaptcha, tout a l'air ok 

`2018-06-09 14:11:30: Captcha soumis avec succès
2018-06-09 14:27:47: Captcha soumis avec succès
`

Merci d'avance.

**Comment by nenes25** [comment]
Bonjour,
Je pense que c'est un doublon de celui-ci #59 
Merci de regarder si cela corrige votre problème.
