### ISSUE TITLE
An error occurred while sending the message

### ISSUE THREAD

**Issue by byLoConte** [nenes25/eicaptcha#69]
### Your prestashop version
PS v.1.7.2.5
### Eicaptcha Version
v.2.0.4 & Contact Form Module v.4.1.1
### Do you use a specific theme
Leo Mimy for PS 1.7.x
### Issue description
Hi There,
Our system uses the SMTP sending method without problems.
When we try to make a submission of the form we find the following message:
- An error occurred while sending the message, please try again.

When we look at the event log, it is as if it was sent correctly:
- 2018-06-11 11:56:05: Captcha submited with success
- 2018-06-12 12:00:32: Captcha submited with success

Thanks in advanced :)

**Comment by nenes25** [comment]
duplicate of #72
