### ISSUE TITLE
Erreur 500 sur création de compte

### ISSUE THREAD

**Issue by Guillawme** [nenes25/eicaptcha#70]
### Your prestashop version
1.7.3.3
### Eicaptcha Version
last b17
### Do you use a specific theme
creagarden
### Issue description
Tout d'abord merci pour ce module ! 👍 
Le module fonctionne parfaitement bien sur la page contact, en revanche provoque une erreur 500 sur la page de création de compte : /connexion?create_account=1
L'erreur 500 disparaît si je sélectionne "Non" pour "Activer pour la création de compte"

**Comment by nenes25** [comment]
Bonjour,

J'ai pas mal de remontées d'erreur sur la version 1.7.3.3 sur laquelle je n'ai pas encore testé le module.
Je vais regarder cela et je vous tiens au courant.

**Comment by nenes25** [comment]
La pull request #71 devrait corriger ce problème
Je vais prévoir une nouvelle release dans les prochains jours.

**Comment by Guillawme** [comment]
C'est parfait ! Merci 👍
