### ISSUE TITLE
Une erreur s'est produite pendant l'envoi du message

### ISSUE THREAD

**Issue by byLoConte** [nenes25/eicaptcha#72]
### Your prestashop version
1.7.2.5
### Eicaptcha Version
v.2.0.4 & Contact Form Module v.4.1.1
### Do you use a specific theme
Leo Mimy pour PS 1.7.x
### Issue description
Bonjour,
Notre système utilise la méthode d'envoi SMTP sans problèmes.
Lorsque nous essayons de faire une soumission du formulaire de contact, nous trouvons le message suivant:

     Une erreur est survenue lors de l'envoi du message, veuillez réessayer.

Lorsque nous regardons le journal des événements, c'est comme s'il était envoyé correctement:

     2018-06-11 11:56:05: Captcha soumis avec succès
     2018-06-12 12:00:32: Captcha soumis avec succès

Merci d'avance :)

**Comment by nenes25** [comment]
Bonjour,
Merci de regarder le ticket suivant #59 , le problème est sans doute lié.
Il faut mettre à jour le module contactform

Cordialement,
