### ISSUE TITLE
Send to a friend is not working with eicapthcha

### ISSUE THREAD

**Issue by SuperKariO** [nenes25/eicaptcha#75]
### Issue description
- Installed the module as usual from the back office
- After installation verified it is working with contact us form. (not used for registration)
- Copied the two files as instructed (https://github.com/nenes25/eicaptcha/blob/master/install-sendtoafriend.md) and verified the files was really copied
- Opening a product and clicking the "Send to a friend" link opens a popup
- After filling the popup fields and checking the captcha nothing happens when clicking the Send button
Additional issue
- A: If the product has no combinations clicking the cancel button in the popup window changes the product view so that it is not possible to add the product to cart AND gives a text telling the product is not available in current combination (note! product has no combinations
- B: If the product has combinations clicking the cancel button closes the popup and the product is shown normally
- In both A and B the product is shown normally if the popup is closed with top right corner (X)

If mandatory fields are not filled or the captcha is not checked normal error messages are shown.

**Comment by nenes25** [comment]
Hi,
This feature will be removed from next version.
( Not well implemented as js based only )

Regards,
