### ISSUE TITLE
captcha only loads when I've logged in

### ISSUE THREAD

**Issue by Ingdanielolivera** [nenes25/eicaptcha#76]
### Your prestashop version
1.6.1.6
### Eicaptcha Version
0.4.14
### Issue description

the problem is that the captcha only loads well when I have started secion otherwise does not load

additional of this still validate the captcha does not send the message

**Comment by Fera** [comment]
I have the same problem (Prestashop 1.6.1.20, eicaptcha 0.4.14) 
Captcha only loads  when I've logged in. For not register in code is <div id="captcha-box"></div> and this div is empty :-(

**Comment by nenes25** [comment]
Hi,
Sorry i'm unable to reproduce this behaviour.
I've tested with same configuration and everything works well.
Do you use a specific theme ?
Regards,

**Comment by EnzoSparacino** [comment]
I encountered this problem. It was related to a thirdy part module that inhibited access to the site for the b2b.
Inside Chrome developer tools in the section, check that eicaptcha-ajax.php does not go into redirect 302.
