### ISSUE TITLE
captcha property error under smarty in contact form

### ISSUE THREAD

**Issue by fgarganese** [nenes25/eicaptcha#78]
### Your prestashop version
1.6.0.14
### Eicaptcha Version
0.4.14
### Do you use a specific theme
No, just some little changes to the basic default-bootstrap
### Issue description
There is an error message displaying contact form, reporting a smarty error on captcha properties.
The error persists also deleting the cache or disabling it.
Here is the screenshot:
![captcha_smarty_error](https://user-images.githubusercontent.com/42323216/44005071-6a5d8576-9e6d-11e8-95f0-d3f507066134.jpg)

**Comment by fgarganese** [comment]
Hi,
Yes I did, because I started installing an old version.
I restored the original contact-form.tpl and now all it's perfect!
Thank you very much and all the best

**Comment by nenes25** [comment]
OK great, so i close the issue ;)
Regards,
