### ISSUE TITLE
recaptcha box!

### ISSUE THREAD

**Issue by hossisa** [nenes25/eicaptcha#79]
hi
i have a big problem with my account creation form!
the submit button is hide under the recaptcha box!
p.s :it works perfectly on mobile devices but its not working properly on desktop pc!
i attached the photo the way that it should be and the one with problem!
i'm amateur so plz explain as easy as possible!
the green button is missing!
eicaptha , latest version
presta 1.6
![the way it is](https://user-images.githubusercontent.com/44140707/46919294-2ed7ed80-cfea-11e8-9d3c-dfce03a20008.png)
![the way it should be](https://user-images.githubusercontent.com/44140707/46919296-2f708400-cfea-11e8-9bec-9344186f66bb.png)

**Comment by nenes25** [comment]
Hi,
This errors is related by the fact that the module was not tested with rtl languages.
You just have to adapt the css file to make the div #captcha-box float to left instead of right.

Regards,
