### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by megamurmulis** [nenes25/eicaptcha#8]
**1.** Generates failure message during install:
Problem: In function `install()` - missing "!" before `$this->registerHook('contactFormAccess')`
Solution: add missing `!`..

---
**2.** Configuration form does not display saved values (and shows notices about missing keys if display_errors=true)
Problem: in `renderForm()` - missing code that would set key `fields_value` in `HelperForm()`.
Solution: add missing code:

```
	$helper->tpl_vars = array(
		'fields_value' => array(
			'CAPTCHA_PUBLIC_KEY'     => Configuration::get('CAPTCHA_PUBLIC_KEY',          Tools::getValue('CAPTCHA_PUBLIC_KEY')),
			'CAPTCHA_PRIVATE_KEY'    => Configuration::get('CAPTCHA_PRIVATE_KEY',         Tools::getValue('CAPTCHA_PRIVATE_KEY')),
			'CAPTCHA_FORCE_LANG'     => Configuration::get('CAPTCHA_FORCE_LANG',          Tools::getValue('CAPTCHA_FORCE_LANG')),
			'CAPTCHA_ENABLE_ACCOUNT' => (int)Configuration::get('CAPTCHA_ENABLE_ACCOUNT', (int)Tools::getValue('CAPTCHA_ENABLE_ACCOUNT')),
			'CAPTCHA_ENABLE_CONTACT' => (int)Configuration::get('CAPTCHA_ENABLE_CONTACT', (int)Tools::getValue('CAPTCHA_ENABLE_CONTACT')),
			'CAPTCHA_THEME'          => (int)Configuration::get('CAPTCHA_THEME',          (int)Tools::getValue('CAPTCHA_THEME')),
		),
		..
```

---
**3.** add note that code requires PHP directive `allow_url_fopen = On`

---
**4.** (optional) Rename field titles to be more in line with google's own metodology - add `(..)`;
Also swap those 2 fields, so matches order given by https://www.google.com/recaptcha/admin (helps avoid confusion when users copy-paste values):
```
"Captcha public key"   => "Captcha public key (Site key)"
"Captcha private key"  => "Captcha private key (Secret key)"
```
---
**5.** (optional) Given that Composer isn't always available - add note about manually downloading `recaptcha-master.zip` ( https://github.com/google/recaptcha/ ), extracting `src` to module dir, and changing loader code: 
```
//require_once(__DIR__ . '/vendor/autoload.php');
require_once(__DIR__ .'/src/autoload.php');
```
---

**Comment by ajankuv** [comment]
[Sun May 28 12:15:52.923838 2017] [:error] [pid 29782] [client iphere:28396] PHP Warning:  require_once(/var/www/sitehere/modules/eicaptcha/src/autoload.php): failed to open stream: No such file or directory in /var/www/sitehere/modules/eicaptcha/eicaptcha.php on line 366, referer: https://sitehere.com/contact-us
[Sun May 28 12:15:52.923887 2017] [:error] [pid 29782] [client iphere:28396] PHP Fatal error:  require_once(): Failed opening required '/var/www/sitehere/modules/eicaptcha/vendor/autoload.php' (include_path='/var/www/sitehere/tools/htmlpurifier/standalone:.:/usr/share/php:/usr/share/pear') in /var/www/sitehere/modules/eicaptcha/eicaptcha.php on line 366, referer: https://sitehere.com/contact-us

example of the error before this switch. @megamurmulis I owe you a beer 👍  worked like a charm.

NOTE: Most prestashop users won't be using compose. May want to add an FAQ for this.

**Comment by nenes25** [comment]
Hello,

All of these issues seems to be related with last merge request.
https://github.com/nenes25/eicaptcha/pull/7 
I've not reviewed them enough, i'll check this asap.

**Comment by nenes25** [comment]
The last fixes should have correct all of these issues.
To correct the lack of composer files in the clone, i've updated readme and create a release which have all the necessary files.

Regards,
