### ISSUE TITLE
Impossible d'installer le module !

### ISSUE THREAD

**Issue by albanBCM** [nenes25/eicaptcha#80]
### Your prestashop version
1.7.4.3
### Eicaptcha Version
2.0.4
### Do you use a specific theme
mrcoffee version 1.0.0 Conçu par TemplatesOcean
### Issue description
J'ai tout d'abord essayé d'installer le module via le backoffice et j'ai eu un message d'erreur. Je suis du coup passé par le ftp. Dans ces deux cas je n'arrive pas à voir le module sur le backoffice. J'ai pourtant bien installée le module Formulaire de contact en version 4.1.1.
Qu'est ce que je peux bien faire ?
Merci pour votre aide.

**Comment by nenes25** [comment]
Bonjour,
Je viens de tester à l'instant sans problème particulier.
Avez-vous bien téléchargé le fichier eicaptcha.zip de cette release  ?
https://github.com/nenes25/eicaptcha/releases/tag/2.0.4

Cordialement,

**Comment by nenes25** [comment]
Pas de retours.
Clôture de l'issue.
