### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by breazz** [nenes25/eicaptcha#83]
prestashop v1.6.1.6

 Eicaptcha V 0.4.15

 Blue Mega Store

 Hi, at the time of submitting the form the error 500 appears.
I attach log php:

Mon, 03 Dec 2018 12:58:08 GMT [error] [client 79.32.196.204] - www.printed.it - AH01215: PHP Warning: require_once(/web/htdocs/www.printed.it/home/modules/eicaptcha/vendor/autoload.php): failed to open stream: No such file or directory in /web/htdocs/www.printed.it/home/modules/eicaptcha/eicaptcha.php on line 474: /web/htdocs/www.printed.it/home/index.php, referer https://www.printed.it/it/contattaci
--

Thank you very much

Cristian

**Comment by nenes25** [comment]
Hi,
Please download the release from this page.
https://github.com/nenes25/eicaptcha/releases/tag/0.4.15
and everthing should works.

Regards,
