### ISSUE TITLE
It does not work when we use Prestashop Invoice & Delivery Slips, Credit Slips Template Builder with Custom Number

### ISSUE THREAD

**Issue by taydotech** [nenes25/eicaptcha#84]
It does not work when we use this module, Why?
https://buy-addons.com/store/prestashop/module/prestashop-invoice-template-builder-module.html
Please help us !!!

**Comment by nenes25** [comment]
Hi,
I don't know this module it may have conflicts with mine.
But unfortunaletely i cannot check.

Regards,
