### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Juke29** [nenes25/eicaptcha#85]
### Your prestashop version
1.7.2.4 (update to latest version scheduled soon)
### Eicaptcha Version
2.0.4 for PS 1.7
### Do you use a specific theme
Classic theme (customized)
### Issue description
I cannot install the module (automatically or manually). Module import failure message : 
Je ne peux pas installer le module (automatiquement ou manuellement). Message d'erreur d'import :
> Aïe... le chargement a échoué.
> Que s'est-il passé ? 
> L'installation du module eicaptcha a échoué. Avant d'installer ce module, vous devez installer le(s) module(s) suivant(s) :
> - contactform

But I do not have any modules called "contactform" in the modules list. I do have default contact form with this theme though. I see a directory called "/contactform/" in "/modules/" but do not know if it is in use. How shall I identify it in my modules list?
Mais je ne vois pas de modules au nom de "contactform" dans la liste de modules. J'ai par contre le formulaire de contact par défaut avec ce thème. Je vois un répertoire nommé "/contactform/" dans "/modules/" mais je ne sais pas s'il est utilisé. Comment puis-je l'identifier dans ma liste de modules ?

When I drop the folder manually in /modules/ it is not detected in my modules list in PS.
Quand je drop le répertoire manuellement dans /modules/ il n'est pas détecté dans la liste des modules de PS.

I can provide the website link, but not in public please.
Je peux donner le lien du site mais pas de manière publique svp.

Thanks a lot, this module looks promising! I hope to be able to use it!
Merci beaucoup, ce module a l'air vraiment prometteur ! J'espère pouvoir l'utiliser !

**Comment by nenes25** [comment]
Bonjour,

Le message d'erreur est pourtant clair ;)
Il faut installer au préalable le module "contactform".
Il vous suffit de le chercher dans la liste des modules et de cliquer sur le bouton installer.
( C'est un module natif de prestashop qui est founi dans la distribution de base )

Cordialement,
Hervé

**Comment by Juke29** [comment]
Non j'avais déjà vidé le cache à chaque essai, tenté de réinstaller le module également.

J'ai trouvé par contre parmi les issues fermées la réponse à mon problème : https://github.com/nenes25/eicaptcha/issues/59#issuecomment-381508434

> OK I've found the error which is well related to the contactform module.
> When you update it, the template is still override in the classic theme with the old file which is not compatible anymore.
> The solution is to replace the file \themes\classic\modules\contactform\views\templates\widget\contactform.tpl with the new one : ( be carrefull to take the one compatible with your ps version : https://github.com/PrestaShop/PrestaShop/blob/1.7.3.x/themes/classic/modules/contactform/views/templates/widget/contactform.tpl )

J'ai récupéré les 2 bouts de code de ce fichier manquants dans le mien pour le mettre dans le mien et voilà nickel. Merci c'est résolu !

```
            {if isset($id_module)}
                <div class="form-group row">
                    <div class="offset-md-3">
                        {hook h='displayGDPRConsent' id_module=$id_module}
                    </div>
                </div>
            {/if}
```

et ensuite le footer avec le bouton : 

```
        <footer class="form-footer text-sm-right">
            <style>
                input[name=url] {
                    display: none !important;
                }
            </style>
            <input type="text" name="url" value=""/>
            <input type="hidden" name="token" value="{$token}" />
            <input class="btn btn-primary" type="submit" name="submitMessage" value="{l s='Send' d='Shop.Theme.Actions'}">
        </footer>
```

**Comment by nenes25** [comment]
Ok parfait
Je clos donc l'issue.

Cordialement,
Hervé
