### ISSUE TITLE
Errori  l'override di contacform.php non esiste

### ISSUE THREAD

**Issue by dinox76** [nenes25/eicaptcha#86]
Prestashop versione 1.7.2.4

### Eicaptcha Version

Nome del tema theme_naturecircle2

Php versione 5.6.38-0 + deb8u1

Chi mi aiuta per favore?

**Comment by nenes25** [comment]
Hi,
Could you please try to clean the cache ?
What is the eicaptcha version ?

Regards,

**Comment by dinox76** [comment]
ciao
eicaptcha 2.0.4
Ho pulito la cache sia del pannello che del browser

**Comment by dinox76** [comment]
è da ieri pomeriggio che sto impazzendo, non riesco a risolvere

**Comment by dinox76** [comment]
il problema che non sono un webmaster, quindi mi serve qualcuno che mi aiuti a trovare il file da modificare, perchè sicuramente sarà questo il problema.
Mi puoi aiutare per favore nenes?

**Comment by nenes25** [comment]
Hi
Could you please translate your messages in english as i'm not speaking italian.
Furthermore could you send me an url ?
Regards,

**Comment by dinox76** [comment]
what url do you need, of my site?

**Comment by dinox76** [comment]
the captcha is active on contacts
www.calabriascerra.com

**Comment by dinox76** [comment]
on advanced parameters of the Captcha module, it gives me this error: Errors
contacform.php override does not exist

**Comment by dinox76** [comment]
is there anyone who can help me please?

**Comment by dinox76** [comment]
Is there anyone who can help me?

**Comment by nenes25** [comment]
If evrething else works, there is no more thing to do.
The false positive will be fixed in the next release.

Regards,

**Comment by dinox76** [comment]
So what should I do?
leave everything as it does not work?
