### ISSUE TITLE
Captcha non visible sur le formulaire de contact

### ISSUE THREAD

**Issue by Thierryla** [nenes25/eicaptcha#87]
### Issue description: Le module fonctionne sur l’inscription au site, mais pas dans nous-contacter.

Du coup je désactive   "Activer pour le formulaire de contact"
et me sert de reCaptcha v2(autre module) pour avoir le captcha dans le formulaire de contact.

Bien sur je préférerais n'avoir qu'un module, le votre, pour avoir ce captcha sur les deux formulaire...
Merci de votre conseil et aide et surtout de votre travail.

**Comment by nenes25** [comment]
Bonjour,
Je n'ai aucune erreur sur ma version de test avec à priori la même configuration que vous.
https://web.h-hennes.fr/dev/prestashop/prestashop_1-7-4-4/fr/nous-contacter
( PS 1.7.4.4 et thème classique )
Pouvez-vous me fournir une url, avez-vous constaté une erreur ?
Cordialement,

**Comment by Thierryla** [comment]
Bonsoir,

En premier je vous remercie pour votre temps et gentillesse a me répondre et prendre en considération mon interrogation.
Alors … Je viens de revérifier en désactivant le module Recaptcha V2 par Comonsoft qui me permettait de voir le captcha sur ma page de contact…
Dois je commencer par me flageller ? Maintenant cela fonctionne, je n’ai pourtant rien changer et avais fait pleins d’essais d’installation et désinstallation… RRooooo

Je suis navré de vous avoir importuné ! Toutes mes excuses.

Cela fonctionne bien, le module de Comonsoft est désactivé et je vais quand meme attendre quelques jours avant de le desinstaller complètement.

Passez une tres bonne soirée, je me sent bête :-)
Encore merci.

https://oleyolacie.com/nous-contacter <https://oleyolacie.com/nous-contacter>


Thierry

**Comment by nenes25** [comment]
Bonjour Thierry,
L'essentiel est que cela fonctionne ;-)
Merci de votre retour, je ferme donc ce ticket.
Cordialement,
Hervé
