### ISSUE TITLE
The button "Send" does not work in contact form

### ISSUE THREAD

**Issue by Dragona771** [nenes25/eicaptcha#89]
###Prestashop 1.6.1.6

### Issue description- I installed this module and since I could not configure keys I deleted it.
 After deleting the button "send" in contact form stopped working. I decided to reinstall the same module and now module work fine but button "send" still does not work.
 Could you advise what can I do? Here is the link on my contact page:
https://www.b-pwr.com/us/information

**Comment by nenes25** [comment]
Since our last exchange the problem was corrected on your side.
Regards,
