### ISSUE TITLE
in prestashop 1.6.1.12

### ISSUE THREAD

**Issue by zenerry** [nenes25/eicaptcha#9]
Hi everyone,
I've just installed this module and integrated with recaptcha api.
But I've got a problem I can't solve.
When I hit the "submit " button it get's stuck in a white screen (error 500 I think) without any response.
I doesn't "return" to the "message sent correctly" screen and it doesn't create the message inside the backoffice either.

[POST https://www.vinoexpres.com/es/contactanos 500 ()]

Could anybody help me please? This is in vinoexpres .com

Thanks in advanced

**Comment by nenes25** [comment]
Hello,

Could you please enable the debug mode in prestashop :
https://www.prestashop.com/forums/topic/575132-how-to-enable-debug-mode-on-prestashop-17-and-older-versions-turn-on-error-reporting-blank-page/
 
And give me the error message ?

Regards,
Hervé

**Comment by zenerry** [comment]
Hello, did you see anything wrong in these messages?
    Thanks!
    
    
    El 08/06/2017 a las 11:05, Pol
      Senserrich - ARDStudio escribió:
    
    
      
      Those are the screenshots with the error, 
      
      Hope you can help me, I'm really in a hurry.
      Thanks in advanced.
      
      
      
      
      
      El 07/06/2017 a las 15:10, Hervé H.
        escribió:
      
      
        Hello,
        Could you please enable the debug mode in prestashop :
          https://www.prestashop.com/forums/topic/575132-how-to-enable-debug-mode-on-prestashop-17-and-older-versions-turn-on-error-reporting-blank-page/
        And give me the error message ?
        Regards,
          Hervé
        —
          You are receiving this because you authored the thread.
          Reply to this email directly, view it on GitHub, or mute the thread.
        
          
            
            
          
          
        
        {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nenes25/eicaptcha","title":"nenes25/eicaptcha","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nenes25/eicaptcha"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nenes25 in #9: Hello,\r\n\r\nCould you please enable the debug mode in prestashop :\r\nhttps://www.prestashop.com/forums/topic/575132-how-to-enable-debug-mode-on-prestashop-17-and-older-versions-turn-on-error-reporting-blank-page/\r\n \r\nAnd give me the error message ?\r\n\r\nRegards,\r\nHervé"}],"action":{"name":"View Issue","url":"https://github.com/nenes25/eicaptcha/issues/9#issuecomment-306789859"}}}
      
      
      -- 
         ARDStudio  
         Pol Senserrich  
             Solucions Visuals  
            
           ardstudio@gmail.com
           
          08700 Igualada - Barcelona 
          Tel Mòbil. +34 661 75 54 67 
          Skype. zenerry 
      
    
    
    -- 
       ARDStudio  
       Pol Senserrich  
           Solucions Visuals  
          
         ardstudio@gmail.com  
        08700 Igualada - Barcelona 
        Tel Mòbil. +34 661 75 54 67 
        Skype. zenerry

**Comment by nenes25** [comment]
Hello,
I see no screenshots in your answer ;-)

**Comment by zenerry** [comment]
Can you see them now.
    
    
    El 08/06/2017 a las 11:05, Pol
      Senserrich - ARDStudio escribió:
    
    
      
      Those are the screenshots with the error, 
      
      Hope you can help me, I'm really in a hurry.
      Thanks in advanced.
      
      
      
      
      
      El 07/06/2017 a las 15:10, Hervé H.
        escribió:
      
      
        Hello,
        Could you please enable the debug mode in prestashop :
          https://www.prestashop.com/forums/topic/575132-how-to-enable-debug-mode-on-prestashop-17-and-older-versions-turn-on-error-reporting-blank-page/
        And give me the error message ?
        Regards,
          Hervé
        —
          You are receiving this because you authored the thread.
          Reply to this email directly, view it on GitHub, or mute the thread.
        
          
            
            
          
          
        
        {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nenes25/eicaptcha","title":"nenes25/eicaptcha","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nenes25/eicaptcha"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nenes25 in #9: Hello,\r\n\r\nCould you please enable the debug mode in prestashop :\r\nhttps://www.prestashop.com/forums/topic/575132-how-to-enable-debug-mode-on-prestashop-17-and-older-versions-turn-on-error-reporting-blank-page/\r\n \r\nAnd give me the error message ?\r\n\r\nRegards,\r\nHervé"}],"action":{"name":"View Issue","url":"https://github.com/nenes25/eicaptcha/issues/9#issuecomment-306789859"}}}
      
      
      -- 
         ARDStudio  
         Pol Senserrich  
             Solucions Visuals  
            
           ardstudio@gmail.com
           
          08700 Igualada - Barcelona 
          Tel Mòbil. +34 661 75 54 67 
          Skype. zenerry 
      
    
    
    -- 
       ARDStudio  
       Pol Senserrich  
           Solucions Visuals  
          
         ardstudio@gmail.com  
        08700 Igualada - Barcelona 
        Tel Mòbil. +34 661 75 54 67 
        Skype. zenerry

**Comment by nenes25** [comment]
Nope still nothing,
You should try to drag & drop them on github page https://github.com/nenes25/eicaptcha/issues/9

**Comment by zenerry** [comment]
here you are
    
    
    El 09/06/2017 a las 12:52, Hervé H.
      escribió:
    
    
      Nope still nothing,
        You should try to drag & drop them on github page #9
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nenes25/eicaptcha","title":"nenes25/eicaptcha","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nenes25/eicaptcha"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nenes25 in #9: Nope still nothing,\r\nYou should try to drag \u0026 drop them on github page https://github.com/nenes25/eicaptcha/issues/9"}],"action":{"name":"View Issue","url":"https://github.com/nenes25/eicaptcha/issues/9#issuecomment-307358783"}}}
    
    
    -- 
       ARDStudio  
       Pol Senserrich  
           Solucions Visuals  
          
         ardstudio@gmail.com  
        08700 Igualada - Barcelona 
        Tel Mòbil. +34 661 75 54 67 
        Skype. zenerry

**Comment by nenes25** [comment]
OK i've them.

In fact the errors means that composer files are not found.
You can :
 run composer update in module directory
Otherwise you can download the release which bundled composer files from the folowing page : https://github.com/nenes25/eicaptcha/releases

Regards,

**Comment by zenerry** [comment]
Hi again,
could you please tell me what are composer files or module to update?
We've got all modules up to date in our backoffice.

Thanks.

**Comment by zenerry** [comment]
Thank you, just copy the vendor folder and coposer.json file of the bundle package into the module folder, and "voilà".
Everything running perfectly.
Thanks a lot!

**Comment by nenes25** [comment]
Hello,
Great it everything is working :-)

Regards,

**Comment by hossisa** [comment]
hi
i have a big problem with my account creation form!
the submit button is hide under the recaptcha box!
p.s :it works perfectly on mobile devices but its not working properly on desktop pc!
i attached the photo the way that it should be and the one with problem!
i'm amateur so plz explain as easy as possible!
the green button is missing!
![the way it is](https://user-images.githubusercontent.com/44140707/46919136-c425b280-cfe7-11e8-9b2e-bd3633abc27e.png)
![the way it should be](https://user-images.githubusercontent.com/44140707/46919137-c7b93980-cfe7-11e8-8036-dbd04d3ade73.png)
