### ISSUE TITLE
display recaptcha at login page

### ISSUE THREAD

**Issue by robertbaum** [nenes25/eicaptcha#91]
prestashop version 1.7.2

Eicaptcha Version 2.0.3

i am using a specific theme yes

how can me display the recaptcha at login page
what is the needed hook to do that
i added the recaptcha to the login-form.tpl and it worked but i needed to assign the public key to the login form and do this auto by this modul
thanks

**Comment by nenes25** [comment]
Hi,

Unfortunately this module is not designed to add captcha to the login page ;)
Feel free to fork it and to share your work if you manage to do this.
But this can not be considered as an issue, so i close it.

Regards,
Hervé
