### ISSUE TITLE
Installation of module eicaptcha failed

### ISSUE THREAD

**Issue by cesarpalacio** [nenes25/eicaptcha#92]
### Your prestashop version
1.7.4.1
### Eicaptcha Version
0.4.15
### Do you use a specific theme
Leothemes leo_lollipop version 1.0.0
### Issue description
The version of your module is not compliant with your PrestaShop version.

**Comment by nenes25** [comment]
Hi,
As you can read on the realeases page, v 0.4.15 is for prestashop  1.6 and under.
Please use version 2.0.x for prestashop 1.7

see : https://github.com/nenes25/eicaptcha/releases/tag/2.0.4

Regards,

**Comment by cesarpalacio** [comment]
Ups jejeje sorry.
THX
