### ISSUE TITLE
Installation 1.7 failed 

### ISSUE THREAD

**Issue by RollandH** [nenes25/eicaptcha#93]
Hello,

### Issue description 
![image](https://user-images.githubusercontent.com/48630130/54480112-f486ac80-4824-11e9-822e-fa2daed35235.png)
Tried several times and even disabling modules not Prestashop's, I get the same result.

Thak's for your attention.

Regards

**Comment by nenes25** [comment]
Hi,

You can try to download this file : https://github.com/nenes25/eicaptcha/releases/download/2.0.4/eicaptcha.zip

Regards,

**Comment by RollandH** [comment]
Hello,

Yes, It runs well with this realase.
Thank's for your answer and your efficiency
Regards
