### ISSUE TITLE
Recaptcha v3

### ISSUE THREAD

**Issue by snaperr** [nenes25/eicaptcha#94]
### Your prestashop version

1.7.5.1

### Eicaptcha Version

2.0.4

### Do you use a specific theme

Gearbest

### Issue description

Hi when u update to recaptcha v3? Thx :)

**Comment by tauaje** [comment]
Saludos 
No se puede instalar en Prestashop 1.7.5.1

**Comment by snaperr** [comment]
I use this plugin on my shop. I ask when update plugin to captcha v3

**Comment by tauaje** [comment]
Saludos
Yo quiero instalarlo en Prestashop 1.7.5.1 y no puedo
¿quería preguntarle si usted lo instalo?

**Comment by snaperr** [comment]
Yes, version: 2.0.4

**Comment by tauaje** [comment]
quiero instalarlo en Prestashop 1.7.5.1 la ultima versión de eicaptcha 0.4.15 y no me deja

**Comment by snaperr** [comment]
U must install 2.0.4 not 0.4.15 - this is for 1.6 prestashop
2.0.4 - is for 1.7 prestashop

**Comment by tauaje** [comment]
Tampoco me deja instalarlo, me dice modulo no actualizado

**Comment by snaperr** [comment]
https://github.com/nenes25/eicaptcha/releases/tag/2.0.4

**Comment by nenes25** [comment]
Hi,

It's not planned yet to update this module to the last recaptcha version.
I have not enough time to do it right now.
I'll see later maybe.

Regards,

**Comment by tauaje** [comment]
Saludos Muchas gracias por sus respuesta
Saludos

Ya he instalado Eicaptcha, se ve en formulario de registro y formulario de contacto, ¿ pero como puedo ponerlo en Newsletter popup?

**Comment by nenes25** [comment]
@tauaje it's not that issue subject but it's not possible to add a captcha to the newsletter whith this module.
Regards,

**Comment by tauaje** [comment]
Muchas gracias
Mis disculpas, soy nuevo en esto y estoy como loco intentando de añadir en newsletter, y no sabia donde acudir, gracias y nueva mente mis disculpas

**Comment by snaperr** [comment]
@nenes25 why i dont have picture captcha on normal browser in chrome? When i use incognito mode on chrome i must select picture, on normal mode i dont have this. I only click "im not robot" and this all.

**Comment by nenes25** [comment]
@snaperr it's defaut google recaptcha behaviour.
Depending on the information it gets on you it display something.
In incognito mode as it have less information, it's harder to take the captcha ;)
