### ISSUE TITLE
Not working on create user account

### ISSUE THREAD

**Issue by grabelle** [nenes25/eicaptcha#95]
### Your prestashop version
1.7.5.1

### Eicaptcha Version
latest (2.0.4)

### Do you use a specific theme
yes but not for auth

### Issue description
Capcha is OK for contact form but is not display in the create account form (and so when we validate, we have an error because recaptcha expected)

Thanks for your help ...

**Comment by nenes25** [comment]
Hi,
I've no issue with the classic theme as you can see here : https://web.h-hennes.fr/dev/prestashop/prestashop_1-7-5-1/fr/connexion?create_account=1

So thee issue seems to be related with your theme.
Without any additional information i can't help you.
Regards,

**Comment by laurentqc** [comment]
Bonjour,
j'ai un problème similaire sur le ps1.6. Le captcha existe dans la page de création de compte mais semble se retrouver hors champs, ne laissant que le texte ''captcha'' au dessus du bouton de validation ''s'inscrire''.
comment corriger ceci ? 
ma page: https://www.magasinade.com/qc/login?back=my-account?back=my-account
bien à vous,

**Comment by nenes25** [comment]
@laurentqc merci d'ouvrir une autre issue elle n'est la lié à la demande initiale.
J'ai vite fait un tour sur votre site j'ai l'impression que vous avez plusieurs captcha installé ?!

Cordialement,
Hervé
