### ISSUE TITLE
Customize captcha 

### ISSUE THREAD

**Issue by Jhannys** [nenes25/eicaptcha#97]
### I need to modify some recaptcha properties (size and position). I tried modifying eicaptcha.css file, but it doesn't work. What could I do? Thank you all!

**Comment by nenes25** [comment]
Hi,
It is the right thing to do ;-)
What kind of modification doesn't works ?

By the way the version your are using is not for ps 1.7
Please download this one : https://github.com/nenes25/eicaptcha/releases/tag/2.0.4

Regards,
