### ISSUE TITLE
Captcha hors champs

### ISSUE THREAD

**Issue by laurentqc** [nenes25/eicaptcha#98]
Bonjour,

Effectivement, j'essaye plusieurs captcha et ils font tous le même problème pour la page de compte. C'est à dire que la boite captcha s'affiche pour une seconde et disparait, ne laissant que le texte ''captcha'' au dessus du bouton ''s'inscrire'' sur les browsers Firefox et Chrome mais s'affiche correctement sur Edge. 

ma page: https://www.magasinade.com/qc/login?back=my-account?back=my-account

**Comment by nenes25** [comment]
Dans un premier temps il faudrait déjà faire le ménage et n'en laisser qu'un seul.
Il est possible qu'il y'ai des conflits entre les différentes versions.

**Comment by laurentqc** [comment]
Désolé, c'est fait,  je n'ai gardé que le votre. Cependant, ça le faisait déjà avant que j'installe le deuxième.

**Comment by nenes25** [comment]
Bizarre effectivement le problème est toujours la.
Pouvez-vous essayer de désactiver la minification js ( si elle est active ) ?

**Comment by laurentqc** [comment]
tout est désactivé, le cache aussi

**Comment by laurentqc** [comment]
faut il renseigner le header.tpl ?

**Comment by laurentqc** [comment]
j'ai trouvé la solution sur un forum en renseignant manuellement le header.tpl et l'index.php à la racine. je n'ai plus de problème. cela pourrait être utile pour votre module.
https://shop.devcustom.net/fr/content/9-mise-en-place-captcha?content_only=1
merci pour vos efforts.
Bien à vous

**Comment by nenes25** [comment]
OK parfait si c'est corrigé.
Je ne suis pas fan de cette approche mais l'essentiel est que cela fonctionne :-)
